import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

// Banco real de Brasil (Ruta 2 — Ritmo y Trópico). Mismo estándar que Colombia/Perú/Chile:
// 22 preguntas verificadas por categoría, sin solapamiento entre rondas.
export const BANCO_BRASIL: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Brasil?", opciones: ["Río de Janeiro", "São Paulo", "Brasilia", "Salvador"], correctaIndex: 2, fuente: "REST Countries API", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea la costa de Brasil?", opciones: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué continente está ubicado Brasil?", opciones: ["América del Norte", "América del Sur", "África", "Europa"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el idioma oficial de Brasil?", opciones: ["Español", "Portugués", "Inglés", "Francés"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el río más caudaloso del mundo, que atraviesa Brasil?", opciones: ["Nilo", "Misisipi", "Amazonas", "Yangtsé"], correctaIndex: 2, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Con cuántos países limita Brasil?", opciones: ["8", "9", "10", "12"], correctaIndex: 2, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la ciudad más poblada de Brasil?", opciones: ["Brasilia", "Río de Janeiro", "São Paulo", "Salvador"], correctaIndex: 2, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama la selva tropical que cubre gran parte del norte de Brasil?", opciones: ["Selva Lacandona", "Selva Amazónica", "Selva del Darién", "Selva Negra"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué famosa estatua religiosa corona un cerro en Río de Janeiro?", opciones: ["Cristo Redentor", "Virgen de Aparecida", "Torre Eiffel", "Estatua de la Libertad"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la moneda oficial de Brasil?", opciones: ["Peso", "Real", "Dólar", "Sol"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué línea imaginaria atraviesa la ciudad brasileña de Macapá?", opciones: ["Trópico de Cáncer", "Meridiano de Greenwich", "Línea del Ecuador", "Círculo Polar Ártico"], correctaIndex: 2, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuántos estados tiene Brasil, sin contar el Distrito Federal?", opciones: ["24", "26", "27", "30"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Brasil?", opciones: ["Pico Bolívar", "Pico da Neblina", "Aconcagua", "Chimborazo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué estado brasileño tiene la mayor extensión territorial?", opciones: ["Pará", "Amazonas", "Mato Grosso", "Bahía"], correctaIndex: 1, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué cataratas comparte Brasil con Argentina?", opciones: ["Cataratas del Niágara", "Cataratas Victoria", "Cataratas del Iguazú", "Salto Ángel"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué humedal, el más grande del mundo, se ubica en el suroeste de Brasil?", opciones: ["Everglades", "Pantanal", "Ciénaga Grande", "Sundarbans"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Cuál es la capital financiera de Brasil, aunque no es la capital política?", opciones: ["Brasilia", "São Paulo", "Río de Janeiro", "Salvador"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué archipiélago brasileño en el Atlántico es Patrimonio de la Humanidad por su vida marina?", opciones: ["Islas Galápagos", "Fernando de Noronha", "Islas Malvinas", "San Andrés"], correctaIndex: 1, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué río, afluente del Amazonas, marca frontera entre Brasil y varios países vecinos?", opciones: ["Río Negro", "Río de la Plata", "Río Orinoco", "Río Magdalena"], correctaIndex: 0, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿En qué región de Brasil se encuentra la mayor parte de la Amazonía?", opciones: ["Región Sur", "Región Norte", "Región Nordeste", "Región Sudeste"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la capital del estado de Bahía?", opciones: ["Recife", "Salvador", "Fortaleza", "Natal"], correctaIndex: 1, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad brasileña fue sede de los Juegos Olímpicos de 2016?", opciones: ["São Paulo", "Brasilia", "Río de Janeiro", "Salvador"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿Qué país europeo colonizó Brasil?", opciones: ["España", "Portugal", "Francia", "Países Bajos"], correctaIndex: 1, fuente: "Wikipedia — Historia de Brasil", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año Brasil se independizó de Portugal?", opciones: ["1810", "1822", "1889", "1900"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Quién proclamó la independencia de Brasil?", opciones: ["Simón Bolívar", "Pedro I", "Getúlio Vargas", "José de San Martín"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué forma de gobierno tiene Brasil actualmente?", opciones: ["Monarquía", "República federal", "Dictadura militar", "Colonia"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año Brasil abolió la esclavitud?", opciones: ["1822", "1888", "1900", "1950"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿Qué título tuvo Pedro I al independizar Brasil?", opciones: ["Rey", "Emperador", "Presidente", "Primer Ministro"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año se proclamó la República en Brasil?", opciones: ["1822", "1889", "1900", "1930"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué explorador portugués es considerado el \"descubridor\" de Brasil en 1500?", opciones: ["Vasco da Gama", "Pedro Álvares Cabral", "Fernando de Magallanes", "Cristóbal Colón"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué dictadura militar gobernó Brasil entre 1964 y 1985?", opciones: ["Dictadura de Vargas", "Dictadura militar brasileña", "Estado Novo", "Segundo Imperio"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Quién lideró el \"Estado Novo\" en Brasil en los años 1930-40?", opciones: ["Getúlio Vargas", "Juscelino Kubitschek", "Fernando Collor", "Lula da Silva"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué presidente impulsó la construcción de Brasilia como nueva capital en 1960?", opciones: ["Getúlio Vargas", "Juscelino Kubitschek", "João Goulart", "Castelo Branco"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año volvió la democracia a Brasil tras la dictadura militar?", opciones: ["1975", "1985", "1990", "2000"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿Cómo se llamó el primer emperador de Brasil?", opciones: ["Pedro I", "Pedro II", "Vargas", "Cabral"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué hijo de Pedro I gobernó Brasil como su segundo y último emperador?", opciones: ["Pedro II", "Pedro III", "Vargas", "Deodoro da Fonseca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Quién proclamó la República de Brasil en 1889?", opciones: ["Deodoro da Fonseca", "Getúlio Vargas", "Pedro II", "Juscelino Kubitschek"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué tratado de 1494 dividió las tierras del Nuevo Mundo entre España y Portugal, influyendo en el territorio de Brasil?", opciones: ["Tratado de Tordesillas", "Tratado de Utrecht", "Tratado de Versalles", "Tratado de París"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Cómo se llama el período de la historia de Brasil marcado por el auge del café en el siglo XIX y XX?", opciones: ["Ciclo del oro", "Ciclo del café", "Ciclo del azúcar", "Ciclo del caucho"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué ciclo económico colonial se basó en la extracción de caucho en la Amazonía?", opciones: ["Ciclo del oro", "Ciclo del caucho", "Ciclo del café", "Ciclo del azúcar"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿En qué siglo tuvo su auge el \"ciclo del oro\" en la región de Minas Gerais?", opciones: ["Siglo XVI", "Siglo XVII", "Siglo XVIII", "Siglo XIX"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué corte real europea se trasladó a Río de Janeiro en 1808 huyendo de las tropas napoleónicas?", opciones: ["La corte española", "La corte portuguesa", "La corte francesa", "La corte inglesa"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué nombre recibió la Constitución brasileña promulgada en 1988, tras el fin de la dictadura?", opciones: ["Constitución Ciudadana", "Constitución Federal", "Carta Magna", "Constitución Vargas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué ciudad fue la primera capital de Brasil durante el período colonial?", opciones: ["Río de Janeiro", "Salvador", "São Paulo", "Brasilia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué festividad brasileña es famosa mundialmente por sus desfiles de samba?", opciones: ["Semana Santa", "Carnaval", "Día de Muertos", "Navidad"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué baile y género musical típico de Brasil nació en Río de Janeiro?", opciones: ["Samba", "Tango", "Salsa", "Flamenco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué religión es mayoritaria en Brasil?", opciones: ["Islam", "Catolicismo", "Budismo", "Hinduismo"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué arte marcial y danza brasileña, creada por esclavos africanos, combina lucha y música?", opciones: ["Capoeira", "Kickboxing", "Karate", "Judo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama el género musical urbano brasileño de ritmo acelerado, originado en Río?", opciones: ["Funk carioca", "Reggaetón", "Trap", "Merengue"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿En qué ciudad se celebra el Carnaval más famoso de Brasil?", opciones: ["São Paulo", "Río de Janeiro", "Salvador", "Brasilia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué estructuras compiten en el desfile de Carnaval de Río representando comunidades?", opciones: ["Comparsas", "Escuelas de samba", "Bandas", "Clanes"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué género musical suave y romántico nació en Brasil en los años 50-60, mezcla de samba y jazz?", opciones: ["Bossa nova", "Reggae", "Bolero", "Mariachi"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Cuál es el deporte más popular de Brasil?", opciones: ["Baloncesto", "Fútbol", "Béisbol", "Rugby"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué escritor brasileño escribió \"Dom Casmurro\"?", opciones: ["Jorge Amado", "Machado de Assis", "Paulo Coelho", "Clarice Lispector"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué autor brasileño escribió \"El Alquimista\"?", opciones: ["Machado de Assis", "Paulo Coelho", "Jorge Amado", "Clarice Lispector"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué influencia africana es central en la música, comida y religión de Bahía?", opciones: ["Yoruba", "Maya", "Inca", "Azteca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué religión afrobrasileña sincrética se practica ampliamente en Bahía?", opciones: ["Vudú", "Candomblé", "Rastafarismo", "Sijismo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué escritor brasileño es autor de \"Gabriela, clavo y canela\"?", opciones: ["Machado de Assis", "Jorge Amado", "Paulo Coelho", "Clarice Lispector"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento de origen africano, un arco musical con calabaza, se usa en la capoeira?", opciones: ["Berimbau", "Cuatro", "Charango", "Bandoneón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama una de las escuelas de samba más antiguas de Río, fundada en 1928?", opciones: ["Portela", "Estação Primeira de Mangueira", "Beija-Flor", "Salgueiro"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escritora brasileña, nacida en Ucrania, es autora de \"La hora de la estrella\"?", opciones: ["Clarice Lispector", "Cecília Meireles", "Rachel de Queiroz", "Nélida Piñón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿En qué ciudad brasileña se originó el \"frevo\", género musical y danza de carnaval?", opciones: ["Salvador", "Recife", "Fortaleza", "Belém"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué deidades africanas se veneran en el Candomblé?", opciones: ["Orixás", "Loas", "Kamis", "Devas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué movimiento cultural y musical brasileño de los años 60 mezcló rock, samba y vanguardia?", opciones: ["Tropicália", "Bossa Nova", "Sertanejo", "Axé"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué compositor brasileño, junto con Tom Jobim, escribió \"Garota de Ipanema\" (Chica de Ipanema)?", opciones: ["Vinicius de Moraes", "Chico Buarque", "Caetano Veloso", "Gilberto Gil"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué género musical brasileño de raíz rural es hoy uno de los más escuchados del país?", opciones: ["Sertanejo", "Fado", "Cumbia", "Vallenato"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Cuál es el plato nacional de Brasil, hecho con frijoles negros y carne de cerdo?", opciones: ["Feijoada", "Empanada", "Tamal", "Ceviche"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta y baya energética brasileña, típica en batidos, es muy popular?", opciones: ["Açaí", "Mango", "Papaya", "Piña"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida alcohólica brasileña, hecha de caña de azúcar, es base de la caipirinha?", opciones: ["Tequila", "Cachaça", "Ron", "Whisky"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la carne asada al estilo brasileño, servida en restaurantes \"churrascarías\"?", opciones: ["Churrasco", "Asado argentino", "Barbacoa", "Parrillada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida caliente, similar al mate, se toma mucho en el sur de Brasil?", opciones: ["Mate", "Chocolate", "Café con leche", "Chicha"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Qué ingrediente principal lleva la caipirinha además de cachaça, azúcar y hielo?", opciones: ["Limón", "Naranja", "Fresa", "Menta"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿De qué región de Brasil es típico el \"acarajé\", buñuelo frito relleno de camarón?", opciones: ["Bahía", "São Paulo", "Sur", "Amazonía"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué tubérculo, base de muchos platos brasileños, también se conoce como yuca?", opciones: ["Mandioca", "Papa", "Ñame", "Batata"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato brasileño de arroz, frijoles, carne y farofa se sirve a diario?", opciones: ["Feijoada", "Prato feito", "Ceviche", "Tamal"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué harina tostada, hecha de mandioca, acompaña muchos platos brasileños?", opciones: ["Farofa", "Polenta", "Cuscús", "Arepa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué queso brasileño se usa para hacer el \"pão de queijo\"?", opciones: ["Queso minas", "Mozzarella", "Parmesano", "Queso crema"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta amazónica, de pulpa cremosa, se usa en helados y postres brasileños?", opciones: ["Cupuaçu", "Manzana", "Pera", "Uva"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Qué plato del norte de Brasil se prepara con pato y tucupí (jugo de mandioca fermentado)?", opciones: ["Pato no tucupí", "Feijoada", "Vatapá", "Moqueca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué guiso de pescado con leche de coco y aceite de dendê es típico de Bahía?", opciones: ["Moqueca", "Vatapá", "Feijoada", "Churrasco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato bahiano se prepara con pan remojado, camarones, maní y aceite de palma?", opciones: ["Vatapá", "Moqueca", "Acarajé", "Farofa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿De qué palma se extrae el aceite de dendê, clave en la cocina bahiana?", opciones: ["Palma africana", "Palma de coco", "Palma real", "Palma datilera"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida navideña brasileña se sirve caliente con vino y especias?", opciones: ["Quentão", "Ponche", "Rompope", "Sangría"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué dulce típico brasileño se hace con leche condensada y chocolate, en forma de bolita?", opciones: ["Brigadeiro", "Alfajor", "Trufa", "Marquesote"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué pescado de río amazónico gigante es muy apreciado en la gastronomía local?", opciones: ["Pirarucú", "Salmón", "Bacalao", "Atún"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué carne es la base del churrasco gaúcho, típico del sur de Brasil?", opciones: ["Carne de res", "Cerdo", "Pollo", "Cordero"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el pan de queso brasileño, hecho con harina de mandioca?", opciones: ["Pão de queijo", "Arepa", "Empanada", "Tamal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta roja amazónica y ácida se usa para jugos y es símbolo regional?", opciones: ["Camu camu", "Manzana", "Fresa", "Durazno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Cuál es el bioma más extenso de Brasil, famoso por su biodiversidad?", opciones: ["Selva Amazónica", "Desierto del Sahara", "Tundra", "Sabana africana"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué felino, el más grande de América, habita en Brasil?", opciones: ["Jaguar", "León", "Tigre", "Leopardo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave grande y colorida, típica de la Amazonía, es conocida por su pico grande?", opciones: ["Tucán", "Águila", "Pingüino", "Avestruz"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué río es el más caudaloso del mundo y atraviesa Brasil?", opciones: ["Nilo", "Amazonas", "Misisipi", "Danubio"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué humedal brasileño es el más grande del mundo?", opciones: ["Pantanal", "Everglades", "Camargue", "Okavango"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Qué primate pequeño, símbolo de Brasil, es endémico de la Mata Atlántica?", opciones: ["Mono tití león dorado", "Gorila", "Chimpancé", "Orangután"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué reptil gigante habita los ríos y pantanos brasileños, similar al cocodrilo?", opciones: ["Yacaré", "Varano", "Iguana", "Camaleón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué bioma costero brasileño, muy reducido hoy, alberga alta biodiversidad única?", opciones: ["Mata Atlántica", "Sabana", "Tundra", "Estepa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué pez amazónico gigante puede medir hasta 3 metros?", opciones: ["Pirarucú", "Bagre", "Trucha", "Salmón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero acuático, en peligro, habita los ríos de la Amazonía?", opciones: ["Delfín rosado (boto)", "Foca", "Nutria marina", "Manatí ártico"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave rapaz gigante, una de las águilas más grandes del mundo, habita la Amazonía?", opciones: ["Águila harpía", "Cóndor andino", "Águila calva", "Halcón peregrino"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué proporción aproximada de la Amazonía se encuentra dentro de Brasil?", opciones: ["Menos del 30%", "Alrededor del 60%", "Toda la Amazonía", "Menos del 10%"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Qué serpiente venenosa es una de las más grandes de Sudamérica y habita Brasil?", opciones: ["Surucucú (Lachesis)", "Cobra real", "Mamba negra", "Víbora de Gabón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se conoce popularmente al delfín de río amazónico de color rosado?", opciones: ["Boto", "Orca", "Marsopa", "Delfín nariz de botella"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero, el roedor más grande del mundo, vive en zonas húmedas de Brasil?", opciones: ["Capibara", "Castor", "Nutria", "Ardilla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave no voladora, la más grande de Sudamérica, habita el Cerrado y Pantanal brasileños?", opciones: ["Ñandú", "Avestruz", "Emú", "Casuario"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué bioma brasileño de sabana tropical, rico en biodiversidad, cubre el centro del país?", opciones: ["Cerrado", "Caatinga", "Pampa", "Taiga"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué bioma semiárido del nordeste brasileño se caracteriza por vegetación espinosa?", opciones: ["Caatinga", "Cerrado", "Pantanal", "Mata Atlántica"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de árbol es símbolo de la extracción histórica de caucho en la Amazonía?", opciones: ["Hevea brasiliensis (árbol del caucho)", "Roble", "Pino", "Ceibo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cuántas especies de aves aproximadamente se estima que habitan Brasil?", opciones: ["Cerca de 1.900", "Cerca de 500", "Cerca de 100", "Cerca de 5.000"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran felino manchado, casi extinto en algunas regiones, es tope de cadena en la Amazonía?", opciones: ["Jaguar", "Puma", "Ocelote", "Lince"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional brasileño protege la mayor cascada de agua dulce del país, compartida con Argentina?", opciones: ["Parque Nacional del Iguazú", "Parque Nacional Pantanal", "Parque Nacional Chapada Diamantina", "Parque Nacional Amazônia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte más popular en Brasil?", opciones: ["Fútbol", "Béisbol", "Hockey", "Rugby"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cuántas veces ha sido campeón del Mundial de fútbol la selección de Brasil (el mayor número de títulos)?", opciones: ["3", "5", "7", "2"], correctaIndex: 1, fuente: "FIFA", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué futbolista brasileño es considerado uno de los mejores de la historia, ganador de 3 mundiales?", opciones: ["Pelé", "Maradona", "Messi", "Cristiano Ronaldo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué deporte de playa, variante del fútbol, es muy popular en las costas brasileñas?", opciones: ["Fútbol playa", "Voleibol de nieve", "Rugby playa", "Hockey sobre hielo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué arte marcial de origen brasileño se hizo famosa mundialmente en las artes marciales mixtas (MMA)?", opciones: ["Jiu-jitsu brasileño", "Karate", "Taekwondo", "Judo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿En qué ciudad brasileña se disputó la final del Mundial de fútbol de 2014?", opciones: ["São Paulo", "Río de Janeiro", "Brasilia", "Salvador"], correctaIndex: 1, fuente: "FIFA", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad brasileña fue sede de los Juegos Olímpicos de verano 2016?", opciones: ["São Paulo", "Brasilia", "Río de Janeiro", "Salvador"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué futbolista brasileño, apodado \"El Fenómeno\", ganó el Mundial en 1994 y 2002?", opciones: ["Ronaldo Nazário", "Ronaldinho", "Kaká", "Romário"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué disciplina de vóleibol, muy popular en Brasil, se juega en la arena?", opciones: ["Vóley playa", "Vóley sobre hielo", "Vóley acuático", "Vóley de sala solamente"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué piloto brasileño de Fórmula 1 es tricampeón mundial y falleció en 1994?", opciones: ["Ayrton Senna", "Nelson Piquet", "Rubens Barrichello", "Felipe Massa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué estadio de Río de Janeiro es uno de los más famosos e históricos del fútbol mundial?", opciones: ["Maracaná", "Camp Nou", "Wembley", "Bernabéu"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué liga de fútbol brasileño reúne a los principales clubes del país?", opciones: ["Brasileirão", "La Liga", "Serie A", "Premier League"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿En qué año Brasil ganó su primer Mundial de fútbol?", opciones: ["1950", "1958", "1962", "1970"], correctaIndex: 1, fuente: "FIFA", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Cuántos títulos mundiales de Fórmula 1 ganó Ayrton Senna?", opciones: ["2", "3", "4", "1"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué jugador brasileño ganó el Balón de Oro FIFA en 2007, jugando en el Real Madrid y AC Milan?", opciones: ["Kaká", "Neymar", "Ronaldinho", "Romário"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué apodo recibe la selección brasileña de fútbol?", opciones: ["La Canarinha", "Los Albicelestes", "La Tricolor", "Los Cafeteros"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué Mundial Brasil sufrió una histórica derrota 7-1 ante Alemania en semifinales, jugado en casa?", opciones: ["2010", "2014", "2018", "2006"], correctaIndex: 1, fuente: "FIFA", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué evento multideportivo se celebró en Brasil en 2016 además de los Juegos Olímpicos?", opciones: ["Juegos Paralímpicos", "Juegos Panamericanos", "Juegos Asiáticos", "Juegos de la Commonwealth"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué jugador brasileño, ganador de 3 Mundiales (1958, 1962, 1970), es apodado \"O Rei\" (El Rey)?", opciones: ["Pelé", "Garrincha", "Zico", "Sócrates"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué mediocampista brasileño, capitán en el Mundial de 1982 y también médico, fue símbolo de la \"Democracia Corintiana\"?", opciones: ["Sócrates", "Zico", "Falcão", "Cerezo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué circuito de Fórmula 1 brasileño incluye parte de su trazado con el nombre de Ayrton Senna?", opciones: ["Autódromo de Interlagos", "Circuito de Mónaco", "Silverstone", "Monza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Cuántos Mundiales de fútbol ha ganado Brasil en total (hasta 2022)?", opciones: ["4", "5", "6", "3"], correctaIndex: 1, fuente: "FIFA", dificultad: "dificil" },
    ],
  },
};
