import type { PreguntaTrivia } from "./onboarding-data";
import { shuffle, shuffleOpciones } from "./trivia-bank";

export const RETO_CULTURA_GENERAL_CONFIG = { cantidad: 20 };

/** Banco de cultura general (mundial, no atado a un país) para el reto compartible
 * de la sección Retos — ~195 preguntas repartidas en las 6 categorías, para que
 * un reto de 20 preguntas casi nunca se repita igual entre partidas distintas. */
const BANCO_CULTURA_GENERAL: PreguntaTrivia[] = [
  { categoria: "Geografía", pregunta: "¿Cuál es el río más largo del mundo?", opciones: ["Nilo", "Amazonas", "Yangtsé", "Misisipi"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Cuál es el país más grande del mundo por área?", opciones: ["Rusia", "Canadá", "China", "Estados Unidos"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es el desierto más grande del mundo?", opciones: ["Sahara", "Gobi", "Antártida", "Kalahari"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la montaña más alta del mundo?", opciones: ["K2", "Everest", "Kilimanjaro", "Aconcagua"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Qué océano es el más grande del planeta?", opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctaIndex: 2, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Japón?", opciones: ["Tokio", "Kioto", "Osaka", "Seúl"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿En qué continente está Egipto?", opciones: ["Asia", "África", "Europa", "Oceanía"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿En qué año terminó la Segunda Guerra Mundial?", opciones: ["1943", "1945", "1948", "1950"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué antigua civilización construyó las pirámides de Giza?", opciones: ["Los mayas", "Los egipcios", "Los romanos", "Los griegos"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿En qué año cayó el Muro de Berlín?", opciones: ["1985", "1989", "1991", "1993"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Quién fue el primer hombre en pisar la Luna?", opciones: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], correctaIndex: 1, fuente: "NASA", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué imperio construyó el Coliseo de Roma?", opciones: ["Imperio Romano", "Imperio Bizantino", "Imperio Otomano", "Imperio Persa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Rembrandt"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿En qué idioma se escribió originalmente \"Romeo y Julieta\"?", opciones: ["Francés", "Italiano", "Inglés", "Alemán"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué instrumento tiene 88 teclas?", opciones: ["Piano", "Órgano", "Acordeón", "Clavecín"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué escritor creó a Sherlock Holmes?", opciones: ["Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "Charles Dickens"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿En qué país se originó el origami?", opciones: ["China", "Japón", "Corea", "Tailandia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿De qué país es originaria la pizza margarita?", opciones: ["Francia", "España", "Italia", "Grecia"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué grano se usa para hacer el chocolate?", opciones: ["Café", "Cacao", "Vainilla", "Avellana"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es el mayor productor mundial de café?", opciones: ["Colombia", "Brasil", "Vietnam", "Etiopía"], correctaIndex: 1, fuente: "FAO", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Cuál es el ingrediente principal del hummus?", opciones: ["Lentejas", "Garbanzos", "Frijoles", "Habas"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el animal terrestre más grande del mundo?", opciones: ["Rinoceronte", "Elefante africano", "Hipopótamo", "Jirafa"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el mamífero más grande del mundo?", opciones: ["Elefante africano", "Ballena azul", "Tiburón blanco", "Cachalote"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuántos corazones tiene un pulpo?", opciones: ["1", "2", "3", "4"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal es el símbolo de Australia junto al koala?", opciones: ["Canguro", "Panda", "Oso polar", "Puma"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el felino más rápido del mundo?", opciones: ["León", "Guepardo", "Tigre", "Puma"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cada cuántos años se celebran los Juegos Olímpicos de verano?", opciones: ["2", "3", "4", "5"], correctaIndex: 2, fuente: "COI", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos jugadores tiene un equipo de fútbol en la cancha?", opciones: ["9", "10", "11", "12"], correctaIndex: 2, fuente: "FIFA", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿En qué país se inventó el baloncesto?", opciones: ["Estados Unidos", "Canadá", "Inglaterra", "Francia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Cada cuántos años se juega el Mundial de fútbol?", opciones: ["2", "3", "4", "5"], correctaIndex: 2, fuente: "FIFA", dificultad: "facil" },

  // Geografía
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Francia?", opciones: ["Marsella", "París", "Lyon", "Niza"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Australia?", opciones: ["Sídney", "Melbourne", "Canberra", "Perth"], correctaIndex: 2, fuente: "Wikidata", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Cuál es el país más poblado del mundo?", opciones: ["China", "India", "Estados Unidos", "Indonesia"], correctaIndex: 1, fuente: "ONU", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Cuál es el lago de agua dulce más grande del mundo por superficie?", opciones: ["Lago Baikal", "Lago Superior", "Lago Victoria", "Mar Caspio"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Geografía", pregunta: "¿Cuál es el país más poblado de África?", opciones: ["Egipto", "Nigeria", "Etiopía", "Sudáfrica"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Qué estrecho separa España de Marruecos?", opciones: ["Estrecho de Bering", "Estrecho de Gibraltar", "Estrecho de Ormuz", "Estrecho de Magallanes"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Canadá?", opciones: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correctaIndex: 2, fuente: "Wikidata", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Cuál es el país más pequeño del mundo?", opciones: ["Mónaco", "San Marino", "Ciudad del Vaticano", "Liechtenstein"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿En qué continente está el desierto del Sahara?", opciones: ["Asia", "África", "Oceanía", "América"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la cordillera más larga del mundo?", opciones: ["Himalaya", "Andes", "Montañas Rocosas", "Alpes"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Rusia?", opciones: ["San Petersburgo", "Moscú", "Kiev", "Minsk"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es el río más largo de Sudamérica?", opciones: ["Orinoco", "Paraná", "Amazonas", "Magdalena"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Qué país tiene forma de bota en el mapa?", opciones: ["España", "Italia", "Grecia", "Portugal"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Egipto?", opciones: ["Alejandría", "El Cairo", "Guiza", "Luxor"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es el continente más pequeño del mundo?", opciones: ["Europa", "Oceanía", "Antártida", "América"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Qué país tiene más husos horarios en su territorio?", opciones: ["Rusia", "Estados Unidos", "Francia", "China"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Perú?", opciones: ["Cusco", "Lima", "Arequipa", "Trujillo"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Qué río atraviesa Egipto?", opciones: ["Éufrates", "Tigris", "Nilo", "Jordán"], correctaIndex: 2, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la isla más grande del mundo?", opciones: ["Madagascar", "Groenlandia", "Borneo", "Sumatra"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Alemania?", opciones: ["Múnich", "Berlín", "Fráncfort", "Hamburgo"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es el punto más bajo de la Tierra en tierra firme?", opciones: ["Fosa de las Marianas", "Mar Muerto", "Valle de la Muerte", "Depresión de Danakil"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Geografía", pregunta: "¿En qué país se encuentra Machu Picchu?", opciones: ["Bolivia", "Perú", "Ecuador", "Chile"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Grecia?", opciones: ["Atenas", "Esparta", "Tesalónica", "Corinto"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Cuál es el volcán activo más alto del mundo?", opciones: ["Kilimanjaro", "Ojos del Salado", "Etna", "Fuji"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Geografía", pregunta: "¿Cuál es la capital de Portugal?", opciones: ["Oporto", "Lisboa", "Faro", "Coímbra"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
  { categoria: "Geografía", pregunta: "¿Qué mar se encuentra entre Europa y África?", opciones: ["Mar Rojo", "Mar Mediterráneo", "Mar Negro", "Mar Báltico"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },

  // Historia
  { categoria: "Historia", pregunta: "¿Quién fue el primer presidente de Estados Unidos?", opciones: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿En qué año comenzó la Primera Guerra Mundial?", opciones: ["1912", "1914", "1916", "1918"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué civilización construyó Machu Picchu?", opciones: ["Aztecas", "Incas", "Mayas", "Olmecas"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Quién llegó a América en 1492?", opciones: ["Vasco da Gama", "Cristóbal Colón", "Fernando de Magallanes", "Américo Vespucio"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿En qué año llegó el hombre a la Luna?", opciones: ["1965", "1969", "1971", "1975"], correctaIndex: 1, fuente: "NASA", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué imperio gobernó gran parte de Europa bajo Napoleón?", opciones: ["Imperio Austrohúngaro", "Imperio Francés", "Imperio Otomano", "Imperio Ruso"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Quién escribió la Declaración de Independencia de EE.UU.?", opciones: ["Benjamin Franklin", "Thomas Jefferson", "George Washington", "John Adams"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿En qué año se consumó la independencia de México?", opciones: ["1810", "1821", "1836", "1846"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Historia", pregunta: "¿Cuál es la única Maravilla del Mundo Antiguo que sigue en pie?", opciones: ["Coloso de Rodas", "Gran Pirámide de Guiza", "Jardines Colgantes de Babilonia", "Faro de Alejandría"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Qué revolución comenzó en Francia en 1789?", opciones: ["Revolución Industrial", "Revolución Francesa", "Revolución Rusa", "Revolución Americana"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Quién fue Cleopatra?", opciones: ["Reina de Persia", "Reina de Egipto", "Reina de Grecia", "Reina de Roma"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué país atacó Pearl Harbor en 1941?", opciones: ["Alemania", "Italia", "Japón", "Rusia"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Quién lideró el movimiento de independencia de la India?", opciones: ["Nelson Mandela", "Mahatma Gandhi", "Martin Luther King", "Simón Bolívar"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué explorador organizó la primera expedición en dar la vuelta al mundo?", opciones: ["Cristóbal Colón", "Fernando de Magallanes", "Marco Polo", "James Cook"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿En qué siglo cayó el Imperio Romano de Occidente?", opciones: ["Siglo III", "Siglo V", "Siglo VII", "Siglo X"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Quién fue Simón Bolívar?", opciones: ["Un pintor", "Un libertador de América", "Un rey de España", "Un científico"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Quién fue el primer emperador de Roma?", opciones: ["Julio César", "Augusto", "Nerón", "Constantino"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Historia", pregunta: "¿En qué año se hundió el Titanic?", opciones: ["1905", "1912", "1918", "1923"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué civilización precolombina desarrolló un calendario muy preciso?", opciones: ["Incas", "Aztecas", "Mayas", "Toltecas"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Quién fue Juana de Arco?", opciones: ["Una reina de Inglaterra", "Una heroína francesa", "Una emperatriz romana", "Una científica"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿En qué año comenzó la Revolución Rusa?", opciones: ["1905", "1917", "1922", "1930"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Qué antigua civilización creó la escritura cuneiforme?", opciones: ["Egipcios", "Sumerios", "Fenicios", "Griegos"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Historia", pregunta: "¿Quién fue el primer explorador en llegar al Polo Sur?", opciones: ["Robert Scott", "Roald Amundsen", "Ernest Shackleton", "Edmund Hillary"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Historia", pregunta: "¿En qué año se disolvió la Unión Soviética?", opciones: ["1989", "1991", "1993", "1995"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Qué tratado puso fin a la Primera Guerra Mundial?", opciones: ["Tratado de Versalles", "Tratado de Utrecht", "Tratado de Tordesillas", "Tratado de Roma"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Historia", pregunta: "¿Qué faraón es famoso por su máscara funeraria de oro?", opciones: ["Ramsés II", "Tutankamón", "Akenatón", "Keops"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Historia", pregunta: "¿Qué conquistador español venció al Imperio Inca?", opciones: ["Hernán Cortés", "Francisco Pizarro", "Juan Ponce de León", "Vasco Núñez de Balboa"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },

  // Cultura
  { categoria: "Cultura", pregunta: "¿Quién pintó el techo de la Capilla Sixtina?", opciones: ["Leonardo da Vinci", "Miguel Ángel", "Rafael", "Donatello"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Quién escribió \"Don Quijote de la Mancha\"?", opciones: ["Lope de Vega", "Miguel de Cervantes", "Federico García Lorca", "Pablo Neruda"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué pintor es famoso por \"La noche estrellada\"?", opciones: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué banda británica cantó \"Yesterday\"?", opciones: ["The Rolling Stones", "The Beatles", "Queen", "Pink Floyd"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Quién compuso la \"Novena Sinfonía\"?", opciones: ["Mozart", "Bach", "Beethoven", "Chopin"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué escritor colombiano ganó el Premio Nobel de Literatura?", opciones: ["Mario Vargas Llosa", "Gabriel García Márquez", "Pablo Neruda", "Octavio Paz"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué museo alberga la Mona Lisa?", opciones: ["El Prado", "El Louvre", "El MoMA", "El Hermitage"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué instrumento es característico del tango argentino?", opciones: ["Guitarra", "Bandoneón", "Violín", "Arpa"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Quién pintó \"Guernica\"?", opciones: ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Diego Rivera"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué escritora creó al detective Hercule Poirot?", opciones: ["Arthur Conan Doyle", "Agatha Christie", "Raymond Chandler", "Edgar Allan Poe"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué país es la cuna del flamenco?", opciones: ["México", "España", "Cuba", "Argentina"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué pintora mexicana es famosa por sus autorretratos?", opciones: ["Diego Rivera", "Frida Kahlo", "David Alfaro Siqueiros", "Rufino Tamayo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué idioma tiene más hablantes nativos en el mundo?", opciones: ["Inglés", "Español", "Mandarín", "Hindi"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué danza típica de Brasil se originó en el Carnaval?", opciones: ["Salsa", "Samba", "Tango", "Merengue"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué compositor es famoso por \"Las cuatro estaciones\"?", opciones: ["Bach", "Vivaldi", "Mozart", "Handel"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué escultura griega representa a una mujer sin brazos?", opciones: ["El Pensador", "Venus de Milo", "David", "La Piedad"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Cuál es el festival de cine más antiguo de Europa?", opciones: ["Festival de Cannes", "Festival de Venecia", "Festival de Berlín", "Festival de Sundance"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Cultura", pregunta: "¿Qué saga de libros escribió J.K. Rowling?", opciones: ["El Señor de los Anillos", "Harry Potter", "Crónicas de Narnia", "Percy Jackson"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué museo de Madrid alberga \"Las Meninas\"?", opciones: ["El Louvre", "El Prado", "El Hermitage", "El MoMA"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Quién esculpió \"El Pensador\"?", opciones: ["Auguste Rodin", "Miguel Ángel", "Donatello", "Bernini"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué instrumento musical tiene cuerdas y se toca con arco?", opciones: ["Guitarra", "Violín", "Piano", "Flauta"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué escritor argentino escribió \"Ficciones\"?", opciones: ["Julio Cortázar", "Jorge Luis Borges", "Ernesto Sabato", "Adolfo Bioy Casares"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué país celebra el Día de los Muertos como tradición cultural principal?", opciones: ["España", "México", "Perú", "Colombia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Cultura", pregunta: "¿Qué pintor renacentista pintó \"El nacimiento de Venus\"?", opciones: ["Botticelli", "Rafael", "Tiziano", "Miguel Ángel"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Cultura", pregunta: "¿Qué género musical nació en Nueva Orleans a principios del siglo XX?", opciones: ["Rock", "Jazz", "Blues", "Reggae"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Cultura", pregunta: "¿Qué obra narra las aventuras de un caballero y su escudero Sancho Panza?", opciones: ["La Ilíada", "Don Quijote de la Mancha", "Los Miserables", "La Odisea"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },

  // Gastronomía
  { categoria: "Gastronomía", pregunta: "¿Qué país es famoso por el sushi?", opciones: ["China", "Japón", "Corea", "Tailandia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Cuál es el ingrediente principal de un ceviche?", opciones: ["Carne", "Pescado crudo marinado", "Pollo", "Cerdo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es uno de los mayores productores de vino del mundo?", opciones: ["Francia", "Italia", "España", "Estados Unidos"], correctaIndex: 1, fuente: "OIV", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué especia se obtiene de una flor y es la más cara del mundo?", opciones: ["Canela", "Azafrán", "Pimienta", "Cúrcuma"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué bebida se obtiene de la fermentación de la uva?", opciones: ["Cerveza", "Vino", "Sidra", "Whisky"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es famoso por la paella?", opciones: ["Italia", "España", "Portugal", "Grecia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué fruta es la principal para hacer guacamole?", opciones: ["Aguacate", "Tomate", "Mango", "Papaya"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Con qué tipo de leche se hace tradicionalmente la mozzarella original?", opciones: ["Vaca", "Cabra", "Búfala", "Oveja"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es reconocido mundialmente por el curry?", opciones: ["China", "India", "Tailandia", "Japón"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué grano es la base de la cerveza?", opciones: ["Trigo", "Cebada", "Maíz", "Arroz"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿En qué país se originó el kimchi?", opciones: ["China", "Japón", "Corea", "Vietnam"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué fruta tropical es conocida como \"la reina de las frutas\" en el sudeste asiático?", opciones: ["Mango", "Durián", "Piña", "Papaya"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Gastronomía", pregunta: "¿De qué planta se extrae el tequila?", opciones: ["Agave/Maguey", "Caña de azúcar", "Maíz", "Cactus"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es uno de los mayores productores mundiales de aceite de oliva?", opciones: ["Italia", "Grecia", "España", "Turquía"], correctaIndex: 2, fuente: "FAO", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué carne se usa tradicionalmente en un asado argentino?", opciones: ["Cerdo", "Res", "Pollo", "Cordero"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es famoso por el kebab?", opciones: ["Grecia", "Turquía", "Líbano", "Egipto"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué condimento picante de la comida mexicana proviene de un fruto?", opciones: ["Chile", "Pimienta negra", "Jengibre", "Mostaza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es conocido por el fondue de queso?", opciones: ["Francia", "Suiza", "Bélgica", "Austria"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué cereal es la base de la dieta en gran parte de Asia?", opciones: ["Trigo", "Maíz", "Arroz", "Avena"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué bebida andina se prepara tradicionalmente con hojas de coca?", opciones: ["Mate de coca", "Chicha", "Pisco", "Aguardiente"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué país europeo es conocido como capital del chocolate?", opciones: ["Suiza", "Bélgica", "Francia", "Alemania"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué fruta cítrica da nombre a una conocida mermelada británica?", opciones: ["Limón", "Naranja amarga", "Toronja", "Mandarina"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Gastronomía", pregunta: "¿Qué región española es famosa por su vino tinto de Rioja?", opciones: ["Francia", "España", "Italia", "Portugal"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué tubérculo es la base de la papa frita?", opciones: ["Yuca", "Papa", "Camote", "Ñame"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿En qué país se originaron los fideos, según muchos historiadores?", opciones: ["Italia", "China", "Japón", "Corea"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué fruta se usa para preparar el vino de Oporto?", opciones: ["Manzana", "Uva", "Ciruela", "Pera"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país es famoso por el goulash?", opciones: ["Polonia", "Hungría", "Rumania", "República Checa"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Gastronomía", pregunta: "¿Qué bebida caliente se prepara con hojas de la planta Camellia sinensis?", opciones: ["Café", "Té", "Chocolate caliente", "Mate"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Gastronomía", pregunta: "¿Qué país nórdico es de los mayores consumidores de café per cápita del mundo?", opciones: ["Brasil", "Colombia", "Finlandia", "Italia"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },

  // Naturaleza
  { categoria: "Naturaleza", pregunta: "¿Cuál es el ave más rápida del mundo en vuelo en picada?", opciones: ["Águila", "Halcón peregrino", "Colibrí", "Vencejo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Cuántas patas tiene una araña?", opciones: ["6", "8", "10", "12"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal es conocido por cambiar de color para camuflarse?", opciones: ["Iguana", "Camaleón", "Salamandra", "Gecko"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el ave no voladora más grande del mundo?", opciones: ["Pingüino", "Avestruz", "Emú", "Kiwi"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal duerme entre las mayores cantidades de horas al día?", opciones: ["Perezoso", "Koala", "León", "Gato"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el reptil más grande del mundo?", opciones: ["Cocodrilo marino", "Anaconda", "Dragón de Komodo", "Tortuga laúd"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Naturaleza", pregunta: "¿Qué proceso permite a las plantas producir su propio alimento?", opciones: ["Respiración", "Fotosíntesis", "Fermentación", "Digestión"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Qué continente tiene la mayor biodiversidad de especies?", opciones: ["África", "Asia", "América del Sur", "Oceanía"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal es símbolo de China y está en peligro de extinción?", opciones: ["Tigre", "Panda gigante", "Elefante", "Rinoceronte"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuántos años puede vivir una tortuga gigante en promedio?", opciones: ["20-30 años", "50-70 años", "100-150 años", "más de 500 años"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Qué insecto poliniza la mayoría de las flores del mundo?", opciones: ["Mosca", "Abeja", "Hormiga", "Escarabajo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el pez más grande del mundo?", opciones: ["Tiburón blanco", "Tiburón ballena", "Orca", "Pez espada"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal tiene el cuello más largo del mundo?", opciones: ["Camello", "Jirafa", "Avestruz", "Flamenco"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el único mamífero capaz de volar de forma activa?", opciones: ["Ardilla voladora", "Murciélago", "Colibrí", "Petrel"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Qué selva tropical es conocida como \"el pulmón del planeta\"?", opciones: ["Bosque Negro", "Selva Amazónica", "Selva del Congo", "Bosque Boreal"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuántos corazones tiene aproximadamente una lombriz de tierra?", opciones: ["1", "3", "5", "10"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal marino es en realidad un mamífero?", opciones: ["Tiburón", "Delfín", "Medusa", "Pulpo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es la serpiente más larga del mundo?", opciones: ["Cobra real", "Anaconda verde", "Pitón reticulada", "Mamba negra"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "dificil" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal africano vive en manadas y es conocido por sus rayas únicas?", opciones: ["Cebra", "Antílope", "Búfalo", "Jirafa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Qué órgano bombea la sangre en el cuerpo humano?", opciones: ["Pulmón", "Corazón", "Hígado", "Riñón"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal marino puede regenerar sus brazos si los pierde?", opciones: ["Rana", "Estrella de mar", "Iguana", "Tortuga"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el continente más frío del planeta?", opciones: ["Ártico", "Antártida", "Siberia", "Groenlandia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Qué gas es esencial para la respiración humana?", opciones: ["Dióxido de carbono", "Oxígeno", "Nitrógeno", "Hidrógeno"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el felino más grande del mundo?", opciones: ["León", "Tigre", "Jaguar", "Leopardo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Qué animal es capaz de hibernar durante el invierno?", opciones: ["Zorro", "Oso", "Lobo", "Ciervo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es la capa externa de la Tierra donde vivimos?", opciones: ["Núcleo", "Manto", "Corteza", "Atmósfera"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Naturaleza", pregunta: "¿Qué ave es conocida por imitar sonidos y palabras humanas?", opciones: ["Águila", "Loro", "Búho", "Cuervo"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Naturaleza", pregunta: "¿Cuál es el mayor arrecife de coral del mundo?", opciones: ["Arrecife Mesoamericano", "Gran Barrera de Coral", "Arrecife de Belice", "Triángulo de Coral"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },

  // Deportes
  { categoria: "Deportes", pregunta: "¿Cuántos anillos tiene la bandera olímpica?", opciones: ["4", "5", "6", "7"], correctaIndex: 1, fuente: "COI", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿En qué deporte se usa un volante o \"birdie\"?", opciones: ["Tenis", "Bádminton", "Squash", "Ping pong"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Cuántos jugadores de baloncesto están en la cancha por equipo?", opciones: ["5", "6", "7", "9"], correctaIndex: 0, fuente: "FIBA", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿En qué país se originó el judo?", opciones: ["China", "Japón", "Corea", "Tailandia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos puntos vale un touchdown en fútbol americano?", opciones: ["3", "5", "6", "7"], correctaIndex: 2, fuente: "NFL", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Qué deporte se juega en el torneo de Wimbledon?", opciones: ["Golf", "Tenis", "Críquet", "Rugby"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos jugadores de vóleibol están en la cancha por equipo?", opciones: ["5", "6", "7", "8"], correctaIndex: 1, fuente: "FIVB", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos?", opciones: ["Londres", "Atenas", "París", "Roma"], correctaIndex: 1, fuente: "COI", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Qué país ha ganado más Copas del Mundo de fútbol?", opciones: ["Alemania", "Argentina", "Brasil", "Italia"], correctaIndex: 2, fuente: "FIFA", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos hoyos tiene un campo de golf estándar?", opciones: ["9", "12", "18", "24"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿En qué deporte se compite por la Copa Davis?", opciones: ["Golf", "Tenis", "Fútbol", "Rugby"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Cuántos sets se necesitan para ganar un partido de tenis masculino a 5 sets?", opciones: ["2", "3", "4", "5"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Qué deporte practica Michael Phelps, el atleta más laureado en Juegos Olímpicos?", opciones: ["Atletismo", "Natación", "Ciclismo", "Gimnasia"], correctaIndex: 1, fuente: "COI", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos jugadores de béisbol hay en el campo por equipo?", opciones: ["8", "9", "10", "11"], correctaIndex: 1, fuente: "MLB", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿En qué país nació el fútbol moderno con reglas escritas?", opciones: ["Brasil", "Inglaterra", "España", "Argentina"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Qué distancia tiene una maratón olímpica?", opciones: ["21 km", "30 km", "42.195 km", "50 km"], correctaIndex: 2, fuente: "COI", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Cuántos jugadores tiene un equipo de rugby union en el campo?", opciones: ["11", "13", "15", "17"], correctaIndex: 2, fuente: "World Rugby", dificultad: "dificil" },
  { categoria: "Deportes", pregunta: "¿Qué país organizó el Mundial de fútbol de 2014?", opciones: ["Sudáfrica", "Brasil", "Rusia", "Catar"], correctaIndex: 1, fuente: "FIFA", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿En qué juego de mesa se usa el término \"jaque mate\"?", opciones: ["Damas", "Ajedrez", "Backgammon", "Go"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos asaltos tiene como máximo un combate de boxeo profesional estándar?", opciones: ["8", "10", "12", "15"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Qué país ha ganado más medallas de oro olímpicas en la historia?", opciones: ["Rusia", "China", "Estados Unidos", "Reino Unido"], correctaIndex: 2, fuente: "COI", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿En qué deporte compite un jinete?", opciones: ["Ciclismo", "Equitación", "Motociclismo", "Esquí"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos jugadores de fútbol sala (futsal) hay en la cancha por equipo?", opciones: ["4", "5", "6", "7"], correctaIndex: 1, fuente: "FIFA", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿En qué país se originó el rugby?", opciones: ["Francia", "Inglaterra", "Gales", "Escocia"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿En qué superficie se juega el torneo Roland Garros?", opciones: ["Césped", "Arcilla (tierra batida)", "Cemento duro", "Alfombra"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
  { categoria: "Deportes", pregunta: "¿Cuántos jugadores de hockey sobre hielo están en la pista por equipo?", opciones: ["5", "6", "7", "8"], correctaIndex: 1, fuente: "IIHF", dificultad: "dificil" },
  { categoria: "Deportes", pregunta: "¿Qué deporte usa el término \"Tour de Francia\"?", opciones: ["Atletismo", "Ciclismo", "Automovilismo", "Natación"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Cuántos árbitros principales dirigen un partido de fútbol dentro del campo?", opciones: ["1", "2", "3", "4"], correctaIndex: 0, fuente: "FIFA", dificultad: "facil" },
  { categoria: "Deportes", pregunta: "¿Qué país ganó el primer Mundial de fútbol en 1930?", opciones: ["Brasil", "Argentina", "Uruguay", "Italia"], correctaIndex: 2, fuente: "FIFA", dificultad: "dificil" },
];

/** Selecciona `cantidad` preguntas al azar (sin repetir) con sus opciones barajadas. */
export function preguntasCulturaGeneral(cantidad = RETO_CULTURA_GENERAL_CONFIG.cantidad): PreguntaTrivia[] {
  return shuffle(BANCO_CULTURA_GENERAL).slice(0, Math.min(cantidad, BANCO_CULTURA_GENERAL.length)).map(shuffleOpciones);
}

/** Igual que `preguntasCulturaGeneral()`, pero también devuelve los ÍNDICES
 * usados dentro de `BANCO_CULTURA_GENERAL` — para un reto 1 a 1, guardamos
 * esos índices y así el retado responde EXACTAMENTE las mismas preguntas
 * (el orden de las opciones sí se vuelve a barajar por jugador, eso no afecta
 * la justicia del puntaje). */
export function preguntasCulturaGeneralConIndices(
  cantidad = RETO_CULTURA_GENERAL_CONFIG.cantidad
): { preguntas: PreguntaTrivia[]; indices: number[] } {
  const indicesBarajados = shuffle(BANCO_CULTURA_GENERAL.map((_, i) => i)).slice(
    0,
    Math.min(cantidad, BANCO_CULTURA_GENERAL.length)
  );
  return {
    preguntas: indicesBarajados.map((i) => shuffleOpciones(BANCO_CULTURA_GENERAL[i])),
    indices: indicesBarajados,
  };
}

/** Reconstruye el MISMO set de preguntas de un reto 1 a 1 ya creado, a partir
 * de los índices guardados — para que el retado juegue exactamente lo mismo. */
export function preguntasPorIndices(indices: number[]): PreguntaTrivia[] {
  return indices.map((i) => shuffleOpciones(BANCO_CULTURA_GENERAL[i]));
}
