import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

// Banco semilla real de Colombia (único país gratis) — el pipeline de generación con
// verificación automática (ver ESTADO.md) llega en la Sesión 6. Preguntas verificadas
// manualmente. Cada ronda (Explorador/Descubridor/Experto) tiene su PROPIO set de
// preguntas, sin solapamiento: así ningún nivel repite lo que ya preguntó otro nivel
// de la misma categoría (corrección pedida por el usuario, 2026-08-23).
export const BANCO_COLOMBIA: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Colombia?", opciones: ["Medellín", "Bogotá", "Cali", "Cartagena"], correctaIndex: 1, fuente: "REST Countries API", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Colombia por el occidente?", opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctaIndex: 2, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué mar bordea la costa norte de Colombia?", opciones: ["Mar Caribe", "Mar Rojo", "Mar Mediterráneo", "Mar Negro"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué continente está ubicada Colombia?", opciones: ["América del Sur", "América Central", "Norteamérica", "Europa"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el idioma oficial de Colombia?", opciones: ["Portugués", "Español", "Inglés", "Francés"], correctaIndex: 1, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Cuál es el río más largo de Colombia?", opciones: ["Río Cauca", "Río Magdalena", "Río Orinoco", "Río Atrato"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera atraviesa gran parte de Colombia?", opciones: ["Los Andes", "Las Rocosas", "Los Alpes", "El Himalaya"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad colombiana es conocida como \"la Sucursal del Cielo\"?", opciones: ["Cali", "Medellín", "Bucaramanga", "Pereira"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Con cuántos países limita Colombia?", opciones: ["3", "4", "5", "7"], correctaIndex: 2, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿En qué altiplano está ubicada Bogotá?", opciones: ["Sabana de Bogotá", "Altiplano de Nariño", "Valle del Cauca", "Meseta de Popayán"], correctaIndex: 0, fuente: "IGAC", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la segunda ciudad más poblada de Colombia?", opciones: ["Medellín", "Cali", "Barranquilla", "Cartagena"], correctaIndex: 0, fuente: "DANE", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué archipiélago colombiano está en el mar Caribe, cerca de Nicaragua?", opciones: ["San Andrés y Providencia", "Islas del Rosario", "Islas de San Bernardo", "Malpelo"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuántas regiones naturales tiene Colombia?", opciones: ["4", "5", "6", "8"], correctaIndex: 2, fuente: "IGAC", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el departamento más grande de Colombia por área?", opciones: ["Vichada", "Amazonas", "Meta", "Chocó"], correctaIndex: 1, fuente: "DANE", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Colombia?", opciones: ["Nevado del Ruiz", "Pico Cristóbal Colón", "Volcán Galeras", "Cerro de Monserrate"], correctaIndex: 1, fuente: "IGAC", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Por qué departamento colombiano pasa la línea del Ecuador?", opciones: ["Amazonas", "Nariño", "Putumayo", "Vaupés"], correctaIndex: 0, fuente: "IGAC", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es el lago natural más grande de Colombia, ubicado en Boyacá?", opciones: ["Lago de Tota", "Laguna de Guatavita", "Ciénaga Grande", "Laguna del Otún"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuántos departamentos tiene Colombia?", opciones: ["30", "32", "33", "35"], correctaIndex: 1, fuente: "DANE", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué departamento colombiano tiene costas tanto en el Pacífico como en el Caribe?", opciones: ["Chocó", "Nariño", "Bolívar", "Valle del Cauca"], correctaIndex: 0, fuente: "IGAC", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es la isla colombiana más alejada del continente, en pleno océano Pacífico?", opciones: ["Malpelo", "Gorgona", "San Andrés", "Providencia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es el pico gemelo de Cristóbal Colón en la Sierra Nevada de Santa Marta, de altura casi idéntica?", opciones: ["Pico Simón Bolívar", "Pico Cumbal", "Volcán Galeras", "Nevado del Tolima"], correctaIndex: 0, fuente: "IGAC", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué golfo separa a Colombia de Panamá en el mar Caribe?", opciones: ["Golfo de Urabá", "Golfo de Morrosquillo", "Golfo de Tribugá", "Golfo de Guayaquil"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿En qué año se dio el Grito de Independencia de Colombia?", opciones: ["1810", "1776", "1821", "1900"], correctaIndex: 0, fuente: "Wikipedia — Historia de Colombia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Quién es considerado el libertador de Colombia?", opciones: ["José de San Martín", "Simón Bolívar", "Antonio Nariño", "Francisco de Paula Santander"], correctaIndex: 1, fuente: "Wikipedia — Simón Bolívar", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año llegó Cristóbal Colón por primera vez a América?", opciones: ["1492", "1500", "1519", "1521"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué explorador español avistó por primera vez las costas colombianas en 1499?", opciones: ["Alonso de Ojeda", "Hernán Cortés", "Francisco Pizarro", "Vasco Núñez de Balboa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué pueblo indígena, con la leyenda de El Dorado, habitó la zona de Bogotá antes de la conquista?", opciones: ["Muisca", "Inca", "Maya", "Azteca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿En qué año se separó Panamá de Colombia?", opciones: ["1886", "1903", "1930", "1948"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Cómo se llamó la unión de países que incluyó a Colombia tras la independencia?", opciones: ["Gran Colombia", "Confederación Andina", "Unión Bolivariana", "República del Sur"], correctaIndex: 0, fuente: "Wikipedia — Gran Colombia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Quién fue el primer presidente de la Gran Colombia?", opciones: ["Francisco de Paula Santander", "Simón Bolívar", "Antonio Nariño", "José María Córdova"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué laguna se realizaba el ritual muisca que dio origen a la leyenda de El Dorado?", opciones: ["Laguna de Guatavita", "Lago de Tota", "Ciénaga Grande", "Laguna del Otún"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Quién fundó la ciudad de Bogotá en 1538?", opciones: ["Gonzalo Jiménez de Quesada", "Sebastián de Belalcázar", "Pedro de Heredia", "Rodrigo de Bastidas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué ciudad colombiana fundó Sebastián de Belalcázar en 1536?", opciones: ["Santiago de Cali", "Cartagena", "Bucaramanga", "Tunja"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año se firmó la actual Constitución Política de Colombia?", opciones: ["1986", "1991", "1998", "2001"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿En qué batalla de 1819 se selló la independencia de Colombia?", opciones: ["Batalla de Boyacá", "Batalla de Ayacucho", "Batalla de Carabobo", "Batalla de Pichincha"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué acuerdo de paz se firmó en Colombia en 2016?", opciones: ["Acuerdo con las FARC", "Acuerdo con el M-19", "Tratado de Boyacá", "Concordato"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Cómo se llamó el período de violencia bipartidista de mediados del siglo XX en Colombia?", opciones: ["La Violencia", "El Bogotazo", "La Reconquista", "El Frente Nacional"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué evento de 1948 desató el llamado \"Bogotazo\"?", opciones: ["Un terremoto", "El asesinato de Jorge Eliécer Gaitán", "Una huelga general", "Un golpe militar"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué explorador español fundó Santa Marta en 1525?", opciones: ["Rodrigo de Bastidas", "Gonzalo Jiménez de Quesada", "Sebastián de Belalcázar", "Pedro de Heredia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Cómo se llamó la zona desmilitarizada usada en las negociaciones de paz con las FARC entre 1998 y 2002?", opciones: ["Zona de distensión del Caguán", "Acuerdo de Ralito", "Proceso 8000", "Pacto de Chicoral"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué grupo guerrillero se desmovilizó en 1990 tras firmar la paz con el gobierno colombiano?", opciones: ["M-19", "ELN", "EPL", "AUC"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿En qué década se creó el Frente Nacional, pacto de alternancia entre liberales y conservadores?", opciones: ["1930s", "1950s", "1970s", "1990s"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué presidente colombiano lideró la fallida negociación de paz del Caguán con las FARC?", opciones: ["Andrés Pastrana", "Álvaro Uribe", "César Gaviria", "Ernesto Samper"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿En qué ciudad colombiana se realizó la ceremonia de firma del acuerdo de paz con las FARC en 2016?", opciones: ["Cartagena", "Bogotá", "Medellín", "Cali"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué escritor colombiano ganó el Premio Nobel de Literatura?", opciones: ["Mario Vargas Llosa", "Gabriel García Márquez", "Pablo Neruda", "Octavio Paz"], correctaIndex: 1, fuente: "NobelPrize.org", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cuál es la novela más famosa de Gabriel García Márquez?", opciones: ["Cien años de soledad", "La casa de los espíritus", "Rayuela", "Pedro Páramo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué cantante colombiana es famosa mundialmente por canciones como \"Hips Don't Lie\"?", opciones: ["Shakira", "Karol G", "Fanny Lu", "Andrea Echeverri"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué cantante colombiana es conocida por éxitos como \"Tusa\" y \"Provenza\"?", opciones: ["Karol G", "Shakira", "Fanny Lu", "Goyo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué cantante colombiano, autor de \"La Bicicleta\", mezcla vallenato con pop?", opciones: ["Carlos Vives", "Juanes", "J Balvin", "Maluma"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿Qué género musical es originario de la costa Caribe colombiana?", opciones: ["Tango", "Cumbia", "Samba", "Merengue"], correctaIndex: 1, fuente: "Wikipedia — Cumbia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué pintor colombiano es famoso por sus figuras voluminosas?", opciones: ["Fernando Botero", "Alejandro Obregón", "Enrique Grau", "Débora Arango"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué carnaval colombiano es Patrimonio Cultural Inmaterial de la Humanidad?", opciones: ["Carnaval de Barranquilla", "Carnaval de Río", "Carnaval de Oruro", "Carnaval de Venecia"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué artista colombiano de música urbana es conocido por \"Mi Gente\" y \"Ginza\"?", opciones: ["J Balvin", "Maluma", "Feid", "Ryan Castro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor colombiano escribió \"El amor en los tiempos del cólera\"?", opciones: ["Gabriel García Márquez", "Jorge Isaacs", "José Eustasio Rivera", "Álvaro Mutis"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué pintora colombiana es reconocida por retratar con crudeza \"La Violencia\" bipartidista en sus cuadros?", opciones: ["Débora Arango", "Beatriz González", "Ana Mercedes Hoyos", "Doris Salcedo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor colombiano escribió la novela \"La vorágine\", ambientada en la selva?", opciones: ["José Eustasio Rivera", "Jorge Isaacs", "Álvaro Mutis", "Tomás Carrasquilla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué sombrero típico colombiano se teje con fibra de caña flecha?", opciones: ["Sombrero vueltiao", "Sombrero de paja toquilla", "Sombrero cordobés", "Sombrero charro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿En qué ciudad se celebra el Festival de la Leyenda Vallenata?", opciones: ["Valledupar", "Santa Marta", "Riohacha", "Barranquilla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento de viento es típico de la música andina colombiana?", opciones: ["Gaita", "Didgeridoo", "Shofar", "Fagot"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cuál es el baile típico de la región Pacífica colombiana?", opciones: ["Currulao", "Joropo", "Bambuco", "Mapalé"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento de percusión, hecho de madera ahuecada, es típico de la música del Pacífico colombiano?", opciones: ["Marimba de chonta", "Tambora", "Cununo", "Guacharaca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escritora colombiana ganó el Premio Alfaguara con su novela \"Delirio\"?", opciones: ["Laura Restrepo", "Piedad Bonnett", "Ingrid Betancourt", "Melba Escobar"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué ciudad colombiana es reconocida como la \"Capital Musical de Colombia\"?", opciones: ["Ibagué", "Neiva", "Villavicencio", "Manizales"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escultora colombiana es reconocida internacionalmente por instalaciones sobre la memoria del conflicto armado?", opciones: ["Doris Salcedo", "Débora Arango", "Beatriz González", "Feliza Bursztyn"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué ritmo musical de la región Andina colombiana interpretaba el compositor Jorge Villamil?", opciones: ["Bambuco", "Vallenato", "Champeta", "Porro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cuál es el baile insignia del departamento del Huila, celebrado en el Festival del Bambuco?", opciones: ["Sanjuanero huilense", "Currulao", "Mapalé", "Joropo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Cuál es el plato típico colombiano con maíz, carne, chicharrón y aguacate?", opciones: ["Bandeja Paisa", "Feijoada", "Pabellón Criollo", "Asado Argentino"], correctaIndex: 0, fuente: "Wikipedia — Bandeja paisa", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es el principal producto agrícola de exportación de Colombia?", opciones: ["Cacao", "Café", "Trigo", "Arroz"], correctaIndex: 1, fuente: "Banco de la República", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida caliente colombiana se prepara con panela y agua?", opciones: ["Agua de panela", "Chicha", "Masato", "Guarapo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta tropical colombiana, ácida y jugosa, es una de las más consumidas en jugos del país?", opciones: ["Lulo", "Manzana", "Pera", "Durazno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es el ingrediente principal de la arepa colombiana?", opciones: ["Maíz", "Trigo", "Arroz", "Yuca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Qué sopa bogotana lleva pollo, papa criolla y guascas?", opciones: ["Sancocho", "Ajiaco", "Mondongo", "Cazuela"], correctaIndex: 1, fuente: "Wikipedia — Ajiaco", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida alcohólica típica colombiana se destila de la caña de azúcar?", opciones: ["Aguardiente", "Pisco", "Ron añejo", "Tequila"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué dulce colombiano se hace hirviendo leche con azúcar hasta espesar?", opciones: ["Arequipe", "Flan", "Cajeta", "Manjar blanco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida fermentada de maíz es tradicional entre comunidades indígenas colombianas?", opciones: ["Chicha", "Sake", "Kombucha", "Pulque"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué queso colombiano, típico de la Costa Caribe, acompaña el chocolate caliente?", opciones: ["Queso costeño", "Queso parmesano", "Queso manchego", "Queso gouda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué carne se usa tradicionalmente en la Lechona tolimense?", opciones: ["Cerdo", "Res", "Pollo", "Cordero"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué pan de queso, hecho con almidón de yuca, es típico del Valle del Cauca?", opciones: ["Pandebono", "Buñuelo", "Achira", "Almojábana"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Qué sopa costeña se prepara con varias carnes, plátano y yuca?", opciones: ["Sancocho", "Ajiaco", "Changua", "Mote de queso"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la arepa rellena típica de Boyacá con queso?", opciones: ["Arepa boyacense", "Arepa de choclo", "Arepa santandereana", "Arepa paisa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta colombiana, pequeña y anaranjada, es muy valorada por su vitamina C?", opciones: ["Uchuva", "Lulo", "Curuba", "Guanábana"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Con qué se acompaña tradicionalmente el arroz con coco de la costa Caribe?", opciones: ["Pescado frito", "Chicharrón", "Carne asada", "Pollo al horno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿De qué región colombiana es típica la sopa \"mote de queso\", hecha con ñame?", opciones: ["Región Caribe", "Región Andina", "Región Pacífica", "Región Orinoquía"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el plato de carne de res asada a las brasas, típico de los Llanos Orientales?", opciones: ["Mamona", "Bandeja Paisa", "Sancocho", "Asado huilense"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿En qué hoja se envuelve tradicionalmente el \"viudo de pescado\" huilense para cocinarlo?", opciones: ["Hoja de plátano", "Hoja de bijao", "Hoja de maíz", "Papel aluminio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta se usa para el postre \"brevas con arequipe\", típico de Santander?", opciones: ["Breva", "Guayaba", "Mango", "Papaya"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué insecto es un snack tradicional y muy popular en Santander?", opciones: ["Hormiga culona", "Grillo", "Chapulín", "Escarabajo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el dulce de guayaba en bloque, clásico para acompañar con queso?", opciones: ["Bocadillo", "Arequipe", "Cocada", "Panelitas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Cuál es el parque natural más visitado de la costa Caribe colombiana?", opciones: ["Parque Tayrona", "Parque Amacayacu", "Parque Chicaque", "Parque Los Nevados"], correctaIndex: 0, fuente: "Parques Nacionales Naturales de Colombia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave es el símbolo nacional de Colombia?", opciones: ["Guacamaya", "Cóndor de los Andes", "Tucán", "Colibrí"], correctaIndex: 1, fuente: "Wikipedia — Símbolos de Colombia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es la flor nacional de Colombia?", opciones: ["Rosa", "Orquídea", "Girasol", "Margarita"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es el mamífero nacional de Colombia, un oso que vive en los Andes?", opciones: ["Oso de anteojos", "Oso panda", "Oso polar", "Oso pardo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque natural colombiano protege el nevado activo más alto del país, cerca de Manizales?", opciones: ["Los Nevados", "Tayrona", "Amacayacu", "Chicaque"], correctaIndex: 0, fuente: "Parques Nacionales Naturales de Colombia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Qué felino, el más grande de América, habita en la selva colombiana?", opciones: ["Jaguar", "Puma", "Ocelote", "Lince"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿En qué cordillera colombiana está el volcán Nevado del Ruiz?", opciones: ["Cordillera Occidental", "Cordillera Central", "Cordillera Oriental", "Sierra Nevada"], correctaIndex: 1, fuente: "Servicio Geológico Colombiano", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ecosistema de alta montaña, propio de los Andes, es clave para el agua de Colombia?", opciones: ["Páramo", "Sabana", "Estepa", "Tundra"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué primate, endémico del norte de Colombia y en peligro crítico, tiene una llamativa cresta de pelo blanco?", opciones: ["Tití cabeciblanco", "Mono aullador", "Mono araña", "Marimonda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué tipo de bosque, típico de las montañas colombianas, está cubierto de niebla y musgo?", opciones: ["Bosque de niebla", "Selva tropical", "Manglar", "Sabana"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ecosistema costero, de raíces sumergidas, protege las costas colombianas de la erosión?", opciones: ["Manglar", "Páramo", "Sabana", "Estepa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es el reptil más grande que habita los ríos y ciénagas de las tierras bajas colombianas?", opciones: ["Caimán aguja", "Babilla", "Iguana", "Tortuga charapa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Qué desierto colombiano en el Huila es famoso por sus formaciones rojizas?", opciones: ["Desierto de la Tatacoa", "Desierto de Atacama", "Desierto del Sahara", "Desierto de Sechura"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué río colombiano es conocido como \"el río de los 5 colores\"?", opciones: ["Caño Cristales", "Río Magdalena", "Río Cauca", "Río Vaupés"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué lugar ocupa Colombia en el mundo por número de especies de aves?", opciones: ["Primer lugar", "Quinto lugar", "Décimo lugar", "No está en el top 10"], correctaIndex: 0, fuente: "Instituto Humboldt", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué selva colombiana forma parte de la cuenca del río más caudaloso del mundo?", opciones: ["Selva Amazónica", "Selva del Darién", "Selva de Niebla", "Selva del Chocó"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿En qué departamento colombiano se encuentra el Santuario de Fauna y Flora Los Flamencos?", opciones: ["La Guajira", "Magdalena", "Atlántico", "Cesar"], correctaIndex: 0, fuente: "Parques Nacionales Naturales de Colombia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional colombiano protege el páramo más grande del mundo?", opciones: ["Sumapaz", "Chingaza", "Los Nevados", "Puracé"], correctaIndex: 0, fuente: "Parques Nacionales Naturales de Colombia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran río amazónico nace en el Macizo Colombiano, junto con el Magdalena y el Cauca?", opciones: ["Río Caquetá", "Río Meta", "Río Guaviare", "Río Vaupés"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué rana, considerada de las más venenosas del mundo, es endémica de la selva del Chocó?", opciones: ["Rana dorada", "Rana toro", "Rana arbórea", "Sapo común"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Colombia es el segundo país del mundo con más especies de qué, después de Brasil?", opciones: ["Plantas", "Reptiles", "Peces de agua salada", "Mamíferos marinos"], correctaIndex: 0, fuente: "Instituto Humboldt", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué cordillera colombiana no tiene actividad volcánica, a diferencia de la Central?", opciones: ["Cordillera Oriental", "Cordillera Central", "Cordillera Occidental", "Sierra Nevada"], correctaIndex: 0, fuente: "Servicio Geológico Colombiano", dificultad: "experto" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte más popular en Colombia?", opciones: ["Fútbol", "Béisbol", "Baloncesto", "Voleibol"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué ciclista colombiano ganó el Tour de Francia en 2019?", opciones: ["Nairo Quintana", "Egan Bernal", "Rigoberto Urán", "Fernando Gaviria"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cómo se le conoce popularmente a la selección de fútbol masculina de Colombia?", opciones: ["La Tricolor", "La Roja", "La Albiceleste", "La Verdeamarela"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué colombiano es considerado el mejor futbolista de la historia del país, ícono de los años 90?", opciones: ["Carlos Valderrama", "René Higuita", "Freddy Rincón", "Faustino Asprilla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte autóctono y nacional de Colombia, que consiste en lanzar un disco a un blanco con pólvora?", opciones: ["Tejo", "Cucunubá", "Rana", "Bolos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Qué ciclista colombiano ganó el Giro de Italia en 2014?", opciones: ["Nairo Quintana", "Egan Bernal", "Miguel Ángel López", "Sergio Henao"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué ciclista colombiano también ganó la Vuelta a España en 2016?", opciones: ["Nairo Quintana", "Egan Bernal", "Rigoberto Urán", "Esteban Chaves"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿En qué deporte de ruedas Colombia gana constantemente medallas mundiales?", opciones: ["Patinaje de carreras", "Hockey sobre hielo", "Ciclismo BMX de pista", "Curling"], correctaIndex: 0, fuente: "Federación Colombiana de Patinaje", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué arquero colombiano, apodado \"El Loco\", era famoso por salir a jugar como líbero?", opciones: ["René Higuita", "Óscar Córdoba", "David Ospina", "Faryd Mondragón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué pareja de tenistas colombianos llegó al puesto número 1 del mundo en dobles?", opciones: ["Cabal y Farah", "Falla y Giraldo", "Galán y Lebrón", "Bryan y Bryan"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué colombiano ganó la medalla de oro en levantamiento de pesas en Río 2016?", opciones: ["Óscar Figueroa", "Jhonatan Rivera", "Manuel Caicedo", "Yeison López"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué atleta colombiana ganó el oro en salto triple en los Juegos Olímpicos de Río 2016?", opciones: ["Caterine Ibargüen", "Yuri Alvear", "Mariana Pajón", "Jackeline Rentería"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿Cómo se llama el estadio de fútbol más importante de Bogotá?", opciones: ["El Campín", "El Monumental", "El Metropolitano", "El Centenario"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Quién fue el boxeador colombiano campeón mundial apodado \"Kid Pambelé\"?", opciones: ["Antonio Cervantes", "Miguel Herrera", "Rodrigo Valdez", "Prudencio Cardona"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué ciclista colombiana ganó oro olímpico en BMX en Londres 2012 y Río 2016?", opciones: ["Mariana Pajón", "Catalina Escobar", "Diana Trujillo", "Yuri Alvear"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad colombiana es famosa por el Alto de Letras, ícono del ciclismo de montaña?", opciones: ["Manizales", "Popayán", "Ibagué", "Neiva"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Quién ganó la primera medalla de oro olímpica en la historia de Colombia, en Sydney 2000?", opciones: ["María Isabel Urrutia", "Mariana Pajón", "Caterine Ibargüen", "Óscar Figueroa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿A qué selección venció Colombia en la final de la Copa América 2001, jugada como local?", opciones: ["México", "Argentina", "Brasil", "Uruguay"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué arquero colombiano fue el mejor arquero (Guante de Oro) de la Copa América 2001?", opciones: ["Óscar Córdoba", "René Higuita", "Faryd Mondragón", "David Ospina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué ciudad colombiana se jugó la final de la Copa América 2001?", opciones: ["Bogotá", "Cali", "Barranquilla", "Medellín"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué patinadora colombiana es una de las más laureadas del mundo en patinaje de carreras?", opciones: ["Cecilia Baena", "Yuri Alvear", "Ana Cabrera", "Pilar Fernández"], correctaIndex: 0, fuente: "Federación Colombiana de Patinaje", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué deporte compite Mariana Pajón, apodada \"la Reina\"?", opciones: ["BMX", "Ciclismo de ruta", "Patinaje", "Atletismo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
};
