import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

// Banco real de Estados Unidos (Ruta 3 — Ecos del Norte). Mismo estándar que el resto de países.
export const BANCO_EEUU: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Estados Unidos?", opciones: ["Nueva York", "Washington D.C.", "Los Ángeles", "Chicago"], correctaIndex: 1, fuente: "REST Countries API", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Estados Unidos por el oeste?", opciones: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Estados Unidos por el este?", opciones: ["Atlántico", "Pacífico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué idioma es el más hablado en Estados Unidos?", opciones: ["Inglés", "Español", "Francés", "Alemán"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué continente está ubicado Estados Unidos?", opciones: ["América del Norte", "América del Sur", "Europa", "Asia"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Con cuántos países limita Estados Unidos por tierra?", opciones: ["2", "1", "3", "4"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la ciudad más poblada de Estados Unidos?", opciones: ["Nueva York", "Los Ángeles", "Chicago", "Houston"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera atraviesa el oeste de Estados Unidos?", opciones: ["Montañas Rocosas", "Los Andes", "Alpes", "Himalaya"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es el estado más grande de Estados Unidos por área?", opciones: ["Alaska", "Texas", "California", "Montana"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la moneda oficial de Estados Unidos?", opciones: ["Dólar estadounidense", "Euro", "Libra", "Peso"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué país limita a Estados Unidos por el norte?", opciones: ["Canadá", "México", "Cuba", "Rusia"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuántos estados componen Estados Unidos?", opciones: ["50", "48", "52", "45"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Estados Unidos?", opciones: ["Denali", "Monte Whitney", "Pico Elbert", "Monte Rainier"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿En qué estado se ubica el Denali (antes Monte McKinley)?", opciones: ["Alaska", "Colorado", "Washington", "California"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué gran cañón, tallado por el río Colorado, es uno de los más famosos del mundo?", opciones: ["Gran Cañón", "Cañón del Sumidero", "Cañón del Colca", "Valle de la Muerte"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué valle, el punto más caluroso de Norteamérica, se ubica entre California y Nevada?", opciones: ["Valle de la Muerte (Death Valley)", "Desierto de Sonora", "Desierto de Mojave", "Desierto de Atacama"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué gran lago, compartido con Canadá, es el más grande de los Grandes Lagos?", opciones: ["Lago Superior", "Lago Michigan", "Lago Hurón", "Lago Erie"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Cuántos son los Grandes Lagos de Norteamérica en total?", opciones: ["5", "3", "4", "7"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué río, uno de los más largos y caudalosos de EE.UU., atraviesa Nueva Orleans?", opciones: ["Misisipi", "Colorado", "Columbia", "Hudson"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué desierto cubre gran parte de Arizona y Nuevo México, célebre por sus cactus saguaro?", opciones: ["Desierto de Sonora", "Desierto de Mojave", "Desierto de Chihuahua", "Desierto de Atacama"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué archipiélago del Pacífico es un estado de EE.UU. desde 1959?", opciones: ["Hawái", "Puerto Rico", "Guam", "Samoa Americana"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera marca la línea divisoria continental que separa el drenaje de los ríos hacia el este y el oeste de EE.UU.?", opciones: ["Montañas Rocosas", "Río Misisipi", "Paralelo 40", "Meridiano de Greenwich"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿De qué país se independizaron las 13 colonias en 1776?", opciones: ["Reino Unido", "Francia", "España", "Países Bajos"], correctaIndex: 0, fuente: "Wikipedia — Historia de EE.UU.", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Quién es considerado el primer presidente de Estados Unidos?", opciones: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "Benjamin Franklin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué documento de 1776 declaró la independencia de EE.UU.?", opciones: ["Declaración de Independencia", "Constitución", "Carta Magna", "Bill of Rights"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué guerra civil (1861-1865) dividió a Estados Unidos entre Norte y Sur?", opciones: ["Guerra Civil Estadounidense", "Guerra de Independencia", "Guerra Hispano-Americana", "Guerra de Vietnam"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué presidente lideró a EE.UU. durante la Guerra Civil y abolió la esclavitud?", opciones: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "Theodore Roosevelt"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿En qué año se firmó la Declaración de Independencia de Estados Unidos?", opciones: ["1776", "1789", "1800", "1865"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué documento, ratificado en 1788, es la ley suprema de Estados Unidos?", opciones: ["Constitución de los Estados Unidos", "Declaración de Independencia", "Carta Magna", "Tratado de París"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año terminó la Guerra Civil estadounidense?", opciones: ["1865", "1861", "1900", "1776"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué compra de territorio en 1803 duplicó el tamaño de Estados Unidos?", opciones: ["Compra de Luisiana", "Compra de Alaska", "Tratado de Guadalupe Hidalgo", "Compra de Florida"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿A qué país compró Estados Unidos el territorio de Alaska en 1867?", opciones: ["Rusia", "Francia", "España", "Reino Unido"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué enmienda constitucional abolió la esclavitud en Estados Unidos en 1865?", opciones: ["Decimotercera Enmienda", "Primera Enmienda", "Decimonovena Enmienda", "Vigésima Enmienda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué movimiento social, liderado por Martin Luther King Jr., luchó por la igualdad racial en los años 50-60?", opciones: ["Movimiento por los Derechos Civiles", "Movimiento Sufragista", "Movimiento Obrero", "Movimiento Abolicionista"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿Qué ataque japonés de 1941 llevó a EE.UU. a entrar en la Segunda Guerra Mundial?", opciones: ["Ataque a Pearl Harbor", "Bombardeo de Hiroshima", "Batalla de Midway", "Invasión de Normandía"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué presidente estadounidense lideró al país durante la mayor parte de la Segunda Guerra Mundial?", opciones: ["Franklin D. Roosevelt", "Harry Truman", "Dwight Eisenhower", "Woodrow Wilson"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué crisis económica de 1929 provocó la Gran Depresión en Estados Unidos?", opciones: ["Crac del 29 (caída de la bolsa de Wall Street)", "Crisis del petróleo", "Burbuja inmobiliaria", "Crisis de 2008"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué programa de reformas económicas del presidente Roosevelt buscó sacar a EE.UU. de la Gran Depresión?", opciones: ["New Deal", "Great Society", "New Frontier", "Fair Deal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué enmienda constitucional otorgó el derecho al voto a las mujeres en EE.UU. en 1920?", opciones: ["Decimonovena Enmienda", "Decimotercera Enmienda", "Vigésimo Sexta Enmienda", "Primera Enmienda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué discurso histórico de 1963 pronunció Martin Luther King Jr. en Washington D.C.?", opciones: ["\"Tengo un sueño\" (I Have a Dream)", "Discurso de Gettysburg", "Discurso inaugural", "Cuatro Libertades"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué presidente pronunció el histórico \"Discurso de Gettysburg\" en 1863?", opciones: ["Abraham Lincoln", "George Washington", "Theodore Roosevelt", "Woodrow Wilson"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué guerra fría enfrentó ideológicamente a EE.UU. con la Unión Soviética durante gran parte del siglo XX?", opciones: ["Guerra Fría", "Guerra de Corea", "Guerra de Vietnam", "Guerra del Golfo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿En qué año llegó el hombre a la Luna en la misión Apolo 11 de EE.UU.?", opciones: ["1969", "1959", "1975", "1980"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué presidente estadounidense renunció a su cargo en 1974 tras el escándalo de Watergate?", opciones: ["Richard Nixon", "Gerald Ford", "Lyndon B. Johnson", "Jimmy Carter"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué género musical, con raíces afroamericanas, nació en Nueva Orleans a principios del siglo XX?", opciones: ["Jazz", "Salsa", "Flamenco", "Tango"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué industria del entretenimiento, con sede en Los Ángeles, produce la mayoría de las películas de Hollywood?", opciones: ["Cine (Hollywood)", "Música clásica", "Teatro", "Ópera"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué deporte con bate y pelota es considerado el \"pasatiempo nacional\" de EE.UU.?", opciones: ["Béisbol", "Fútbol americano", "Baloncesto", "Hockey"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué estatua, regalo de Francia, es símbolo de Nueva York y la inmigración?", opciones: ["Estatua de la Libertad", "Torre Eiffel", "Cristo Redentor", "Big Ben"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué festividad estadounidense de noviembre celebra la cosecha con pavo y familia?", opciones: ["Acción de Gracias (Thanksgiving)", "Halloween", "Navidad", "Independence Day"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿Qué género musical afroamericano, con raíces en el sur, influenció profundamente el rock and roll?", opciones: ["Blues", "Ópera", "Música clásica", "Vals"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué cantante, apodado \"El Rey del Rock and Roll\", revolucionó la música popular en los años 50?", opciones: ["Elvis Presley", "Frank Sinatra", "Bob Dylan", "Chuck Berry"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor estadounidense es autor de \"Las aventuras de Huckleberry Finn\"?", opciones: ["Mark Twain", "Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor estadounidense ganó el Nobel de Literatura y escribió \"El viejo y el mar\"?", opciones: ["Ernest Hemingway", "Mark Twain", "William Faulkner", "John Steinbeck"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué género musical popular estadounidense, con raíces country y folk del sur, incluye artistas como Dolly Parton?", opciones: ["Country", "Jazz", "Blues", "Reggae"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué museo neoyorquino, fundado en 1870, alberga una de las mayores colecciones de arte del mundo?", opciones: ["Museo Metropolitano de Arte (MET)", "MoMA", "Museo Guggenheim", "Instituto de Arte de Chicago"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué evento deportivo, la final de la liga de fútbol americano, es uno de los más vistos del mundo?", opciones: ["Super Bowl", "World Series", "NBA Finals", "Stanley Cup"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué movimiento literario y cultural afroamericano floreció en Nueva York en los años 1920?", opciones: ["Renacimiento de Harlem", "Generación Perdida", "Beat Generation", "Transcendentalismo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué grupo de escritores, incluido Hemingway y Fitzgerald, vivió como expatriados en Europa tras la Primera Guerra Mundial?", opciones: ["Generación Perdida", "Renacimiento de Harlem", "Generación Beat", "Transcendentalistas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué movimiento literario de los años 50, con Jack Kerouac y Allen Ginsberg, rechazó las normas sociales convencionales?", opciones: ["Generación Beat", "Generación Perdida", "Renacimiento de Harlem", "Modernismo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué artista pop estadounidense es famoso por sus serigrafías de latas de sopa Campbell?", opciones: ["Andy Warhol", "Jackson Pollock", "Roy Lichtenstein", "Jean-Michel Basquiat"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué corriente artística estadounidense de posguerra, con Jackson Pollock como referente, usaba goteo de pintura?", opciones: ["Expresionismo abstracto", "Arte pop", "Cubismo", "Minimalismo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué compositor estadounidense de origen ruso escribió \"Rhapsody in Blue\", fusionando jazz y música clásica?", opciones: ["George Gershwin", "Aaron Copland", "Leonard Bernstein", "John Williams"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué dramaturgo estadounidense escribió \"Muerte de un viajante\"?", opciones: ["Arthur Miller", "Tennessee Williams", "Eugene O'Neill", "Edward Albee"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué dramaturgo sureño escribió \"Un tranvía llamado deseo\"?", opciones: ["Tennessee Williams", "Arthur Miller", "Eugene O'Neill", "Edward Albee"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué filósofo y ensayista, junto a Thoreau, lideró el movimiento trascendentalista estadounidense del siglo XIX?", opciones: ["Ralph Waldo Emerson", "Mark Twain", "Walt Whitman", "Herman Melville"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué poeta estadounidense del siglo XIX escribió \"Hojas de hierba\"?", opciones: ["Walt Whitman", "Emily Dickinson", "Ralph Waldo Emerson", "Edgar Allan Poe"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Qué comida rápida, hecha de carne molida en pan, es un ícono estadounidense mundialmente popular?", opciones: ["Hamburguesa", "Taco", "Pizza", "Sushi"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué salsa dulce de tomate acompaña comúnmente las hamburguesas y papas fritas en EE.UU.?", opciones: ["Kétchup", "Mostaza", "Mayonesa", "Salsa BBQ"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué pastel estadounidense, típico de Acción de Gracias, se hace con calabaza?", opciones: ["Pastel de calabaza", "Pastel de manzana", "Pastel de queso", "Pastel de chocolate"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué carne asada lentamente con salsa ahumada, típica del sur de EE.UU., se llama?", opciones: ["Barbacoa (BBQ)", "Asado argentino", "Churrasco", "Parrillada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué sándwich estadounidense, con mantequilla de maní y mermelada, es un clásico infantil?", opciones: ["PB&J", "Club sandwich", "Grilled cheese", "BLT"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Qué plato de pollo frito, crujiente y sazonado, es típico del sur de Estados Unidos?", opciones: ["Pollo frito", "Pollo asado", "Pollo al curry", "Pollo teriyaki"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué postre helado, servido en cono o copa, es un básico estadounidense desde el siglo XIX?", opciones: ["Helado", "Flan", "Pudín", "Gelatina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué guiso de mariscos, típico de Nueva Inglaterra, se prepara con almejas y crema?", opciones: ["Clam chowder", "Ceviche", "Bullabesa", "Paella"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué pan dulce y esponjoso, relleno de mermelada o crema, es típico del desayuno estadounidense (de origen alemán)?", opciones: ["Donut", "Croissant", "Bagel", "Muffin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué pan con hueco en el centro, típico del desayuno neoyorquino, suele untarse con queso crema?", opciones: ["Bagel", "Donut", "Pretzel", "Muffin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué queso amarillo y procesado es característico de las hamburguesas estadounidenses?", opciones: ["Queso americano", "Queso brie", "Queso azul", "Queso parmesano"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato del sur de EE.UU., de arroz con mariscos y especias cajún, es típico de Luisiana?", opciones: ["Jambalaya", "Paella", "Risotto", "Sushi"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Qué guiso espeso de Luisiana, con base de roux, mariscos u okra, es típico de la cocina criolla/cajún?", opciones: ["Gumbo", "Jambalaya", "Chowder", "Étouffée"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué estilo de barbacoa, típico de Texas, usa principalmente carne de res (brisket)?", opciones: ["Barbacoa estilo Texas", "Barbacoa estilo Carolina", "Barbacoa estilo Memphis", "Barbacoa estilo Kansas City"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato de Filadelfia, sándwich de carne de res con queso fundido, es un ícono local?", opciones: ["Philly cheesesteak", "Reuben", "Po' boy", "Club sandwich"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué sándwich de Nueva Orleans, con mariscos fritos o carne, se sirve en pan francés?", opciones: ["Po' boy", "Philly cheesesteak", "Reuben", "BLT"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué pastel de queso, denso y cremoso, es un postre asociado a Nueva York?", opciones: ["Cheesecake", "Tiramisú", "Red velvet", "Brownie"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué salsa picante estadounidense, hecha con vinagre y chiles, se produce en Luisiana desde el siglo XIX?", opciones: ["Salsa Tabasco", "Salsa Valentina", "Salsa Cholula", "Sriracha"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué platillo del medio oeste de EE.UU., de origen alemán, consiste en salchicha en pan?", opciones: ["Hot dog", "Hamburguesa", "Bratwurst solo", "Corn dog"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué versión de hot dog, rebozado en masa de maíz y frito con palito, es típica de ferias estadounidenses?", opciones: ["Corn dog", "Hot dog clásico", "Chili dog", "Bagel dog"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato del sur de EE.UU., de maíz molido cocido como papilla, se sirve como acompañamiento (similar a la polenta)?", opciones: ["Grits", "Puré de papa", "Arroz blanco", "Cuscús"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué región estadounidense es reconocida por su estilo particular de barbacoa con salsa vinagre en vez de salsa de tomate?", opciones: ["Carolina del Norte", "Texas", "Kansas", "Memphis"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Qué ave rapaz, símbolo nacional de Estados Unidos, aparece en el escudo del país?", opciones: ["Águila calva", "Águila real", "Halcón peregrino", "Cóndor"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional, el primero del mundo, se estableció en EE.UU. en 1872?", opciones: ["Yellowstone", "Yosemite", "Gran Cañón", "Everglades"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran mamífero, símbolo de las llanuras norteamericanas, casi se extinguió en el siglo XIX?", opciones: ["Bisonte americano", "Alce", "Ciervo", "Búfalo de agua"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran cañón, tallado por el río Colorado, es un ícono natural de EE.UU.?", opciones: ["Gran Cañón", "Valle de la Muerte", "Cañón del Colca", "Monument Valley"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué oso, el más grande de Norteamérica, habita zonas como Alaska?", opciones: ["Oso pardo (grizzly)", "Oso panda", "Oso perezoso", "Oso de anteojos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Qué géiser, uno de los más famosos del mundo, entra en erupción regularmente en Yellowstone?", opciones: ["Old Faithful", "Strokkur", "Geysir", "El Tatio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué árboles gigantes, algunos de los más altos del mundo, crecen en California?", opciones: ["Secuoyas", "Robles", "Pinos", "Abetos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional de California protege los árboles más altos del mundo (secuoyas costeras)?", opciones: ["Redwood", "Yosemite", "Sequoia", "Death Valley"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué valle de California, el más caluroso registrado en la Tierra, es célebre por su aridez extrema?", opciones: ["Valle de la Muerte", "Desierto de Mojave", "Desierto de Sonora", "Desierto de Atacama"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran humedal subtropical del sur de Florida es hábitat de caimanes y aves?", opciones: ["Everglades", "Pantanal", "Ciénaga de Zapata", "Sundarbans"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué gato montés grande, el más veloz de América, habita algunas zonas remotas de EE.UU.?", opciones: ["Puma (león de montaña)", "Jaguar", "Guepardo", "Lince euroasiático"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave, la más grande de Norteamérica, casi se extinguió y hoy se recupera con programas de conservación?", opciones: ["Cóndor de California", "Águila calva", "Pelícano", "Buitre"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Qué géiser predecible de Yellowstone es el más famoso, en erupción cada 60-90 minutos aproximadamente?", opciones: ["Old Faithful", "Steamboat Geyser", "Grand Geyser", "Castle Geyser"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué géiser de Yellowstone es el más alto del mundo en erupción activa, aunque impredecible?", opciones: ["Steamboat Geyser", "Old Faithful", "Grand Geyser", "Riverside Geyser"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué caldera volcánica gigante subyace bajo el Parque Nacional Yellowstone?", opciones: ["Supervolcán de Yellowstone", "Volcán Santa Elena", "Volcán Shasta", "Volcán Rainier"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de árbol, la más alta del mundo, crece en los bosques de Redwood, California?", opciones: ["Secuoya costera", "Secuoya gigante", "Pino Bristlecone", "Abeto Douglas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué pino longevo, en California y Nevada, incluye algunos de los seres vivos individuales más antiguos del planeta?", opciones: ["Pino Bristlecone", "Secuoya gigante", "Roble", "Ciprés"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué montaña volcánica del estado de Washington es uno de los volcanes más peligrosos monitoreados de EE.UU.?", opciones: ["Monte Rainier", "Monte Santa Elena", "Monte Shasta", "Monte Hood"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué volcán del estado de Washington entró en erupción catastróficamente en 1980?", opciones: ["Monte Santa Elena", "Monte Rainier", "Monte Shasta", "Monte Hood"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué gato montés pequeño, de orejas puntiagudas, es común en bosques de Norteamérica?", opciones: ["Lince rojo (bobcat)", "Puma", "Jaguar", "Ocelote"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero acuático, casi extinto por la caza de pieles, se recupera hoy en las costas de California?", opciones: ["Nutria marina", "Foca", "Morsa", "Manatí"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional de Utah es célebre por sus arcos naturales de piedra roja?", opciones: ["Arches National Park", "Zion", "Bryce Canyon", "Yellowstone"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte con más audiencia televisiva en EE.UU., cuya final es el Super Bowl?", opciones: ["Fútbol americano", "Béisbol", "Baloncesto", "Hockey"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué liga profesional de baloncesto estadounidense es la más importante del mundo?", opciones: ["NBA", "NFL", "MLB", "NHL"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué liga profesional de béisbol estadounidense corona a su campeón en la \"World Series\"?", opciones: ["MLB", "NBA", "NFL", "NHL"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué exjugador de baloncesto, con 6 títulos con los Chicago Bulls, es considerado uno de los mejores de la historia?", opciones: ["Michael Jordan", "LeBron James", "Kobe Bryant", "Magic Johnson"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué gimnasta estadounidense es una de las más laureadas de la historia olímpica?", opciones: ["Simone Biles", "Serena Williams", "Katie Ledecky", "Allyson Felix"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Qué liga de hockey sobre hielo estadounidense-canadiense corona su campeón con la \"Copa Stanley\"?", opciones: ["NHL", "NBA", "NFL", "MLB"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué tenista estadounidense, con 23 títulos de Grand Slam, es una de las mejores de la historia?", opciones: ["Serena Williams", "Venus Williams", "Chris Evert", "Billie Jean King"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué nadador estadounidense es el atleta olímpico más laureado de la historia, con 23 medallas de oro?", opciones: ["Michael Phelps", "Mark Spitz", "Ryan Lochte", "Caeleb Dressel"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué exjugador de baloncesto, base de los Lakers, es apodado \"Magic\"?", opciones: ["Magic Johnson", "Michael Jordan", "Kobe Bryant", "LeBron James"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué exjugador de baloncesto, escolta de los Lakers, falleció en un accidente de helicóptero en 2020?", opciones: ["Kobe Bryant", "Michael Jordan", "Magic Johnson", "Shaquille O'Neal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué golfista estadounidense, activo entre los años 60-80, tiene el récord histórico de 18 títulos major?", opciones: ["Jack Nicklaus", "Tiger Woods", "Arnold Palmer", "Phil Mickelson"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué velocista estadounidense, medallista olímpica múltiple en pista, compitió en varias ediciones entre 2000 y 2010?", opciones: ["Allyson Felix", "Florence Griffith-Joyner", "Serena Williams", "Simone Biles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿Qué velocista estadounidense, apodada \"Flo-Jo\", ostenta el récord mundial de 100m femenino desde 1988?", opciones: ["Florence Griffith-Joyner", "Allyson Felix", "Wilma Rudolph", "Marion Jones"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué atleta estadounidense, con 4 medallas de oro en los Juegos de Berlín 1936, desafió la propaganda nazi?", opciones: ["Jesse Owens", "Jim Thorpe", "Carl Lewis", "Michael Johnson"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué velocista estadounidense ganó 4 medallas de oro en atletismo en los Juegos Olímpicos de 1984?", opciones: ["Carl Lewis", "Jesse Owens", "Michael Johnson", "Justin Gatlin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué exjugadora de tenis estadounidense, junto a su hermana, dominó el circuito femenino en los 2000?", opciones: ["Venus Williams", "Chris Evert", "Billie Jean King", "Martina Navratilova"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué exjugadora de tenis estadounidense luchó por la igualdad de género en el deporte, ganando el famoso \"Battle of the Sexes\" en 1973?", opciones: ["Billie Jean King", "Chris Evert", "Serena Williams", "Martina Navratilova"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué gimnasta estadounidense se retiró temporalmente de la final por equipos en Tokio 2020 por salud mental, y volvió a competir después?", opciones: ["Simone Biles", "Katie Ledecky", "Aly Raisman", "Gabby Douglas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué nadadora estadounidense es una de las más laureadas en natación de fondo, con múltiples oros olímpicos en los 2010s-2020s?", opciones: ["Katie Ledecky", "Simone Biles", "Missy Franklin", "Natalie Coughlin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué corredor de fondo estadounidense de los años 70, maratonista olímpico, popularizó el running como fenómeno de masas?", opciones: ["Frank Shorter", "Steve Prefontaine", "Bill Rodgers", "Alberto Salazar"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué exjugador de fútbol americano, mariscal de campo, ganó 7 Super Bowls, el mayor número histórico?", opciones: ["Tom Brady", "Peyton Manning", "Joe Montana", "Patrick Mahomes"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué evento anual, la carrera automovilística más famosa de EE.UU., se celebra en Indiana desde 1911?", opciones: ["Indianápolis 500", "Daytona 500", "Talladega", "Grand Prix de Miami"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
};
