import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

/** Banco de preguntas de Chile — verificadas manualmente, mismo estándar que Colombia/Perú.
 * Cada ronda tiene su propio set (sin solapamiento entre Explorador/Descubridor/Experto). */
export const BANCO_CHILE: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Chile?", opciones: ["Santiago", "Valparaíso", "Concepción", "Antofagasta"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Chile por el oeste?", opciones: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera recorre Chile de norte a sur?", opciones: ["Los Andes", "Los Alpes", "El Himalaya", "Los Urales"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué continente está ubicado Chile?", opciones: ["América del Sur", "América Central", "Oceanía", "Europa"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el idioma oficial de Chile?", opciones: ["Español", "Portugués", "Inglés", "Italiano"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Cuál es el desierto más árido del mundo, ubicado en el norte de Chile?", opciones: ["Desierto de Atacama", "Desierto del Sahara", "Desierto de Nazca", "Desierto de Sonora"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Con cuántos países limita Chile?", opciones: ["2", "3", "4", "5"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué característica geográfica distingue la forma del territorio chileno?", opciones: ["Es muy largo y angosto", "Es perfectamente cuadrado", "Es circular", "Es un archipiélago sin continente"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué isla chilena en el Pacífico es famosa por sus estatuas moái?", opciones: ["Isla de Pascua", "Islas Galápagos", "Islas Malvinas", "Islas Juan Fernández"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama la región más austral de Chile continental?", opciones: ["Magallanes", "Los Lagos", "Araucanía", "Aysén"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué estrecho separa Chile continental de Tierra del Fuego?", opciones: ["Estrecho de Magallanes", "Canal de Beagle", "Estrecho de Gibraltar", "Canal de Panamá"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama el volcán activo cercano a Pucón, uno de los más activos de Sudamérica?", opciones: ["Villarrica", "Osorno", "Llaima", "Chaitén"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Chile?", opciones: ["Ojos del Salado", "Aconcagua", "Llullaillaco", "Tupungato"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama el territorio que Chile reclama en la Antártida?", opciones: ["Territorio Chileno Antártico", "Tierra del Fuego", "Archipiélago de Chiloé", "Campos de Hielo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Cuántas regiones administrativas tiene Chile?", opciones: ["12", "14", "16", "18"], correctaIndex: 2, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué archipiélago del sur de Chile es famoso por sus palafitos e iglesias de madera?", opciones: ["Chiloé", "Juan Fernández", "Guaitecas", "Diego Ramírez"], correctaIndex: 0, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama la mayor masa de hielo del hemisferio sur fuera de la Antártida, en la Patagonia chilena?", opciones: ["Campo de Hielo Patagónico Sur", "Glaciar Perito Moreno", "Campo de Hielo Norte", "Casquete de Groenlandia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué corriente marina fría contribuye a la aridez extrema del desierto de Atacama?", opciones: ["Corriente de Humboldt", "Corriente del Golfo", "Corriente de Kuroshio", "Corriente Circumpolar Antártica"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿En qué archipiélago chileno se ubica la isla Robinson Crusoe?", opciones: ["Juan Fernández", "Chiloé", "Guaitecas", "Diego Ramírez"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es el lago más grande de Chile?", opciones: ["Lago General Carrera", "Lago Llanquihue", "Lago Ranco", "Lago Villarrica"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad puerto chilena, cerca de Santiago, es famosa por sus cerros y ascensores?", opciones: ["Valparaíso", "Viña del Mar", "Concepción", "Antofagasta"], correctaIndex: 0, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué salar chileno alberga las mayores reservas de litio del país?", opciones: ["Salar de Atacama", "Salar de Uyuni", "Salar del Hombre Muerto", "Salar de Arizaro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿Qué pueblo indígena resistió por siglos la conquista española en el sur de Chile?", opciones: ["Mapuche", "Inca", "Azteca", "Maya"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año se proclamó formalmente la independencia de Chile?", opciones: ["1810", "1818", "1821", "1825"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿A quién se considera el padre de la patria chilena?", opciones: ["Bernardo O'Higgins", "José de San Martín", "Simón Bolívar", "Diego Portales"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué conquistador español fundó Santiago en 1541?", opciones: ["Pedro de Valdivia", "Francisco Pizarro", "Diego de Almagro", "Hernán Cortés"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué explorador español llegó primero al territorio chileno en 1520, por el estrecho?", opciones: ["Hernando de Magallanes", "Diego de Almagro", "Pedro de Valdivia", "Francisco Pizarro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿Qué explorador español fue el primero en pisar Chile por tierra en 1536?", opciones: ["Diego de Almagro", "Pedro de Valdivia", "Hernando de Magallanes", "Francisco Pizarro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué batalla de 1818 selló la independencia de Chile?", opciones: ["Batalla de Maipú", "Batalla de Chacabuco", "Batalla de Rancagua", "Batalla de Ayacucho"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué guerra (1879-1883) hizo que Chile ganara territorio del norte a Perú y Bolivia?", opciones: ["Guerra del Pacífico", "Guerra del Chaco", "Guerra de la Triple Alianza", "Guerra de Arauco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Cómo se llamó el conflicto colonial de siglos entre españoles/chilenos y el pueblo mapuche?", opciones: ["Guerra de Arauco", "Guerra del Pacífico", "Guerra Civil chilena", "Guerra de los Mil Días"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué héroe naval chileno protagonizó el Combate Naval de Iquique en 1879?", opciones: ["Arturo Prat", "Bernardo O'Higgins", "Manuel Bulnes", "Ramón Freire"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué presidente chileno fue derrocado por un golpe militar en 1973?", opciones: ["Salvador Allende", "Eduardo Frei", "Patricio Aylwin", "Jorge Alessandri"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué general gobernó Chile en dictadura entre 1973 y 1990?", opciones: ["Augusto Pinochet", "Arturo Prat", "Bernardo O'Higgins", "Ramón Freire"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿Cómo se conoce la batalla de 1814 donde los realistas derrotaron a los patriotas chilenos?", opciones: ["Desastre de Rancagua", "Batalla de Maipú", "Batalla de Chacabuco", "Batalla de Cancha Rayada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué batalla de 1817 abrió el paso a la independencia de Chile?", opciones: ["Batalla de Chacabuco", "Batalla de Maipú", "Batalla de Rancagua", "Batalla de Cancha Rayada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Cómo se llamó el ejército liderado por San Martín que cruzó los Andes en 1817?", opciones: ["Ejército de los Andes", "Ejército Libertador del Sur", "Gran Ejército", "Ejército del Pacífico"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué ministro chileno del siglo XIX es considerado el organizador de la república conservadora?", opciones: ["Diego Portales", "Bernardo O'Higgins", "Manuel Montt", "Andrés Bello"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué tratado de 1904 fijó los límites definitivos entre Chile y Bolivia?", opciones: ["Tratado de 1904", "Tratado de Ancón", "Tratado de Tordesillas", "Tratado de Versalles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué tratado de 1883 puso fin a la guerra entre Chile y Perú?", opciones: ["Tratado de Ancón", "Tratado de 1904", "Tratado de Tordesillas", "Tratado de Petrópolis"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿En qué año ocurrió el golpe de Estado en Chile, un 11 de septiembre?", opciones: ["1973", "1970", "1980", "1990"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué presidente chileno asumió tras el retorno a la democracia en 1990?", opciones: ["Patricio Aylwin", "Salvador Allende", "Eduardo Frei Ruiz-Tagle", "Ricardo Lagos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Quién fue la primera mujer presidenta de Chile?", opciones: ["Michelle Bachelet", "Evelyn Matthei", "Gabriela Mistral", "Isabel Allende"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué cacique mapuche lideró la resistencia y venció a Pedro de Valdivia?", opciones: ["Lautaro", "Caupolicán", "Colo Colo", "Galvarino"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué poetisa chilena fue la primera latinoamericana en ganar el Nobel de Literatura, en 1945?", opciones: ["Gabriela Mistral", "Pablo Neruda", "Isabel Allende", "Nicanor Parra"], correctaIndex: 0, fuente: "NobelPrize.org", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué poeta chileno, Nobel de Literatura 1971, escribió \"Veinte poemas de amor\"?", opciones: ["Pablo Neruda", "Gabriela Mistral", "Vicente Huidobro", "Nicanor Parra"], correctaIndex: 0, fuente: "NobelPrize.org", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cuál es el baile nacional de Chile?", opciones: ["Cueca", "Marinera", "Tango", "Cumbia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué escritora chilena escribió \"La casa de los espíritus\"?", opciones: ["Isabel Allende", "Gabriela Mistral", "Marcela Serrano", "Diamela Eltit"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cómo se llaman las estatuas monumentales de piedra de Isla de Pascua?", opciones: ["Moáis", "Totems", "Menhires", "Estelas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿Qué cantautora chilena es autora de \"Gracias a la vida\"?", opciones: ["Violeta Parra", "Víctor Jara", "Isabel Parra", "Mercedes Sosa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué cantautor chileno, símbolo de resistencia, fue asesinado en 1973?", opciones: ["Víctor Jara", "Ángel Parra", "Patricio Manns", "Rolando Alarcón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué poeta chileno creó el movimiento de vanguardia \"creacionismo\"?", opciones: ["Vicente Huidobro", "Pablo Neruda", "Nicanor Parra", "Pablo de Rokha"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué poeta chileno es conocido por la \"antipoesía\"?", opciones: ["Nicanor Parra", "Pablo Neruda", "Vicente Huidobro", "Gonzalo Rojas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama el instrumento andino de tubos de caña unidos, también típico en Chile?", opciones: ["Zampoña", "Charango", "Cajón", "Bombo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Cuándo se celebran las Fiestas Patrias chilenas?", opciones: ["18 de septiembre", "5 de mayo", "16 de septiembre", "12 de octubre"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama a los habitantes originarios de Isla de Pascua?", opciones: ["Rapa Nui", "Mapuche", "Aimara", "Selknam"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué grupo musical chileno formó parte del movimiento de la Nueva Canción Chilena?", opciones: ["Inti-Illimani", "Los Prisioneros", "La Ley", "Los Tres"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué banda de rock chilena de los 80 es autora de \"El baile de los que sobran\"?", opciones: ["Los Prisioneros", "Inti-Illimani", "La Ley", "Chancho en Piedra"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escritor chileno escribió \"2666\" y \"Los detectives salvajes\"?", opciones: ["Roberto Bolaño", "Isabel Allende", "José Donoso", "Antonio Skármeta"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué novelista chileno escribió \"El obsceno pájaro de la noche\"?", opciones: ["José Donoso", "Roberto Bolaño", "Antonio Skármeta", "Luis Sepúlveda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escritor chileno escribió \"Ardiente paciencia\", base de \"El cartero de Neruda\"?", opciones: ["Antonio Skármeta", "José Donoso", "Roberto Bolaño", "Luis Sepúlveda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué pueblo indígena originario del extremo sur de Chile es hoy considerado extinto como cultura pura?", opciones: ["Selk'nam", "Mapuche", "Aimara", "Rapa Nui"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama el arte textil tradicional mapuche tejido en telar?", opciones: ["Witral", "Quipu", "Batik", "Ikat"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama el año nuevo mapuche, celebrado en el solsticio de invierno de junio?", opciones: ["We Tripantu", "Inti Raymi", "Nguillatún", "Machitún"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿En qué ciudad chilena se celebra el famoso Festival Internacional de la Canción?", opciones: ["Viña del Mar", "Santiago", "Valparaíso", "Concepción"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué director chileno ganó el Óscar en 2018 con \"Una mujer fantástica\"?", opciones: ["Sebastián Lelio", "Pablo Larraín", "Andrés Wood", "Patricio Guzmán"], correctaIndex: 0, fuente: "Academy of Motion Picture Arts", dificultad: "experto" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la empanada chilena rellena de carne, cebolla, huevo y aceituna?", opciones: ["Empanada de pino", "Empanada árabe", "Empanada gallega", "Empanada dulce"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es la bebida espirituosa chilena destilada de uva, también producida en Perú?", opciones: ["Pisco", "Tequila", "Ron", "Vodka"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el guiso chileno de choclo y carne, gratinado al horno?", opciones: ["Pastel de Choclo", "Cazuela", "Curanto", "Charquicán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el sándwich chileno de vienesa con palta, tomate y mayonesa?", opciones: ["Completo", "Chacarero", "Barros Luco", "Choripán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la bebida veraniega chilena de mote de trigo con durazno?", opciones: ["Mote con Huesillo", "Chicha morada", "Horchata", "Agua de Jamaica"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el guiso chileno con carne, papas, choclo y zapallo?", opciones: ["Cazuela", "Charquicán", "Curanto", "Porotos granados"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la técnica de cocción bajo tierra con piedras calientes, típica de Chiloé?", opciones: ["Curanto", "Pachamanca", "Barbacoa", "Asado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el guiso de frijoles con choclo y zapallo?", opciones: ["Porotos Granados", "Charquicán", "Cazuela", "Carbonada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el guiso de papas machacadas con charqui (carne seca)?", opciones: ["Charquicán", "Cazuela", "Porotos Granados", "Carbonada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el sándwich chileno de carne en tira con ají verde y porotos verdes?", opciones: ["Chacarero", "Completo", "Barros Luco", "Lomito"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el postre chileno navideño de origen alemán, con frutas y té?", opciones: ["Kuchen", "Alfajor", "Panqueque", "Suspiro limeño"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué tipo de marisco son los \"locos\", muy apreciados en la gastronomía chilena?", opciones: ["Un molusco (especie de abalón)", "Un crustáceo", "Un pez", "Un alga"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Cuál es la cepa de vino insignia de Chile, redescubierta en los años 90 tras creerse extinta?", opciones: ["Carmenère", "Malbec", "Cabernet Sauvignon", "Merlot"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es el valle vitivinícola más antiguo y prestigioso de Chile, cerca de Santiago?", opciones: ["Valle del Maipo", "Valle de Colchagua", "Valle de Casablanca", "Valle del Elqui"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿En qué valle chileno se produce pisco con Denominación de Origen, junto a un observatorio astronómico?", opciones: ["Valle del Elqui", "Valle del Maipo", "Valle de Casablanca", "Valle de Colchagua"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruto silvestre patagónico, oscuro, se usa mucho en mermeladas del sur de Chile?", opciones: ["Calafate", "Frutilla", "Chirimoya", "Lúcuma"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el pan chileno horneado tradicionalmente bajo las cenizas o rescoldo del fogón?", opciones: ["Tortilla al rescoldo", "Pan amasado", "Sopaipilla", "Marraqueta"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el pan frito de zapallo, muy popular como snack callejero en Chile?", opciones: ["Sopaipilla", "Marraqueta", "Hallulla", "Pan amasado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el pan crujiente chileno, símbolo del desayuno y la once?", opciones: ["Marraqueta", "Sopaipilla", "Kuchen", "Pan de pascua"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el pan dulce navideño chileno con frutas confitadas?", opciones: ["Pan de Pascua", "Kuchen", "Panettone", "Rosca de Reyes"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la salsa picante chilena de ají, tomate, cilantro y limón?", opciones: ["Pebre", "Chimichurri", "Pico de gallo", "Chancho en piedra"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la salsa chilena de tomate, ají y ajo molidos que acompaña el pan?", opciones: ["Chancho en Piedra", "Pebre", "Ají verde", "Salsa criolla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Cuál es el ave nacional de Chile, presente en el escudo?", opciones: ["Cóndor andino", "Águila", "Tucán", "Colibrí"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué ciervo, en peligro de extinción, es el animal nacional de Chile en el escudo?", opciones: ["Huemul", "Guanaco", "Vicuña", "Llama"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es la flor nacional de Chile?", opciones: ["Copihue", "Orquídea", "Cantuta", "Ceibo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué desierto chileno es considerado el más árido del mundo?", opciones: ["Desierto de Atacama", "Desierto de Sonora", "Desierto del Sahara", "Desierto de Nazca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué región del sur de Chile, con lagos y volcanes, es apodada \"la Suiza de América\"?", opciones: ["Región de los Lagos", "Región de Aysén", "Región de Magallanes", "Región de Coquimbo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional chileno protege las Torres del Paine?", opciones: ["Parque Nacional Torres del Paine", "Parque Nacional Vicente Pérez Rosales", "Parque Nacional Conguillío", "Parque Nacional Lauca"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional en el altiplano chileno, cerca de Arica, tiene volcanes y flamencos?", opciones: ["Parque Nacional Lauca", "Parque Nacional Torres del Paine", "Parque Nacional Chiloé", "Reserva Nacional Los Flamencos"], correctaIndex: 0, fuente: "SERNATUR", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué volcán causó una erupción en 2008 que cubrió de ceniza el sur de Chile y Argentina?", opciones: ["Chaitén", "Villarrica", "Osorno", "Llaima"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué pingüino habita las costas del norte y centro de Chile?", opciones: ["Pingüino de Humboldt", "Pingüino emperador", "Pingüino rey", "Pingüino de Magallanes"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama el zorro andino, mamífero carnívoro muy común en Chile?", opciones: ["Zorro culpeo", "Puma", "Chingue", "Quique"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué reserva en el desierto de Atacama es famosa por sus flamencos?", opciones: ["Reserva Nacional Los Flamencos", "Parque Nacional Lauca", "Parque Nacional Pan de Azúcar", "Reserva Nacional Las Vicuñas"], correctaIndex: 0, fuente: "SERNATUR", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama el bosque templado lluvioso del sur de Chile, con alerces milenarios?", opciones: ["Bosque Valdiviano", "Selva Amazónica", "Bosque de Niebla", "Manglar"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Qué árbol chileno milenario es uno de los seres vivos más longevos del planeta?", opciones: ["Alerce", "Araucaria", "Ciprés de las Guaitecas", "Roble"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué árbol chileno en forma de paraguas, considerado fósil viviente, es típico de la Araucanía?", opciones: ["Araucaria", "Alerce", "Ciprés", "Roble"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es el felino más grande de Chile y de toda América?", opciones: ["Puma", "Jaguar", "Ocelote", "Guiña"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es el felino silvestre más pequeño de América, presente en los bosques chilenos?", opciones: ["Guiña", "Puma", "Ocelote", "Gato de pajonal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué recurso abunda en los Campos de Hielo Patagónicos, la mayor reserva del hemisferio sur fuera de la Antártida?", opciones: ["Agua dulce (hielo glaciar)", "Petróleo", "Cobre", "Litio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿De qué mineral Chile es el mayor productor y exportador del mundo?", opciones: ["Cobre", "Oro", "Plata", "Hierro"], correctaIndex: 0, fuente: "COCHILCO", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué animal peligroso NO existe de forma nativa en Chile, a diferencia de gran parte de Sudamérica?", opciones: ["Serpientes venenosas", "Arañas", "Alacranes", "Pumas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero marino gigante se puede avistar en las costas del sur de Chile durante su migración?", opciones: ["Ballena azul", "Orca", "Foca", "Elefante marino"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional de la Patagonia chilena, Reserva de la Biósfera UNESCO, tiene un glaciar colgante?", opciones: ["Parque Nacional Queulat", "Parque Nacional Conguillío", "Parque Nacional Chiloé", "Parque Nacional Vicente Pérez Rosales"], correctaIndex: 0, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama el fenómeno donde el desierto de Atacama se llena de flores tras lluvias raras?", opciones: ["Desierto Florido", "Primavera Austral", "Floración de Atacama", "Verano Boreal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte más popular en Chile?", opciones: ["Fútbol", "Tenis", "Básquetbol", "Rodeo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cómo se le conoce popularmente a la selección chilena de fútbol?", opciones: ["La Roja", "La Albiceleste", "La Verdeamarela", "La Tricolor"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué deporte es considerado el deporte nacional oficial de Chile por ley?", opciones: ["Rodeo", "Fútbol", "Tenis", "Vóleibol"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué tenista chileno ganó medalla de oro olímpica en dobles en Atenas 2004?", opciones: ["Nicolás Massú", "Marcelo Ríos", "Fernando González", "Cristian Garín"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué tenista chileno llegó al puesto número 1 del ranking mundial ATP en 1998?", opciones: ["Marcelo Ríos", "Nicolás Massú", "Fernando González", "Hans Gildemeister"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Cómo se llama el recinto con forma de medialuna donde se practica el rodeo chileno?", opciones: ["Medialuna", "Coliseo", "Hipódromo", "Estadio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué tenista chileno ganó medalla de plata individual en Atenas 2004?", opciones: ["Fernando González", "Marcelo Ríos", "Nicolás Massú", "Cristian Garín"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿En qué país se jugó y ganó Brasil su segunda Copa del Mundo, en 1962?", opciones: ["Chile", "Perú", "Argentina", "Uruguay"], correctaIndex: 0, fuente: "FIFA", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué futbolista chileno fue capitán e ícono de la \"Generación Dorada\"?", opciones: ["Alexis Sánchez", "Arturo Vidal", "Claudio Bravo", "Iván Zamorano"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué arquero chileno fue referente de la \"Generación Dorada\", campeón de Copa América?", opciones: ["Claudio Bravo", "Alexis Sánchez", "Arturo Vidal", "Marcelo Ríos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿En qué años Chile ganó la Copa América dos veces consecutivas?", opciones: ["2015 y 2016", "2007 y 2011", "1991 y 1993", "2019 y 2021"], correctaIndex: 0, fuente: "CONMEBOL", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué deporte de invierno se practica en centros como Portillo, en los Andes chilenos?", opciones: ["Esquí", "Patinaje sobre hielo", "Hockey sobre hielo", "Curling"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿Qué futbolista chileno, apodado \"Bam Bam\", fue delantero estrella en los 90?", opciones: ["Iván Zamorano", "Marcelo Salas", "Alexis Sánchez", "Arturo Vidal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué delantero chileno, apodado \"el Matador\", brilló junto a Zamorano en los 90?", opciones: ["Marcelo Salas", "Iván Zamorano", "Alexis Sánchez", "Arturo Vidal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad chilena fue sede de los Juegos Panamericanos de 2023?", opciones: ["Santiago", "Valparaíso", "Concepción", "Viña del Mar"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué tenista chileno de nueva generación llegó al top 20 del ranking ATP?", opciones: ["Cristian Garín", "Nicolás Jarry", "Alejandro Tabilo", "Jorge Aguilar"], correctaIndex: 0, fuente: "ATP Tour", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Cuál es el club chileno más ganador históricamente en el fútbol local?", opciones: ["Colo-Colo", "Universidad de Chile", "Universidad Católica", "Cobreloa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué año Colo-Colo ganó la Copa Libertadores, su único título en ese torneo?", opciones: ["1991", "1996", "2000", "1981"], correctaIndex: 0, fuente: "CONMEBOL", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad chilena fue parte del recorrido del Rally Dakar en ediciones sudamericanas?", opciones: ["Antofagasta", "Santiago", "Valparaíso", "Concepción"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué año la selección chilena femenina de fútbol se clasificó por primera vez a un Mundial?", opciones: ["2019", "2015", "2011", "2023"], correctaIndex: 0, fuente: "FIFA", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Cómo se conoce popularmente al club Universidad de Chile?", opciones: ["La U", "Los Albos", "La Cruzados", "Los Zorros"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Cómo se llama la competencia ciclística de resistencia que se disputa anualmente en Chile?", opciones: ["Vuelta Ciclista de Chile", "Tour de Francia", "Giro de Italia", "Vuelta a España"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
};
