import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

/** Banco de preguntas de Perú — verificadas manualmente, mismo estándar que Colombia.
 * Cada ronda tiene su propio set (sin solapamiento entre Explorador/Descubridor/Experto). */
export const BANCO_PERU: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Perú?", opciones: ["Lima", "Cusco", "Arequipa", "Trujillo"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Perú?", opciones: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera atraviesa Perú?", opciones: ["Los Andes", "Los Alpes", "El Himalaya", "Las Rocosas"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué continente está ubicado Perú?", opciones: ["América del Sur", "América Central", "Norteamérica", "Europa"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el idioma oficial principal de Perú?", opciones: ["Español", "Portugués", "Inglés", "Francés"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Cuál es el lago navegable más alto del mundo, compartido con Bolivia?", opciones: ["Titicaca", "Poopó", "Junín", "Chinchaycocha"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad fue la capital histórica del Imperio Inca?", opciones: ["Cusco", "Lima", "Arequipa", "Puno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿En qué desierto peruano se encuentran las famosas Líneas de Nazca?", opciones: ["Desierto de Nazca", "Desierto de Sechura", "Desierto de Atacama", "Desierto de la Tatacoa"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Con cuántos países limita Perú?", opciones: ["3", "4", "5", "6"], correctaIndex: 2, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué río, considerado uno de los orígenes del Amazonas, nace en Perú?", opciones: ["Río Apurímac", "Río Marañón", "Río Ucayali", "Río Madre de Dios"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿En qué región natural del Perú se encuentra Machu Picchu?", opciones: ["Sierra", "Costa", "Selva", "Altiplano"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad peruana es conocida como \"la Ciudad Blanca\"?", opciones: ["Arequipa", "Trujillo", "Cusco", "Chiclayo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuántos departamentos tiene el Perú?", opciones: ["22", "24", "26", "28"], correctaIndex: 1, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Perú?", opciones: ["Nevado Huascarán", "Coropuna", "Ausangate", "Salcantay"], correctaIndex: 0, fuente: "IGN Perú", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿En qué cordillera está ubicado el nevado Huascarán?", opciones: ["Cordillera Blanca", "Cordillera Negra", "Cordillera Oriental", "Cordillera Vilcabamba"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es la ciudad portuaria principal del Perú, cercana a Lima?", opciones: ["Callao", "Paita", "Chimbote", "Ilo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿A qué gran cuenca pertenece la selva peruana?", opciones: ["Amazónica", "Del Plata", "Del Orinoco", "Del Pacífico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama el cañón de Arequipa, famoso por sus vuelos de cóndor?", opciones: ["Cañón del Colca", "Gran Cañón", "Cañón del Colorado", "Cañón del Sumidero"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cómo se llaman las islas frente a Paracas conocidas como \"las Galápagos peruanas\"?", opciones: ["Islas Ballestas", "Islas Chincha", "Isla San Lorenzo", "Isla Foca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué corriente marina fría influye en el clima árido de la costa peruana?", opciones: ["Corriente de Humboldt", "Corriente del Golfo", "Corriente de California", "Corriente de Kuroshio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama la región natural de meseta alta andina del sur de Perú, sobre los 4,000 msnm?", opciones: ["Puna", "Selva", "Yunga", "Costa"], correctaIndex: 0, fuente: "Pulgar Vidal — Geografía del Perú", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuántas regiones naturales identificó Javier Pulgar Vidal para clasificar el territorio peruano?", opciones: ["6", "8", "10", "12"], correctaIndex: 1, fuente: "Pulgar Vidal — Geografía del Perú", dificultad: "experto" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿Qué imperio gobernó Perú antes de la conquista española?", opciones: ["Imperio Inca", "Imperio Azteca", "Imperio Maya", "Imperio Tolteca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Cuál fue la capital del Imperio Inca?", opciones: ["Cusco", "Lima", "Quito", "Machu Picchu"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué español conquistó el Imperio Inca?", opciones: ["Francisco Pizarro", "Hernán Cortés", "Diego de Almagro", "Pedro de Valdivia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año se proclamó la independencia de Perú?", opciones: ["1810", "1821", "1824", "1830"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué libertador proclamó la independencia del Perú en 1821?", opciones: ["José de San Martín", "Simón Bolívar", "Antonio José de Sucre", "Bernardo O'Higgins"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿Quién fue el último inca ejecutado por los españoles, en 1572?", opciones: ["Túpac Amaru I", "Atahualpa", "Huáscar", "Manco Cápac"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué inca fue capturado y ejecutado por Pizarro en Cajamarca en 1533?", opciones: ["Atahualpa", "Huáscar", "Túpac Amaru", "Pachacútec"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué batalla de 1824, en territorio peruano, selló la independencia sudamericana?", opciones: ["Batalla de Ayacucho", "Batalla de Junín", "Batalla de Boyacá", "Batalla de Carabobo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Cómo se llamó la guerra entre Perú/Bolivia contra Chile (1879-1883)?", opciones: ["Guerra del Pacífico", "Guerra de la Triple Alianza", "Guerra del Chaco", "Guerra de los Mil Días"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué emperador inca expandió el imperio y mandó construir Machu Picchu?", opciones: ["Pachacútec", "Huayna Cápac", "Atahualpa", "Túpac Yupanqui"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué ciudad fundó Pizarro en 1535 como \"Ciudad de los Reyes\"?", opciones: ["Lima", "Cusco", "Trujillo", "Arequipa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Cómo se llamaba el sistema de caminos incas que conectaba el imperio?", opciones: ["Qhapaq Ñan", "Camino de Santiago", "Ruta de la Seda", "Vía Apia"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿Entre qué dos hermanos incas hubo una guerra civil justo antes de la llegada de los españoles?", opciones: ["Huáscar y Atahualpa", "Pachacútec y Túpac Yupanqui", "Manco Inca y Huayna Cápac", "Sayri Túpac y Titu Cusi"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Cuál fue el último reducto inca de resistencia tras la caída de Cusco?", opciones: ["Vilcabamba", "Ollantaytambo", "Sacsayhuamán", "Choquequirao"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué inca lideró la resistencia y fundó el estado neo-inca de Vilcabamba?", opciones: ["Manco Inca", "Túpac Amaru II", "Atahualpa", "Huayna Cápac"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué líder indígena encabezó una gran rebelión contra el dominio español en 1780?", opciones: ["Túpac Amaru II", "Túpac Katari", "Juan Santos Atahualpa", "Manco Inca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué militar peruano es héroe de la batalla de Arica en la Guerra del Pacífico?", opciones: ["Francisco Bolognesi", "Miguel Grau", "Andrés Avelino Cáceres", "Ramón Castilla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué almirante peruano es héroe naval del Combate de Angamos (1879)?", opciones: ["Miguel Grau", "Francisco Bolognesi", "José Gálvez", "Manuel Gonzáles Prada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué presidente peruano abolió la esclavitud en 1854?", opciones: ["Ramón Castilla", "José de la Riva Agüero", "Andrés de Santa Cruz", "Nicolás de Piérola"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Cómo se llamó la unión entre Perú y Bolivia entre 1836 y 1839?", opciones: ["Confederación Perú-Boliviana", "Gran Colombia", "Confederación Argentina", "Unión Ibérica"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué explorador estadounidense dio a conocer Machu Picchu al mundo en 1911?", opciones: ["Hiram Bingham", "Percy Fawcett", "John Rowe", "Alfred Kroeber"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿En qué año Machu Picchu fue declarado Patrimonio de la Humanidad por la UNESCO?", opciones: ["1972", "1983", "1994", "2000"], correctaIndex: 1, fuente: "UNESCO", dificultad: "experto" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué escritor peruano ganó el Premio Nobel de Literatura en 2010?", opciones: ["Mario Vargas Llosa", "Gabriel García Márquez", "Pablo Neruda", "Octavio Paz"], correctaIndex: 0, fuente: "NobelPrize.org", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cuál es el idioma indígena más hablado en Perú, además del español?", opciones: ["Quechua", "Náhuatl", "Guaraní", "Maya"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cuál es el baile nacional del Perú?", opciones: ["Marinera", "Cumbia", "Tango", "Samba"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento de percusión afroperuano es típico del Perú?", opciones: ["Cajón peruano", "Bongó", "Djembé", "Congas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cuál es la ciudadela inca de piedra, maravilla del mundo moderno?", opciones: ["Machu Picchu", "Chichén Itzá", "Petra", "Angkor Wat"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿Qué novela de Vargas Llosa transcurre en un cuartel militar?", opciones: ["La ciudad y los perros", "Cien años de soledad", "Pedro Páramo", "Rayuela"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama el gorro andino con orejeras tejido en lana, típico de Perú?", opciones: ["Chullo", "Sombrero vueltiao", "Sombrero cordobés", "Panama hat"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama el festival inca al Sol, celebrado en Cusco cada junio?", opciones: ["Inti Raymi", "Qoyllur Rit'i", "Corpus Christi", "Semana Santa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor peruano escribió \"Los ríos profundos\"?", opciones: ["José María Arguedas", "Mario Vargas Llosa", "Ciro Alegría", "César Vallejo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué poeta peruano escribió \"Los heraldos negros\"?", opciones: ["César Vallejo", "Mario Vargas Llosa", "Pablo Neruda", "José María Eguren"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué género musical costeño limeño incluye al \"vals criollo\"?", opciones: ["Música criolla", "Cumbia", "Huayno", "Salsa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama la danza andina en parejas con zapateo fuerte?", opciones: ["Huayno", "Marinera", "Festejo", "Zamacueca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué cultura preincaica es famosa por sus mantos textiles funerarios hallados en Paracas?", opciones: ["Cultura Paracas", "Cultura Nazca", "Cultura Moche", "Cultura Chavín"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué cultura preincaica es famosa por su cerámica escultórica (huaco retrato)?", opciones: ["Cultura Moche", "Cultura Nazca", "Cultura Chimú", "Cultura Wari"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama la ciudadela de barro más grande de la América precolombina, de la cultura Chimú?", opciones: ["Chan Chan", "Caral", "Kuélap", "Sipán"], correctaIndex: 0, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cuál es el sitio arqueológico considerado la civilización más antigua de América?", opciones: ["Caral", "Chavín de Huántar", "Chan Chan", "Kuélap"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué cultura preincaica de la sierra norte es famosa por su templo con cabezas clavas?", opciones: ["Chavín", "Nazca", "Paracas", "Wari"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama la ciudadela conocida como \"la Machu Picchu del norte\", de la cultura Chachapoyas?", opciones: ["Kuélap", "Choquequirao", "Ollantaytambo", "Sacsayhuamán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cómo se conoce el hallazgo de tumbas reales moche descubiertas en 1987 en Lambayeque?", opciones: ["Señor de Sipán", "Señor de Sicán", "Dama de Cao", "Niño del Cerro El Plomo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escritor peruano escribió \"El mundo es ancho y ajeno\"?", opciones: ["Ciro Alegría", "José María Arguedas", "Mario Vargas Llosa", "Julio Ramón Ribeyro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué pintor peruano fue referente del indigenismo en el siglo XX?", opciones: ["José Sabogal", "Fernando de Szyszlo", "Fernando Botero", "Diego Rivera"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Cómo se llama el instrumento de viento andino hecho de varios tubos de caña unidos?", opciones: ["Zampoña", "Quena", "Charango", "Bombo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Cuál es el plato bandera del Perú, pescado marinado en limón?", opciones: ["Ceviche", "Sushi", "Tiradito", "Sashimi"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es la bebida espirituosa de bandera del Perú, destilada de uva?", opciones: ["Pisco", "Tequila", "Ron", "Vodka"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es el tubérculo originario de los Andes peruanos, base de la dieta?", opciones: ["Papa", "Maíz", "Yuca", "Trigo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el cóctel nacional peruano a base de pisco?", opciones: ["Pisco Sour", "Mojito", "Margarita", "Daiquiri"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es el grano andino altamente nutritivo, llamado \"supergrano\"?", opciones: ["Quinua", "Arroz", "Trigo", "Cebada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el plato de carne salteada con papas fritas y arroz, de origen chino-peruano?", opciones: ["Lomo Saltado", "Ají de Gallina", "Rocoto Relleno", "Seco de Cabrito"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cuál es el plato de pollo deshilachado en crema de ají amarillo?", opciones: ["Ají de Gallina", "Lomo Saltado", "Causa Limeña", "Anticuchos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llaman las brochetas de corazón de res a la parrilla?", opciones: ["Anticuchos", "Pachamanca", "Chicharrón", "Cuy chactado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el plato frío de puré de papa amarilla rellena?", opciones: ["Causa Limeña", "Papa a la Huancaína", "Ocopa", "Carapulcra"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la técnica de cocción ancestral bajo tierra con piedras calientes?", opciones: ["Pachamanca", "Barbacoa", "Asado", "Curanto"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué animal andino, similar a un conejillo de indias, se come asado en fiestas?", opciones: ["Cuy", "Conejo", "Cerdo", "Cabrito"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el plato de papas cocidas bañadas en salsa de ají amarillo, huevo y aceitunas?", opciones: ["Papa a la Huancaína", "Causa Limeña", "Ocopa", "Rocoto Relleno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Qué fruta peruana de pulpa amarilla y sabor a caramelo se usa mucho para hacer helados?", opciones: ["Lúcuma", "Chirimoya", "Granadilla", "Tuna"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el plato de pescado crudo en tiras finas, de la cocina Nikkei?", opciones: ["Tiradito", "Ceviche", "Sashimi", "Carpaccio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué ciudad peruana ha sido reconocida como capital gastronómica de América Latina?", opciones: ["Lima", "Cusco", "Arequipa", "Trujillo"], correctaIndex: 0, fuente: "World Travel Awards", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué chef peruano fundó el restaurante Central, varias veces \"mejor de Latinoamérica\"?", opciones: ["Virgilio Martínez", "Gastón Acurio", "Rafael Osterling", "Pedro Miguel Schiaffino"], correctaIndex: 0, fuente: "The World's 50 Best Restaurants", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué chef peruano es el más reconocido internacionalmente, fundador de \"Astrid y Gastón\"?", opciones: ["Gastón Acurio", "Virgilio Martínez", "Mitsuharu Tsumura", "Javier Wong"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el guiso picante de cabrito con frijoles y culantro, típico del norte de Perú?", opciones: ["Seco de Cabrito", "Rocoto Relleno", "Carapulcra", "Chupe de Camarones"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la sopa cremosa de camarones típica de Arequipa?", opciones: ["Chupe de Camarones", "Chairo", "Parihuela", "Aguadito"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama el ají picante relleno de carne, típico de Arequipa?", opciones: ["Rocoto Relleno", "Ají de Gallina", "Papa Rellena", "Tamal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué restaurante peruano ha sido nombrado varias veces \"Mejor restaurante de Latinoamérica\"?", opciones: ["Central", "Maido", "Astrid y Gastón", "Mayta"], correctaIndex: 0, fuente: "The World's 50 Best Restaurants", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Cómo se llama la fusión culinaria entre la cocina peruana y japonesa?", opciones: ["Nikkei", "Chifa", "Criolla", "Novoandina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Cuál es el ave nacional del Perú, que vive en los Andes?", opciones: ["Gallito de las rocas", "Cóndor andino", "Colibrí", "Tucán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué camélido andino, símbolo del escudo nacional del Perú, da la lana más fina del mundo?", opciones: ["Vicuña", "Llama", "Alpaca", "Guanaco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿A qué bioma pertenece gran parte de la selva peruana?", opciones: ["Selva Amazónica", "Selva del Congo", "Sabana", "Tundra"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es la flor nacional del Perú?", opciones: ["Cantuta", "Orquídea", "Girasol", "Amapola"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué oso, el único de Sudamérica, habita los bosques andinos del Perú?", opciones: ["Oso de anteojos", "Oso panda", "Oso pardo", "Oso polar"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama el parque nacional peruano en la Amazonía, famoso por su biodiversidad?", opciones: ["Parque Nacional del Manu", "Parque Nacional Huascarán", "Reserva de Paracas", "Parque Nacional Tingo María"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿A qué altura aproximada sobre el nivel del mar está el Lago Titicaca?", opciones: ["3,800 msnm", "1,500 msnm", "5,000 msnm", "500 msnm"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llaman las islas artificiales de totora en el Lago Titicaca?", opciones: ["Islas de los Uros", "Isla Taquile", "Islas Ballestas", "Isla Amantaní"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama la reserva costera peruana famosa por sus lobos marinos y pingüinos?", opciones: ["Reserva Nacional de Paracas", "Parque Nacional del Manu", "Reserva de Tambopata", "Parque Nacional Huascarán"], correctaIndex: 0, fuente: "SERNANP", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué camélido silvestre andino, más grande que la vicuña, habita el sur de Perú?", opciones: ["Guanaco", "Vicuña", "Alpaca", "Llama"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es el primate más pequeño del mundo, que habita la Amazonía peruana?", opciones: ["Mono tití pigmeo", "Mono araña", "Mono aullador", "Marimonda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué río peruano se une al Marañón para formar el río Amazonas?", opciones: ["Ucayali", "Apurímac", "Madre de Dios", "Huallaga"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Cuál es el segundo pico más alto de Perú?", opciones: ["Yerupajá", "Coropuna", "Ausangate", "Salcantay"], correctaIndex: 0, fuente: "IGN Perú", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama la reserva en Madre de Dios famosa por sus \"collpas\" de guacamayos?", opciones: ["Tambopata", "Manu", "Pacaya-Samiria", "Bahuaja-Sonene"], correctaIndex: 0, fuente: "SERNANP", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es la reserva nacional más grande de Perú, en la Amazonía de Loreto?", opciones: ["Pacaya-Samiria", "Manu", "Tambopata", "Alto Purús"], correctaIndex: 0, fuente: "SERNANP", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cuál es el felino más grande de la Amazonía peruana?", opciones: ["Jaguar", "Puma", "Ocelote", "Tigrillo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama el delfín rosado que habita los ríos amazónicos de Perú?", opciones: ["Bufeo colorado", "Delfín nariz de botella", "Orca", "Manatí"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama el ecorregión de bosque seco en la costa norte de Perú?", opciones: ["Bosque seco de Tumbes", "Selva de niebla", "Manglar", "Puna"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave marina, símbolo de la riqueza pesquera de la Corriente de Humboldt, es común en la costa peruana?", opciones: ["Pelícano peruano", "Albatros errante", "Gaviotín", "Cormorán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué camélido doméstico se cría por su fibra fina, distinto de la llama?", opciones: ["Alpaca", "Llama", "Vicuña", "Guanaco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional protege el Huascarán y su glaciar?", opciones: ["Parque Nacional Huascarán", "Parque Nacional del Manu", "Santuario de Machu Picchu", "Reserva de Paracas"], correctaIndex: 0, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué lugar ocupa Perú en el mundo por diversidad de especies de aves?", opciones: ["Segundo lugar", "Quinto lugar", "Décimo lugar", "Vigésimo lugar"], correctaIndex: 0, fuente: "SERNANP", dificultad: "experto" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte más popular en Perú?", opciones: ["Fútbol", "Vóleibol", "Básquetbol", "Tenis"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cómo se le conoce popularmente a la selección peruana de fútbol?", opciones: ["La Bicolor", "La Verdeamarela", "La Albiceleste", "La Tricolor"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿En qué deporte la selección femenina peruana fue subcampeona mundial en 1982?", opciones: ["Vóleibol", "Básquetbol", "Balonmano", "Fútbol"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cómo se llama el estadio principal de la selección peruana en Lima?", opciones: ["Estadio Nacional", "Estadio Monumental", "Estadio Azteca", "Maracaná"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué deporte acuático es muy popular en la costa peruana?", opciones: ["Surf", "Buceo", "Vela", "Remo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Qué futbolista peruano fue capitán en el Mundial de España 1982?", opciones: ["Héctor Chumpitaz", "Teófilo Cubillas", "Jefferson Farfán", "Paolo Guerrero"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Quién es el máximo goleador histórico de la selección peruana de fútbol?", opciones: ["Paolo Guerrero", "Teófilo Cubillas", "Jefferson Farfán", "Claudio Pizarro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué futbolista peruano jugó muchos años en el Bayern Múnich?", opciones: ["Claudio Pizarro", "Paolo Guerrero", "Jefferson Farfán", "André Carrillo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué tenista peruano-estadounidense ganó Wimbledon en 1959?", opciones: ["Alex Olmedo", "Luis Horna", "Jaime Yzaga", "Pablo Arraya"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿En qué deporte compitió la peruana Kina Malpartida, campeona mundial?", opciones: ["Boxeo", "Judo", "Taekwondo", "Lucha libre"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué famosa carrera de rally internacional se ha corrido varias veces por el desierto peruano?", opciones: ["Rally Dakar", "Fórmula 1", "MotoGP", "Rally de Montecarlo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué peruana fue campeona mundial de tabla/surf en 2004?", opciones: ["Sofía Mulánovich", "Kina Malpartida", "Ana Sofía Aguilar", "Gladys Tejeda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿En qué año Perú fue campeón de la Copa América?", opciones: ["1975", "1985", "1995", "2005"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué atleta peruana, maratonista, es medallista panamericana?", opciones: ["Gladys Tejeda", "Sofía Mulánovich", "Kina Malpartida", "Inés Melchor"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad peruana fue sede de los Juegos Panamericanos de 2019?", opciones: ["Lima", "Cusco", "Arequipa", "Trujillo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué Mundial de fútbol Perú llegó a cuartos de final, su mejor actuación histórica?", opciones: ["México 1970", "Argentina 1978", "España 1982", "Rusia 2018"], correctaIndex: 0, fuente: "FIFA", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué federación regula el fútbol profesional en Perú?", opciones: ["Federación Peruana de Fútbol", "Comité Olímpico Peruano", "Instituto Peruano del Deporte", "Liga1"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué año la selección peruana de vóley femenino fue subcampeona mundial?", opciones: ["1982", "1992", "2002", "1978"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué entrenador peruano lideró a la \"Generación Dorada\" del vóley femenino en los 80?", opciones: ["Man Bohórquez", "Marcelo Tinelli", "Ricardo Gareca", "Carlos Bilardo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué entrenador argentino clasificó a Perú al Mundial 2018 tras 36 años de ausencia?", opciones: ["Ricardo Gareca", "Marcelo Bielsa", "Diego Simeone", "José Pekerman"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué estadio limeño se jugó la final de la Copa Libertadores 2019?", opciones: ["Estadio Monumental de Lima", "Estadio Nacional", "Estadio Alejandro Villanueva", "Maracaná"], correctaIndex: 0, fuente: "CONMEBOL", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Cuál es el máximo logro olímpico histórico de la selección peruana femenina de vóley?", opciones: ["Medalla de plata en Seúl 1988", "Medalla de oro en Múnich 1972", "Medalla de bronce en Atlanta 1996", "No ha ganado medalla olímpica"], correctaIndex: 0, fuente: "Comité Olímpico Internacional", dificultad: "experto" },
    ],
  },
};
