import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

// Banco real de Cuba (Ruta 2 — Ritmo y Trópico). Mismo estándar que Colombia/Perú/Chile/Brasil.
export const BANCO_CUBA: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Cuba?", opciones: ["Santiago de Cuba", "La Habana", "Camagüey", "Holguín"], correctaIndex: 1, fuente: "REST Countries API", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué mar bordea principalmente a Cuba?", opciones: ["Mar Caribe", "Mar Rojo", "Mar Negro", "Mar Mediterráneo"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué región geográfica se ubica Cuba?", opciones: ["El Caribe", "Europa del Este", "Sudeste Asiático", "África Occidental"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el idioma oficial de Cuba?", opciones: ["Español", "Inglés", "Francés", "Portugués"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "Cuba es la isla más grande de qué archipiélago?", opciones: ["Antillas Mayores", "Antillas Menores", "Islas Galápagos", "Islas Canarias"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Qué estrecho separa a Cuba de Estados Unidos (Florida)?", opciones: ["Estrecho de la Florida", "Canal de la Mancha", "Estrecho de Gibraltar", "Canal de Panamá"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la segunda ciudad más poblada de Cuba?", opciones: ["Camagüey", "Santiago de Cuba", "Holguín", "Santa Clara"], correctaIndex: 1, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cómo se llama la cordillera montañosa más alta de Cuba, en el oriente?", opciones: ["Sierra Maestra", "Cordillera de los Andes", "Sierra Nevada", "Montañas Rocosas"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué archipiélago cubano es un destino turístico famoso por sus playas al norte?", opciones: ["Cayo Coco", "Islas Canarias", "Islas Baleares", "San Andrés"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la moneda oficial de Cuba?", opciones: ["Peso cubano", "Dólar", "Euro", "Real"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué bahía cubana alberga una base naval estadounidense desde 1903?", opciones: ["Bahía de Guantánamo", "Bahía de La Habana", "Bahía de Cochinos", "Bahía de Cienfuegos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuántas provincias tiene Cuba actualmente?", opciones: ["15", "12", "20", "10"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Cuba?", opciones: ["Pico Turquino", "Pico Duarte", "Pico Bolívar", "Pico da Neblina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿En qué provincia se ubica el Pico Turquino?", opciones: ["Santiago de Cuba", "Granma", "Pinar del Río", "Matanzas"], correctaIndex: 1, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué bahía cubana fue escenario de una fallida invasión en 1961?", opciones: ["Bahía de Cochinos", "Bahía de Guantánamo", "Bahía de La Habana", "Bahía de Nipe"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Cuál es la provincia más occidental de Cuba, famosa por el tabaco?", opciones: ["Pinar del Río", "Matanzas", "Villa Clara", "Camagüey"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué valle cubano, Patrimonio de la Humanidad, es célebre por sus plantaciones de tabaco y \"mogotes\"?", opciones: ["Valle de Viñales", "Valle de Trinidad", "Valle de los Ingenios", "Valle Sagrado"], correctaIndex: 0, fuente: "UNESCO", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad cubana fue la primera villa fundada en la isla, en 1511?", opciones: ["Santiago de Cuba", "La Habana", "Baracoa", "Trinidad"], correctaIndex: 2, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es la isla más grande adyacente a Cuba, al sur, antes llamada Isla de Pinos?", opciones: ["Isla de la Juventud", "Cayo Largo", "Isla Margarita", "Isla del Coco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad cubana es conocida como \"la Ciudad de las Columnas\" por su arquitectura colonial?", opciones: ["La Habana", "Cienfuegos", "Camagüey", "Trinidad"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué golfo separa a Cuba de la península de Yucatán, México?", opciones: ["Golfo de México", "Golfo Pérsico", "Golfo de Guinea", "Golfo de Adén"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué ciudad cubana, Patrimonio de la Humanidad, conserva uno de los conjuntos coloniales mejor preservados de América?", opciones: ["Trinidad", "La Habana", "Santiago de Cuba", "Matanzas"], correctaIndex: 0, fuente: "UNESCO", dificultad: "dificil" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿Qué país europeo colonizó Cuba?", opciones: ["España", "Portugal", "Francia", "Inglaterra"], correctaIndex: 0, fuente: "Wikipedia — Historia de Cuba", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año Cuba obtuvo su independencia de España?", opciones: ["1898", "1810", "1900", "1959"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Quién es considerado el héroe nacional de Cuba, poeta y líder independentista?", opciones: ["José Martí", "Simón Bolívar", "Fidel Castro", "Antonio Maceo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué revolución de 1959 cambió el sistema político de Cuba?", opciones: ["Revolución Cubana", "Revolución Mexicana", "Revolución Francesa", "Revolución Industrial"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Quién lideró la Revolución Cubana de 1959?", opciones: ["Fidel Castro", "Che Guevara", "José Martí", "Fulgencio Batista"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿Qué dictador cubano fue derrocado por la Revolución de 1959?", opciones: ["Fulgencio Batista", "Fidel Castro", "Ramón Grau", "Gerardo Machado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año comenzó la Guerra de Independencia liderada por José Martí?", opciones: ["1895", "1868", "1902", "1959"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año murió José Martí en combate?", opciones: ["1895", "1898", "1902", "1868"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué país intervino militarmente en Cuba en 1898, tras el hundimiento del USS Maine?", opciones: ["Estados Unidos", "Francia", "Inglaterra", "Alemania"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año se estableció la República de Cuba tras el fin de la ocupación estadounidense?", opciones: ["1902", "1898", "1910", "1959"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué enmienda daba a EE.UU. derecho a intervenir en Cuba, vigente hasta 1934?", opciones: ["Enmienda Platt", "Enmienda Monroe", "Enmienda Roosevelt", "Tratado de París"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué revolucionario argentino-cubano es un ícono mundial de la Revolución Cubana?", opciones: ["Che Guevara", "José Martí", "Camilo Cienfuegos", "Raúl Castro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿En qué año comenzó la primera Guerra de Independencia cubana, conocida como Guerra de los Diez Años?", opciones: ["1868", "1895", "1898", "1902"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué grito, en 1868, marcó el inicio de la primera guerra de independencia cubana?", opciones: ["Grito de Yara", "Grito de Dolores", "Grito de Baire", "Grito de Asencio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué grito de 1895 marcó el inicio de la segunda guerra de independencia, liderada por Martí?", opciones: ["Grito de Baire", "Grito de Yara", "Grito de Dolores", "Grito de Ipiranga"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué general afrocubano, héroe de las guerras de independencia, es conocido como \"el Titán de Bronce\"?", opciones: ["Antonio Maceo", "Máximo Gómez", "Calixto García", "Ignacio Agramonte"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Quién asumió la presidencia de Cuba tras la renuncia de Fidel Castro en 2008?", opciones: ["Raúl Castro", "Miguel Díaz-Canel", "Osvaldo Dorticós", "Ramón Grau"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año tuvo lugar la Crisis de los Misiles de Cuba?", opciones: ["1962", "1959", "1970", "1980"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué evento de 1961 fue el intento fallido de exiliados cubanos, apoyados por EE.UU., de derrocar a Castro?", opciones: ["Invasión de Bahía de Cochinos", "Crisis de los Misiles", "Éxodo del Mariel", "Operación Mangosta"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué éxodo masivo de cubanos hacia EE.UU. ocurrió en 1980?", opciones: ["Éxodo del Mariel", "Éxodo de los balseros", "Puente aéreo", "Operación Peter Pan"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué presidente cubano gobernó entre 1940 y 1944, autor de la Constitución de 1940?", opciones: ["Fulgencio Batista", "Ramón Grau", "Carlos Prío", "Gerardo Machado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué general dirigió la \"Guerra Chiquita\" cubana entre 1879 y 1880?", opciones: ["Calixto García", "Antonio Maceo", "Máximo Gómez", "José Martí"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué género musical cubano, base de la salsa, mezcla ritmos africanos y españoles?", opciones: ["Son cubano", "Tango", "Flamenco", "Fado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué baile de pareja, con raíces cubanas, es popular mundialmente?", opciones: ["Salsa", "Vals", "Ballet", "Tap"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué religión sincrética afrocubana combina santos católicos con deidades yorubas?", opciones: ["Santería", "Budismo", "Hinduismo", "Sijismo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento de percusión, típico de la música cubana, se toca con las manos?", opciones: ["Bongó", "Violín", "Arpa", "Acordeón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué escritor cubano es autor de \"Paradiso\"?", opciones: ["José Lezama Lima", "Gabriel García Márquez", "Pablo Neruda", "Jorge Luis Borges"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿Qué baile de salón cubano, de pasos cortos, se hizo popular en los años 50?", opciones: ["Chachachá", "Vals", "Tango", "Foxtrot"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué género musical cubano-neoyorquino nació de la fusión del son con jazz en los años 70?", opciones: ["Salsa", "Merengue", "Bachata", "Reggaetón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué poeta cubano de raíces africanas es autor de \"Motivos de son\"?", opciones: ["Nicolás Guillén", "José Martí", "Alejo Carpentier", "José Lezama Lima"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor cubano acuñó el concepto de \"lo real maravilloso\"?", opciones: ["Alejo Carpentier", "Nicolás Guillén", "José Martí", "Reinaldo Arenas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué cigarro es uno de los productos culturales más reconocidos de Cuba?", opciones: ["Habano", "Toscano", "Puro dominicano", "Cigarrillo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué famoso cabaret de La Habana es ícono de la vida nocturna cubana desde 1939?", opciones: ["Tropicana", "Copacabana", "Moulin Rouge", "Crazy Horse"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué deidad yoruba, asociada a los santos católicos en la Santería, representa el mar?", opciones: ["Yemayá", "Changó", "Ochún", "Obatalá"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué escritor cubano exiliado escribió \"Antes que anochezca\"?", opciones: ["Reinaldo Arenas", "Alejo Carpentier", "Guillermo Cabrera Infante", "José Lezama Lima"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué escritor cubano es autor de \"Tres tristes tigres\"?", opciones: ["Guillermo Cabrera Infante", "Reinaldo Arenas", "Nicolás Guillén", "Alejo Carpentier"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué género musical cubano de raíz campesina se toca con guitarra y usa \"décimas\" improvisadas?", opciones: ["Punto guajiro", "Son", "Rumba", "Danzón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué baile de tambores de raíz africana es Patrimonio Cultural Inmaterial de la Humanidad?", opciones: ["Rumba", "Chachachá", "Mambo", "Danzón"], correctaIndex: 0, fuente: "UNESCO", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué género musical cubano, precursor del son, se bailaba en salones del siglo XIX con orquesta típica?", opciones: ["Danzón", "Rumba", "Mambo", "Salsa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué músico cubano es considerado el creador del \"mambo\" en los años 40?", opciones: ["Dámaso Pérez Prado", "Benny Moré", "Compay Segundo", "Arsenio Rodríguez"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué agrupación cubana de músicos veteranos ganó fama mundial en los 90 con un disco homónimo?", opciones: ["Buena Vista Social Club", "Los Van Van", "Irakere", "Orquesta Aragón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué pintor cubano es reconocido por su obra \"La Jungla\" (1943), exhibida en el MoMA?", opciones: ["Wifredo Lam", "Amelia Peláez", "René Portocarrero", "Mario Carreño"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué orisha de la Santería cubana se asocia con el trueno y el fuego?", opciones: ["Changó", "Yemayá", "Ochún", "Obatalá"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué cineasta cubano dirigió \"Fresa y chocolate\" (1993)?", opciones: ["Tomás Gutiérrez Alea", "Fernando Pérez", "Juan Padrón", "Humberto Solás"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Qué plato cubano de arroz y frijoles negros cocinados juntos es muy popular?", opciones: ["Moros y cristianos", "Feijoada", "Gallo pinto", "Casamiento"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué carne desmenuzada y frita es un plato tradicional cubano?", opciones: ["Ropa vieja", "Asado", "Barbacoa", "Churrasco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida a base de ron, menta y limón es originaria de Cuba?", opciones: ["Mojito", "Piña colada", "Margarita", "Daiquiri"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué tubérculo frito, similar a la papa, es común en la comida cubana?", opciones: ["Yuca", "Camote", "Ñame", "Taro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué carne de cerdo asada, marinada con ajo y cítricos, es un plato central cubano?", opciones: ["Lechón asado", "Pollo asado", "Carne a la plancha", "Res al horno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Qué cóctel cubano, hecho con ron, jugo de limón y azúcar, lleva el nombre de un pueblo minero?", opciones: ["Daiquiri", "Mojito", "Cuba libre", "Piña colada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué cóctel cubano combina ron con cola y limón?", opciones: ["Cuba libre", "Mojito", "Daiquiri", "Piña colada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué potaje cubano de frijoles negros es un plato tradicional?", opciones: ["Potaje de frijoles negros", "Sancocho", "Ajiaco", "Mondongo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué cítrico ácido, muy usado en la cocina cubana para marinar carnes, se conoce como \"naranja agria\"?", opciones: ["Naranja agria", "Limón", "Toronja", "Mandarina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato cubano de plátano verde frito y aplastado se sirve como acompañamiento?", opciones: ["Tostones", "Maduros", "Chicharrón", "Casabe"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué sándwich cubano, popular en Miami y La Habana, lleva jamón, cerdo, queso y pepinillo?", opciones: ["Sándwich cubano", "Torta", "Hamburguesa", "Panini"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida caliente y fuerte se sirve tradicionalmente en tacitas pequeñas en Cuba?", opciones: ["Café cubano (cafecito)", "Té", "Chocolate caliente", "Mate"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Qué guiso cubano de frijoles colorados con carne de cerdo es típico de la zona oriental?", opciones: ["Congrí oriental", "Ajiaco", "Ropa vieja", "Fricasé"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué tamal cubano de maíz tierno rallado, dulce y salado, se envuelve en hoja?", opciones: ["Tamal cubano", "Hallaca", "Humita", "Pupusa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué guiso cubano de múltiples carnes y viandas (yuca, malanga, plátano) es plato festivo tradicional?", opciones: ["Ajiaco", "Sancocho", "Mondongo", "Cocido"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué dulce cubano de coco rallado y azúcar, cocido hasta caramelizar, es típico postre?", opciones: ["Coco rallado (cocada)", "Flan", "Natilla", "Arroz con leche"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué pan dulce, relleno de guayaba y queso, es típico de la repostería cubana?", opciones: ["Pastelito de guayaba y queso", "Croissant", "Cannoli", "Empanada dulce"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué tubérculo llamado \"malanga\" es común en los guisos cubanos?", opciones: ["Malanga", "Papa", "Zanahoria", "Remolacha"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿De qué fruta se hace la \"champola\", batido tradicional cubano?", opciones: ["Guanábana", "Mango", "Piña", "Papaya"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué carne, cocida a fuego lento y desmenuzada con salsa de tomate y pimientos, da nombre a la \"ropa vieja\"?", opciones: ["Res", "Cerdo", "Pollo", "Cordero"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué licor cubano de caña, más claro que el ron oscuro, se usa en cócteles como el mojito?", opciones: ["Ron blanco cubano", "Whisky", "Vodka", "Ginebra"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué acompañamiento de plátano verde, frito dos veces y aplastado, es típico de toda la cocina caribeña, incluida Cuba?", opciones: ["Tostones", "Maduros", "Yuca frita", "Casabe"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Qué ave, la más pequeña del mundo, es endémica de Cuba?", opciones: ["Zunzuncito (colibrí abeja)", "Águila", "Tucán", "Flamenco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué reptil, el cocodrilo más pequeño de su tipo, es endémico de Cuba?", opciones: ["Cocodrilo cubano", "Cocodrilo del Nilo", "Caimán negro", "Gavial"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave rosada y grácil es común en los humedales cubanos?", opciones: ["Flamenco", "Pingüino", "Avestruz", "Cisne"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué tipo de ecosistema cubre gran parte de las costas cubanas, con raíces en el agua?", opciones: ["Manglar", "Bosque de coníferas", "Tundra", "Desierto"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero marino, herbívoro y en peligro, habita las aguas cubanas?", opciones: ["Manatí", "Foca", "Morsa", "Nutria marina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional cubano protege una de las mayores extensiones de bosque virgen del Caribe?", opciones: ["Parque Nacional Alejandro de Humboldt", "Parque Nacional Viñales", "Parque Nacional Ciénaga de Zapata", "Parque Ischigualasto"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran humedal cubano, el más extenso del Caribe insular, protege aves y cocodrilos?", opciones: ["Ciénaga de Zapata", "Pantanal", "Everglades", "Camargue"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero pequeño, endémico de Cuba y muy antiguo evolutivamente, es venenoso y raro?", opciones: ["Almiquí (solenodonte cubano)", "Ornitorrinco", "Equidna", "Armadillo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de cocodrilo, casi extinta, es endémica de Cuba?", opciones: ["Cocodrilo cubano", "Cocodrilo americano", "Cocodrilo de agua salada", "Caimán de anteojos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué formación cárstica, colinas redondeadas de piedra caliza, caracteriza el paisaje del Valle de Viñales?", opciones: ["Mogotes", "Fiordos", "Dunas", "Volcanes"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave nacional de Cuba, de plumaje rojo, blanco y azul (colores de la bandera), se llama tocororo?", opciones: ["Tocororo", "Quetzal", "Guacamayo", "Colibrí"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué arrecife de coral, uno de los mejor conservados del Caribe, protege el Parque Nacional Jardines de la Reina?", opciones: ["Jardines de la Reina", "Gran Barrera de Coral", "Arrecife Mesoamericano", "Atolón de Bikini"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Cómo se llama el mamífero insectívoro cubano, uno de los pocos venenosos del mundo, considerado \"fósil viviente\"?", opciones: ["Almiquí", "Equidna", "Ornitorrinco", "Tenrec"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué familia de plantas, con cientos de especies en Cuba, incluye muchas endémicas?", opciones: ["Orquídeas", "Rosáceas", "Cactáceas", "Coníferas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué grupo de reptiles incluye la lagartija más pequeña del mundo, descubierta en Cuba?", opciones: ["Anolis (lagartijas)", "Geckos gigantes", "Iguanas marinas", "Basiliscos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de colibrí, la más pequeña ave del mundo, es endémica de Cuba?", opciones: ["Zunzuncito", "Colibrí gigante", "Colibrí de Ana", "Colibrí rufo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿En qué cordillera cubana se ubica el Parque Nacional Alejandro de Humboldt, Patrimonio de la Humanidad?", opciones: ["Sierra Maestra", "Cordillera de Guaniguanico", "Sierra Cristal / Nipe-Sagua-Baracoa", "Cordillera Escambray"], correctaIndex: 2, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué tipo de bosque, con pinos endémicos, cubre parte de las montañas occidentales de Cuba en Viñales?", opciones: ["Bosque de pinos", "Selva tropical húmeda", "Manglar", "Sabana"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Por qué el cocodrilo cubano está en peligro de desaparecer como especie pura?", opciones: ["Hibridación con el cocodrilo americano", "Caza excesiva únicamente", "Cambio de dieta", "Migración forzada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué isla cubana, al sur del archipiélago, alberga una importante colonia de flamencos?", opciones: ["Cayo Coco", "Isla de la Juventud", "Cayo Guillermo", "Cayo Largo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué grupo de invertebrados marinos, clave para los arrecifes, está muy amenazado en aguas cubanas por el cambio climático?", opciones: ["Corales", "Medusas", "Estrellas de mar", "Pulpos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué proporción aproximada de las costas de Cuba está cubierta por manglares, la mayor del Caribe?", opciones: ["Más de la cuarta parte", "Menos del 5%", "Ninguna", "Solo en el norte"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte más popular en Cuba?", opciones: ["Béisbol", "Fútbol", "Baloncesto", "Rugby"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿En qué deporte de combate Cuba ha ganado numerosas medallas olímpicas?", opciones: ["Boxeo", "Esgrima", "Tiro con arco", "Natación"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué velocista cubano ganó el oro olímpico en 400m y 800m en los años 70?", opciones: ["Alberto Juantorena", "Iván Pedroso", "Javier Sotomayor", "Dayron Robles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿En qué disciplina de salto, con récord mundial histórico, compitió Javier Sotomayor?", opciones: ["Salto de altura", "Salto largo", "Lanzamiento de jabalina", "Salto con garrocha"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿En qué evento deportivo internacional Cuba ha ganado tradicionalmente numerosas medallas de boxeo?", opciones: ["Juegos Olímpicos", "Super Bowl", "Champions League", "Masters de Tenis"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Qué atleta cubano ostentó el récord mundial de salto de altura por más de 20 años?", opciones: ["Javier Sotomayor", "Iván Pedroso", "Alberto Juantorena", "Dayron Robles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué atleta cubano fue campeón olímpico y mundial en salto largo en los años 90?", opciones: ["Iván Pedroso", "Javier Sotomayor", "Alberto Juantorena", "Yoelbi Quesada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿En qué deporte de conjunto ha sido Cuba potencia histórica, con varios oros olímpicos amateur?", opciones: ["Béisbol", "Voleibol", "Baloncesto", "Fútbol"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Cómo se apodaba al equipo cubano de voleibol femenino, tricampeón olímpico en los años 90?", opciones: ["Las Morenas del Caribe", "Las Águilas", "Las Panteras", "Las Guerreras"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿En qué ciudad cubana nació el boxeador Teófilo Stevenson, triple campeón olímpico de peso pesado?", opciones: ["Las Tunas", "La Habana", "Santiago de Cuba", "Camagüey"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Cuántas medallas de oro olímpicas consecutivas ganó Teófilo Stevenson en peso pesado (1972-1980)?", opciones: ["3", "2", "4", "1"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué vallista cubano ganó el oro olímpico en 110m con vallas en Beijing 2008?", opciones: ["Dayron Robles", "Iván Pedroso", "Javier Sotomayor", "Alberto Juantorena"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿Qué boxeador cubano igualó el récord de 3 oros olímpicos consecutivos de Stevenson, en los 90-2000?", opciones: ["Félix Savón", "Guillermo Rigondeaux", "Teófilo Stevenson", "Mario Kindelán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué Juegos Olímpicos Alberto Juantorena ganó el histórico doblete de 400m y 800m?", opciones: ["Montreal 1976", "Múnich 1972", "Moscú 1980", "Los Ángeles 1984"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad cubana es cuna del béisbol nacional, sede del histórico Estadio Latinoamericano?", opciones: ["La Habana", "Santiago de Cuba", "Matanzas", "Camagüey"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué liga de béisbol doméstica cubana reúne a los equipos provinciales del país?", opciones: ["Serie Nacional de Béisbol", "Grandes Ligas", "Liga Mexicana", "Serie del Caribe"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué deporte de lucha olímpica ha sido Cuba tradicionalmente competitiva a nivel internacional?", opciones: ["Lucha libre", "Esgrima", "Tiro", "Vela"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué vallista cubano ganó el oro en 110m vallas en los Juegos Olímpicos de Sídney 2000?", opciones: ["Anier García", "Dayron Robles", "Javier Sotomayor", "Alberto Juantorena"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad cubana albergó los Juegos Panamericanos de 1991?", opciones: ["La Habana", "Santiago de Cuba", "Varadero", "Cienfuegos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué año Javier Sotomayor estableció su récord mundial de salto de altura (2.45m), aún vigente?", opciones: ["1993", "1988", "2000", "2010"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Cómo se llama el estadio de béisbol más importante de La Habana?", opciones: ["Estadio Latinoamericano", "Estadio Nacional", "Coliseo de la Ciudad", "Parque Central"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué disciplina atlética ha destacado tradicionalmente la provincia cubana de Santiago de Cuba, cuna de varios velocistas?", opciones: ["Atletismo (velocidad y saltos)", "Curling", "Esquí", "Rugby"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
};
