import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

// Banco real de Canadá (Ruta 3 — Ecos del Norte). Mismo estándar que el resto de países.
export const BANCO_CANADA: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Canadá?", opciones: ["Toronto", "Ottawa", "Vancouver", "Montreal"], correctaIndex: 1, fuente: "REST Countries API", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Canadá por el oeste?", opciones: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Canadá por el este?", opciones: ["Atlántico", "Pacífico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuáles son los dos idiomas oficiales de Canadá?", opciones: ["Inglés y francés", "Solo inglés", "Solo francés", "Inglés y español"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué continente está ubicado Canadá?", opciones: ["América del Norte", "América del Sur", "Europa", "Asia"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Con qué único país limita Canadá por tierra?", opciones: ["Estados Unidos", "México", "Rusia", "Dinamarca (Groenlandia)"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la ciudad más poblada de Canadá?", opciones: ["Toronto", "Montreal", "Vancouver", "Ottawa"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la provincia más poblada de Canadá?", opciones: ["Ontario", "Quebec", "Columbia Británica", "Alberta"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué provincia canadiense es mayoritariamente francófona?", opciones: ["Quebec", "Ontario", "Alberta", "Manitoba"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la moneda oficial de Canadá?", opciones: ["Dólar canadiense", "Dólar estadounidense", "Libra", "Euro"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuántas provincias tiene Canadá, sin contar los territorios?", opciones: ["10", "8", "12", "13"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuántos territorios (no provincias) tiene Canadá en su norte?", opciones: ["3", "1", "2", "5"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Canadá?", opciones: ["Monte Logan", "Denali", "Monte Robson", "Monte Waddington"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿En qué territorio se ubica el Monte Logan?", opciones: ["Yukón", "Columbia Británica", "Territorios del Noroeste", "Alberta"], correctaIndex: 0, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué bahía enorme, en el centro-norte de Canadá, lleva el nombre de un explorador inglés?", opciones: ["Bahía de Hudson", "Bahía de Fundy", "Bahía de Baffin", "Bahía James"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué cataratas, compartidas con Estados Unidos, son un ícono turístico entre Ontario y Nueva York?", opciones: ["Cataratas del Niágara", "Cataratas Victoria", "Cataratas del Iguazú", "Cataratas de Yosemite"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera atraviesa el oeste de Canadá?", opciones: ["Montañas Rocosas", "Los Andes", "Alpes", "Montes Apalaches"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es el territorio o provincia más grande de Canadá por área?", opciones: ["Nunavut", "Quebec", "Ontario", "Territorios del Noroeste"], correctaIndex: 0, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué isla, la más grande de Canadá, se ubica en el Ártico canadiense?", opciones: ["Isla de Baffin", "Isla de Vancouver", "Isla del Príncipe Eduardo", "Isla de Terranova"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué bahía, con las mareas más altas del mundo, se ubica entre Nueva Escocia y Nuevo Brunswick?", opciones: ["Bahía de Fundy", "Bahía de Hudson", "Bahía James", "Bahía de Baffin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué provincia canadiense, la más pequeña por área, se ubica en el golfo de San Lorenzo?", opciones: ["Isla del Príncipe Eduardo", "Nueva Escocia", "Nuevo Brunswick", "Terranova y Labrador"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Cuántos husos horarios tiene Canadá, de este a oeste?", opciones: ["6", "3", "9", "1"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿De qué dos países europeos recibió Canadá su herencia colonial principal?", opciones: ["Francia e Inglaterra", "España y Portugal", "Países Bajos y Alemania", "Italia y Francia"], correctaIndex: 0, fuente: "Wikipedia — Historia de Canadá", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año Canadá se convirtió en una confederación (dominio autónomo)?", opciones: ["1867", "1776", "1900", "1931"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué tipo de gobierno tiene Canadá actualmente?", opciones: ["Monarquía constitucional parlamentaria", "República presidencialista", "Dictadura", "Imperio"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué corona europea es (formalmente) también la del jefe de estado de Canadá?", opciones: ["La Corona británica", "La Corona española", "La Corona francesa", "La Corona neerlandesa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué explorador francés es considerado el fundador de Quebec en 1608?", opciones: ["Samuel de Champlain", "Jacques Cartier", "Henry Hudson", "John Cabot"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿Qué explorador francés fue el primero en cartografiar el río San Lorenzo en el siglo XVI?", opciones: ["Jacques Cartier", "Samuel de Champlain", "Henry Hudson", "John Cabot"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué guerra (1754-63) enfrentó a Francia e Inglaterra por el control de Norteamérica, incluida Canadá?", opciones: ["Guerra Franco-India (Guerra de los Siete Años)", "Guerra de Independencia", "Guerra de 1812", "Guerra Civil"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué tratado de 1763 cedió Nueva Francia (incluido Quebec) a Gran Bretaña?", opciones: ["Tratado de París", "Tratado de Utrecht", "Tratado de Versalles", "Tratado de Tordesillas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué guerra de 1812-1815 las colonias británicas de Canadá resistieron una invasión de EE.UU.?", opciones: ["Guerra de 1812", "Guerra Franco-India", "Primera Guerra Mundial", "Guerra de los Bóeres"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué ley británica de 1867 estableció la Confederación Canadiense?", opciones: ["Ley de la América del Norte Británica (BNA Act)", "Ley de Independencia", "Estatuto de Westminster", "Acta de Quebec"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué estatuto de 1931 le dio a Canadá plena autonomía legislativa del Reino Unido?", opciones: ["Estatuto de Westminster", "Ley BNA", "Acta de Quebec", "Tratado de París"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué año Canadá \"repatrió\" completamente su Constitución del Reino Unido?", opciones: ["1982", "1931", "1867", "1960"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿Qué primer ministro canadiense es considerado el \"padre de la Confederación\" y primer PM del país?", opciones: ["John A. Macdonald", "Wilfrid Laurier", "William Lyon Mackenzie King", "Pierre Trudeau"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué primer ministro canadiense, de origen francófono, gobernó a inicios del siglo XX promoviendo la unidad nacional?", opciones: ["Wilfrid Laurier", "John A. Macdonald", "Mackenzie King", "Louis St. Laurent"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué primer ministro canadiense gobernó por más tiempo acumulado en la historia del país, con interrupciones en el siglo XX?", opciones: ["William Lyon Mackenzie King", "Pierre Trudeau", "John A. Macdonald", "Wilfrid Laurier"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué movimiento político en Quebec ha buscado la independencia de la provincia respecto a Canadá?", opciones: ["Movimiento soberanista quebequense", "Movimiento de los territorios", "Partido Conservador", "Confederación"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿En qué año se realizó el primer referéndum de independencia de Quebec, que perdió la opción soberanista?", opciones: ["1980", "1995", "1970", "1960"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿En qué año se realizó el segundo referéndum de independencia de Quebec, con resultado muy ajustado?", opciones: ["1995", "1980", "2000", "1990"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué primer ministro canadiense, padre de un PM posterior, impulsó la repatriación constitucional de 1982?", opciones: ["Pierre Trudeau", "Brian Mulroney", "Jean Chrétien", "Stephen Harper"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué grupo mestizo canadiense, liderado por Louis Riel, se rebeló en el siglo XIX por sus tierras?", opciones: ["Métis", "Inuit", "Iroqueses", "Cree"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué líder métis lideró las rebeliones de Red River y del Noroeste en el siglo XIX?", opciones: ["Louis Riel", "John A. Macdonald", "Wilfrid Laurier", "George Brown"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué política de asimilación forzada, con internados para niños indígenas, fue reconocida oficialmente por Canadá como un grave daño histórico?", opciones: ["Sistema de internados indígenas (residential schools)", "Ley de Inmigración", "Ley de Tierras", "Acta de Confederación"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué deporte sobre hielo es considerado el deporte nacional de invierno de Canadá?", opciones: ["Hockey sobre hielo", "Fútbol", "Béisbol", "Rugby"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué símbolo natural, una hoja de árbol, aparece en el centro de la bandera de Canadá?", opciones: ["Hoja de arce", "Hoja de roble", "Hoja de olivo", "Hoja de laurel"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué bebida dulce, extraída de un árbol típico de Canadá, se usa para desayunos (panqueques)?", opciones: ["Jarabe de arce", "Miel de abeja", "Melaza", "Jarabe de maíz"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué deporte de origen indígena canadiense, jugado con un palo curvo, es considerado deporte de verano nacional?", opciones: ["Lacrosse", "Rugby", "Críquet", "Softbol"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Cuáles son los dos idiomas oficiales de Canadá?", opciones: ["Inglés y francés", "Solo inglés", "Inglés y español", "Francés y alemán"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿Qué cantautora canadiense, ganadora de múltiples Grammys, es autora de \"A Case of You\"?", opciones: ["Joni Mitchell", "Celine Dion", "Alanis Morissette", "Shania Twain"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué cantante canadiense de Quebec es una de las voces más vendidas de la música pop mundial (años 90-2000)?", opciones: ["Céline Dion", "Joni Mitchell", "Alanis Morissette", "Avril Lavigne"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué cantante de Toronto, de origen caribeño, es una de las figuras del hip-hop más exitosas del mundo en los 2010s?", opciones: ["Drake", "The Weeknd", "Justin Bieber", "Michael Bublé"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritora canadiense ganó el Premio Nobel de Literatura en 2013?", opciones: ["Alice Munro", "Margaret Atwood", "Anne Carson", "Yann Martel"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritora canadiense es autora de \"El cuento de la criada\"?", opciones: ["Margaret Atwood", "Alice Munro", "Anne Carson", "Lucy Maud Montgomery"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritora canadiense creó el personaje de \"Ana, la de Tejas Verdes\"?", opciones: ["Lucy Maud Montgomery", "Margaret Atwood", "Alice Munro", "Yann Martel"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué provincia canadiense es escenario de la novela \"Ana, la de Tejas Verdes\"?", opciones: ["Isla del Príncipe Eduardo", "Quebec", "Ontario", "Nueva Escocia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué escritor canadiense es autor de \"Vida de Pi\"?", opciones: ["Yann Martel", "Margaret Atwood", "Alice Munro", "Michael Ondaatje"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué escritor canadiense, nacido en Sri Lanka, escribió \"El paciente inglés\"?", opciones: ["Michael Ondaatje", "Yann Martel", "Margaret Atwood", "Robertson Davies"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué pintor canadiense, asociado al Grupo de los Siete, es célebre por sus paisajes de bosques y lagos?", opciones: ["Tom Thomson", "Emily Carr", "Norval Morrisseau", "Cornelius Krieghoff"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué pintora canadiense es célebre por retratar los bosques y culturas indígenas de la costa oeste?", opciones: ["Emily Carr", "Tom Thomson", "Norval Morrisseau", "Alex Colville"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué artista indígena canadiense (Ojibwe) es reconocido como pionero del arte woodland contemporáneo?", opciones: ["Norval Morrisseau", "Tom Thomson", "Emily Carr", "Bill Reid"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué artista de la costa noroeste (Haida) es célebre por su escultura \"El espíritu de Haida Gwaii\"?", opciones: ["Bill Reid", "Norval Morrisseau", "Emily Carr", "Tom Thomson"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué colectivo de pintores canadienses de inicios del siglo XX es célebre por representar el paisaje salvaje del país?", opciones: ["Grupo de los Siete", "Impresionistas canadienses", "Grupo de Montreal", "Escuela de Quebec"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué festival de cine, celebrado anualmente en Toronto, es uno de los más importantes del mundo?", opciones: ["TIFF (Festival Internacional de Cine de Toronto)", "Festival de Cannes", "Sundance", "Berlinale"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué comediante y actor canadiense, de Ottawa, se hizo famoso en Hollywood en los 90 (Máscara, Ace Ventura)?", opciones: ["Jim Carrey", "Mike Myers", "Seth Rogen", "Ryan Reynolds"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué actor canadiense de Vancouver protagonizó \"Deadpool\" y es conocido por su humor irreverente?", opciones: ["Ryan Reynolds", "Jim Carrey", "Mike Myers", "Seth Rogen"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Qué producto dulce, extraído de la savia de un árbol, es un ícono nacional canadiense?", opciones: ["Jarabe de arce", "Miel", "Melaza", "Jarabe de maíz"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato canadiense de papas fritas, queso y salsa gravy es originario de Quebec?", opciones: ["Poutine", "Fish and chips", "Papas rellenas", "Nachos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué carne ahumada, similar al pastrami, es un ícono gastronómico de Montreal?", opciones: ["Carne ahumada de Montreal", "Jamón serrano", "Pastrami de Nueva York", "Tocino canadiense"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué tipo de tocino, más magro que el estadounidense, se conoce como \"tocino canadiense\"?", opciones: ["Tocino canadiense (peameal bacon)", "Panceta", "Jamón", "Chorizo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué pastel dulce y pegajoso, hecho con jarabe de arce o azúcar, es un postre típico canadiense?", opciones: ["Tarta de azúcar (butter tart)", "Pastel de manzana", "Cheesecake", "Brownie"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿En qué provincia canadiense se originó la poutine?", opciones: ["Quebec", "Ontario", "Columbia Británica", "Alberta"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué marisco, especialmente valorado, es un producto icónico de la costa atlántica canadiense (Nueva Escocia)?", opciones: ["Langosta", "Camarón", "Pulpo", "Calamar"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué pescado, muy consumido en Canadá por su costa en ambos océanos, es base de muchos platos?", opciones: ["Salmón", "Atún", "Bacalao", "Tilapia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué grano, base de la producción agrícola de las praderas canadienses, es clave en la economía?", opciones: ["Trigo", "Arroz", "Maíz", "Cebada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida caliente, muy consumida en el invierno canadiense, suele acompañarse de donas en cadenas populares?", opciones: ["Café", "Té", "Chocolate caliente", "Mate"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué cadena de café y donas, fundada por un jugador de hockey, es un ícono de la cultura cotidiana canadiense?", opciones: ["Tim Hortons", "Starbucks", "Dunkin'", "McDonald's"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué provincia canadiense es el mayor productor mundial de jarabe de arce?", opciones: ["Quebec", "Ontario", "Nueva Escocia", "Nuevo Brunswick"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Qué plato de Terranova, hecho con lengua de bacalao frita, es una rareza gastronómica local?", opciones: ["Lenguas de bacalao fritas (cod tongues)", "Fish and chips", "Bacalao a la vizcaína", "Ceviche de bacalao"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué pan simple y frito, típico de comunidades del norte de Canadá, se llama \"bannock\"?", opciones: ["Bannock", "Baguette", "Pita", "Naan"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué queso fresco y chirriante, clave para una poutine auténtica, se usa en Quebec?", opciones: ["Cheese curds (queso en grano)", "Queso cheddar madurado", "Queso brie", "Queso azul"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué postre canadiense de nueces y jarabe de arce en una masa quebradiza es típico de Ontario?", opciones: ["Butter tart", "Pecan pie", "Apple pie", "Cheesecake"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué sopa de guisantes amarillos, de tradición francocanadiense, es típica de Quebec?", opciones: ["Sopa de guisantes (pea soup)", "Sopa de lentejas", "Sopa de frijoles negros", "Minestrone"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué pastel de carne, típico de la Navidad en Quebec, se llama \"tourtière\"?", opciones: ["Tourtière", "Empanada", "Pastel de pollo", "Shepherd's pie"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta silvestre, muy usada en mermeladas y postres del este de Canadá, crece en pantanos?", opciones: ["Arándano rojo (cranberry)", "Fresa", "Mora", "Arándano azul"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué grado de jarabe de arce, más oscuro y de sabor intenso, se usa comúnmente para cocinar?", opciones: ["Grado ámbar oscuro", "Grado dorado claro", "Grado extra claro", "Grado A únicamente"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué provincia canadiense es reconocida por su producción de vino de hielo (ice wine)?", opciones: ["Ontario", "Quebec", "Manitoba", "Saskatchewan"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué tipo de vino dulce, hecho con uvas congeladas en la vid, es una especialidad canadiense de exportación?", opciones: ["Vino de hielo (icewine)", "Vino espumoso", "Vino tinto reserva", "Vino rosado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Qué animal, símbolo nacional de Canadá, construye represas con troncos y ramas?", opciones: ["Castor", "Alce", "Oso", "Lobo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran mamífero con cuernos, símbolo de la fauna canadiense, habita bosques del norte?", opciones: ["Alce", "Ciervo", "Bisonte", "Reno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué oso blanco, símbolo del Ártico canadiense, está amenazado por el cambio climático?", opciones: ["Oso polar", "Oso pardo", "Oso negro", "Oso panda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave rapaz, la misma que es símbolo de EE.UU., también habita ampliamente Canadá?", opciones: ["Águila calva", "Águila real", "Cóndor", "Halcón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué fenómeno luminoso natural, visible en cielos del norte de Canadá, se llama aurora boreal?", opciones: ["Aurora boreal", "Arcoíris", "Eclipse", "Cometa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional canadiense, el más antiguo del país (1885), se ubica en las Montañas Rocosas de Alberta?", opciones: ["Banff", "Jasper", "Yoho", "Glacier"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran mamífero cornudo, similar al búfalo, es símbolo de las llanuras canadienses y casi se extinguió?", opciones: ["Bisonte", "Alce", "Reno", "Toro salvaje"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ballena del Ártico canadiense tiene un largo colmillo espiralado?", opciones: ["Narval", "Beluga", "Orca", "Cachalote"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ballena blanca, sin aleta dorsal, habita aguas árticas y subárticas de Canadá?", opciones: ["Beluga", "Narval", "Orca", "Cachalote"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran felino, el más grande de Norteamérica, habita algunas zonas remotas de Canadá?", opciones: ["Puma", "Jaguar", "Guepardo", "Lince"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave migratoria, símbolo del otoño canadiense, vuela en formación de \"V\" hacia el sur?", opciones: ["Ganso canadiense", "Águila calva", "Pato", "Cisne"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué campo de hielo, uno de los más grandes accesibles de Norteamérica, se ubica en Alberta?", opciones: ["Campo de hielo Columbia", "Glaciar Perito Moreno", "Casquete de Groenlandia", "Glaciar de Malaspina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Qué parque provincial canadiense, Patrimonio de la Humanidad, protege fósiles de dinosaurios en Alberta?", opciones: ["Parque Provincial Dinosaur", "Parque Banff", "Parque Jasper", "Parque Yoho"], correctaIndex: 0, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de lobo, la más grande, habita bosques y tundras de Canadá?", opciones: ["Lobo gris (lobo timber)", "Lobo rojo", "Chacal dorado", "Coyote"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero ártico, con cornamenta y pastoreado por comunidades inuit, es clave en la tundra canadiense?", opciones: ["Caribú (reno)", "Alce", "Bisonte", "Buey almizclero"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué bovino peludo, adaptado al frío extremo del Ártico, habita el norte de Canadá?", opciones: ["Buey almizclero", "Bisonte", "Yak", "Búfalo de agua"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque provincial de Columbia Británica protege una de las mayores concentraciones de osos pardos para observación?", opciones: ["Parque Provincial Khutzeymateen", "Parque Banff", "Parque Jasper", "Parque Algonquin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué bosque, el bioma más extenso de Canadá, cubre gran parte del centro y norte del país?", opciones: ["Bosque boreal (taiga)", "Selva tropical", "Sabana", "Desierto"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué fenómeno de marea, el más extremo del mundo (hasta 16 metros), ocurre en la Bahía de Fundy?", opciones: ["Mareas extremas", "Tsunamis frecuentes", "Corrientes cálidas", "Icebergs permanentes"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de salmón, clave en los ríos del Pacífico canadiense, realiza una migración masiva para desovar?", opciones: ["Salmón del Pacífico", "Salmón del Atlántico únicamente", "Trucha arcoíris", "Bacalao"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué búho, común en el Ártico canadiense, es blanco y caza durante el día?", opciones: ["Búho nival", "Búho real", "Lechuza común", "Búho manchado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional, en la frontera de Alberta y Columbia Británica, protege parte de las Montañas Rocosas y glaciares?", opciones: ["Jasper", "Everglades", "Yellowstone", "Yosemite"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte de invierno más popular y considerado nacional en Canadá?", opciones: ["Hockey sobre hielo", "Fútbol", "Béisbol", "Baloncesto"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué liga profesional de hockey sobre hielo, con equipos de EE.UU. y Canadá, corona al campeón con la Copa Stanley?", opciones: ["NHL", "NBA", "NFL", "MLB"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué velocista canadiense ganó (y luego perdió por dopaje) el oro olímpico de 100m en Seúl 1988?", opciones: ["Ben Johnson", "Donovan Bailey", "Andre De Grasse", "Bruny Surin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué deporte de verano de origen indígena es también popular en Canadá, jugado con un palo curvo?", opciones: ["Lacrosse", "Rugby", "Críquet", "Softbol"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué tenista canadiense masculino alcanzó el top mundial y llegó a finales de Grand Slam en los 2010s?", opciones: ["Milos Raonic", "Denis Shapovalov", "Félix Auger-Aliassime", "Vasek Pospisil"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Qué velocista canadiense ganó el oro olímpico de 100m en Atlanta 1996?", opciones: ["Donovan Bailey", "Ben Johnson", "Andre De Grasse", "Bruny Surin"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué velocista canadiense ganó múltiples medallas en los 100m y 200m en Río 2016 y Tokio 2020?", opciones: ["Andre De Grasse", "Donovan Bailey", "Ben Johnson", "Aaron Brown"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué jugador canadiense de hockey, considerado uno de los mejores de la historia (\"The Great One\"), jugó para los Edmonton Oilers?", opciones: ["Wayne Gretzky", "Mario Lemieux", "Sidney Crosby", "Bobby Orr"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué jugador canadiense de hockey, capitán de los Pittsburgh Penguins, es multicampeón de la Copa Stanley y medallista olímpico?", opciones: ["Sidney Crosby", "Wayne Gretzky", "Connor McDavid", "Mario Lemieux"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué tenista canadiense femenina alcanzó una final de Grand Slam en el US Open 2019?", opciones: ["Bianca Andreescu", "Eugenie Bouchard", "Leylah Fernandez", "Milos Raonic"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué baloncestista canadiense fue elegido número 1 del draft de la NBA en 2013?", opciones: ["Anthony Bennett", "Steve Nash", "Andrew Wiggins", "Jamal Murray"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué exjugador de baloncesto canadiense, base, ganó el premio MVP de la NBA en dos ocasiones (2005, 2006)?", opciones: ["Steve Nash", "Anthony Bennett", "Andrew Wiggins", "Jamal Murray"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿Cuántas Copas Stanley ganó Wayne Gretzky con los Edmonton Oilers en los años 80?", opciones: ["4", "2", "6", "1"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué récord histórico ostenta Wayne Gretzky en la NHL, considerado imbatible por muchos?", opciones: ["Máximo goleador histórico de la NHL", "Más partidos jugados", "Más años activo", "Más equipos representados"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué ciudad canadiense se celebraron los Juegos Olímpicos de Invierno de 2010?", opciones: ["Vancouver", "Calgary", "Montreal", "Toronto"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué ciudad canadiense se celebraron los Juegos Olímpicos de Invierno de 1988?", opciones: ["Calgary", "Vancouver", "Montreal", "Quebec"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué ciudad canadiense se celebraron los Juegos Olímpicos de Verano de 1976?", opciones: ["Montreal", "Toronto", "Vancouver", "Calgary"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué jugador de hockey canadiense, defensa revolucionario, ganó el MVP de la NHL en los años 60-70 con los Boston Bruins?", opciones: ["Bobby Orr", "Wayne Gretzky", "Mario Lemieux", "Gordie Howe"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué jugador canadiense, apodado \"Mr. Hockey\", jugó en la NHL por más de 25 años entre los años 40 y 70?", opciones: ["Gordie Howe", "Bobby Orr", "Wayne Gretzky", "Mario Lemieux"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué equipo canadiense de la NHL es el más laureado históricamente, con más Copas Stanley?", opciones: ["Montreal Canadiens", "Toronto Maple Leafs", "Edmonton Oilers", "Calgary Flames"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué corredor canadiense con una sola pierna protagonizó la \"Marathon of Hope\" en 1980 para investigación del cáncer?", opciones: ["Terry Fox", "Rick Hansen", "Steve Nash", "Donovan Bailey"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué joven jugador canadiense de hockey de los Edmonton Oilers ha sido comparado con Gretzky en la década de 2020?", opciones: ["Connor McDavid", "Sidney Crosby", "Auston Matthews", "Nathan MacKinnon"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
};
