import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

// Banco real de México (Ruta 3 — Ecos del Norte). Mismo estándar que el resto de países.
export const BANCO_MEXICO: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de México?", opciones: ["Ciudad de México", "Guadalajara", "Monterrey", "Cancún"], correctaIndex: 0, fuente: "REST Countries API", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a México por el oeste?", opciones: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué golfo bordea a México por el este?", opciones: ["Golfo de México", "Golfo Pérsico", "Golfo de Guinea", "Golfo de Adén"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el idioma oficial de México?", opciones: ["Español", "Inglés", "Francés", "Portugués"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué región está ubicado México?", opciones: ["América del Norte", "América del Sur", "El Caribe", "Europa"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Con cuántos países limita México?", opciones: ["3", "2", "4", "1"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la ciudad más poblada de México?", opciones: ["Ciudad de México", "Guadalajara", "Monterrey", "Puebla"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera atraviesa el occidente de México?", opciones: ["Sierra Madre Occidental", "Cordillera de los Andes", "Montañas Rocosas", "Alpes"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué península mexicana separa el Golfo de México del Mar Caribe?", opciones: ["Península de Yucatán", "Península de Baja California", "Península de Nicoya", "Península Ibérica"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la moneda oficial de México?", opciones: ["Peso mexicano", "Dólar", "Quetzal", "Colón"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué país centroamericano limita a México por el sureste?", opciones: ["Guatemala", "Honduras", "El Salvador", "Panamá"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuántos estados tiene México, sin contar la Ciudad de México?", opciones: ["31", "30", "32", "28"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de México?", opciones: ["Pico de Orizaba", "Popocatépetl", "Iztaccíhuatl", "Nevado de Toluca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué península mexicana, larga y angosta, se ubica en el noroeste del país?", opciones: ["Baja California", "Yucatán", "Florida", "Alaska"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué desierto cubre gran parte del norte de México?", opciones: ["Desierto de Sonora", "Desierto del Sahara", "Desierto de Atacama", "Desierto de Gobi"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué volcán activo, cercano a Ciudad de México, es uno de los más monitoreados del país?", opciones: ["Popocatépetl", "Pico de Orizaba", "Iztaccíhuatl", "Paricutín"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué sistema arrecifal, uno de los más grandes del mundo, se ubica frente a Quintana Roo?", opciones: ["Sistema Arrecifal Mesoamericano", "Gran Barrera de Coral", "Jardines de la Reina", "Arrecife de Belice (parte del anterior)"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es el lago más grande de México?", opciones: ["Lago de Chapala", "Lago Titicaca", "Lago de Nicaragua", "Lago Atitlán"], correctaIndex: 0, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué río forma parte de la frontera entre México y Estados Unidos?", opciones: ["Río Bravo (Grande)", "Río Colorado", "Río Usumacinta", "Río Balsas"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué estado mexicano es el más grande por área?", opciones: ["Chihuahua", "Sonora", "Coahuila", "Durango"], correctaIndex: 0, fuente: "Wikidata", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál es la segunda ciudad más poblada de México?", opciones: ["Guadalajara", "Monterrey", "Puebla", "Tijuana"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué golfo separa la península de Baja California del resto de México?", opciones: ["Golfo de California (Mar de Cortés)", "Golfo de México", "Golfo Pérsico", "Golfo de Guinea"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿Qué país colonizó México?", opciones: ["España", "Portugal", "Francia", "Inglaterra"], correctaIndex: 0, fuente: "Wikipedia — Historia de México", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año México se independizó de España?", opciones: ["1821", "1810", "1910", "1900"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué cura inició el movimiento de independencia mexicana en 1810?", opciones: ["Miguel Hidalgo", "Benito Juárez", "Porfirio Díaz", "Emiliano Zapata"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué imperio precolombino dominó el centro de México antes de la conquista española?", opciones: ["Imperio Azteca", "Imperio Inca", "Imperio Maya", "Imperio Chibcha"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Qué revolución de 1910 transformó política y socialmente a México?", opciones: ["Revolución Mexicana", "Revolución Cubana", "Revolución Francesa", "Revolución Rusa"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿Qué conquistador español lideró la caída del Imperio Azteca en 1521?", opciones: ["Hernán Cortés", "Francisco Pizarro", "Pedro de Alvarado", "Diego de Almagro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Cómo se llamaba la capital azteca conquistada por los españoles?", opciones: ["Tenochtitlan", "Tikal", "Chichén Itzá", "Teotihuacán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué presidente mexicano de origen indígena es reconocido por las Leyes de Reforma?", opciones: ["Benito Juárez", "Porfirio Díaz", "Antonio López de Santa Anna", "Lázaro Cárdenas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué dictador gobernó México por más de 30 años antes de la Revolución de 1910?", opciones: ["Porfirio Díaz", "Benito Juárez", "Victoriano Huerta", "Plutarco Elías Calles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué líder revolucionario del sur de México es símbolo de la lucha agraria, con la consigna \"Tierra y Libertad\"?", opciones: ["Emiliano Zapata", "Pancho Villa", "Francisco Madero", "Venustiano Carranza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué revolucionario del norte de México lideró la División del Norte durante la Revolución?", opciones: ["Pancho Villa", "Emiliano Zapata", "Álvaro Obregón", "Venustiano Carranza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué guerra (1846-48) México perdió más de la mitad de su territorio ante Estados Unidos?", opciones: ["Guerra México-Estados Unidos", "Guerra de los Pasteles", "Guerra de Independencia", "Guerra Cristera"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿Qué tratado de 1848 puso fin a la guerra entre México y Estados Unidos?", opciones: ["Tratado de Guadalupe Hidalgo", "Tratado de Versalles", "Tratado de Tordesillas", "Tratado de París"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué presidente mexicano nacionalizó la industria petrolera en 1938?", opciones: ["Lázaro Cárdenas", "Benito Juárez", "Porfirio Díaz", "Plutarco Elías Calles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué emperador austríaco fue impuesto como monarca de México por Francia entre 1864 y 1867?", opciones: ["Maximiliano de Habsburgo", "Napoleón III", "Carlos V", "Fernando VII"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué conflicto religioso mexicano (1926-1929) enfrentó al gobierno con católicos armados?", opciones: ["Guerra Cristera", "Revolución Mexicana", "Guerra de Reforma", "Guerra de los Pasteles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué guerra de 1838 entre México y Francia se originó por reclamos de un pastelero francés?", opciones: ["Guerra de los Pasteles", "Guerra de Texas", "Guerra de Reforma", "Guerra Cristera"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué estado mexicano se independizó como república en 1836 antes de anexarse a EE.UU.?", opciones: ["Texas", "California", "Nuevo México", "Arizona"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué partido político gobernó México casi ininterrumpidamente desde 1929 hasta el 2000?", opciones: ["PRI (Partido Revolucionario Institucional)", "PAN", "PRD", "MORENA"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué masacre estudiantil ocurrió en la Plaza de las Tres Culturas de Tlatelolco en 1968?", opciones: ["Masacre de Tlatelolco", "Masacre de Acteal", "Masacre de Aguas Blancas", "Masacre de El Bosque"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿En qué año obtuvo México su independencia definitiva, tras la firma del Acta de Independencia?", opciones: ["1821", "1810", "1836", "1917"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué constitución mexicana, promulgada tras la Revolución, sigue vigente hasta hoy (con reformas)?", opciones: ["Constitución de 1917", "Constitución de 1857", "Constitución de 1824", "Constitución de 1836"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Qué festividad mexicana, Patrimonio de la Humanidad, honra a los difuntos cada 1 y 2 de noviembre?", opciones: ["Día de Muertos", "Día de la Independencia", "Semana Santa", "Carnaval"], correctaIndex: 0, fuente: "UNESCO", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué género musical mexicano, con trompetas y violines, es tocado por grupos vestidos de charro?", opciones: ["Mariachi", "Salsa", "Tango", "Reggae"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué bebida alcohólica mexicana se destila del agave azul?", opciones: ["Tequila", "Ron", "Vodka", "Whisky"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué sombrero mexicano, de ala ancha, es un ícono cultural del país?", opciones: ["Sombrero charro", "Sombrero vueltiao", "Panamá", "Fedora"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué pintora mexicana, célebre por sus autorretratos, es una de las artistas más reconocidas del siglo XX?", opciones: ["Frida Kahlo", "Diego Rivera", "Remedios Varo", "María Izquierdo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿Qué muralista mexicano, esposo de Frida Kahlo, pintó grandes obras históricas en edificios públicos?", opciones: ["Diego Rivera", "David Alfaro Siqueiros", "José Clemente Orozco", "Rufino Tamayo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor mexicano ganó el Premio Nobel de Literatura en 1990?", opciones: ["Octavio Paz", "Carlos Fuentes", "Juan Rulfo", "Mariano Azuela"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor mexicano es autor de \"Pedro Páramo\"?", opciones: ["Juan Rulfo", "Octavio Paz", "Carlos Fuentes", "Elena Poniatowska"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué figura artesanal mexicana, colorida y fantástica, se talla en madera en Oaxaca?", opciones: ["Alebrije", "Molas", "Huipil", "Piñata"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué traje tradicional femenino mexicano, bordado y colorido, es típico de Oaxaca y otras regiones?", opciones: ["Huipil", "Sari", "Kimono", "Dirndl"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué género musical folclórico de Veracruz, con arpa y jarana, dio origen a \"La Bamba\"?", opciones: ["Son jarocho", "Mariachi", "Norteño", "Ranchera"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué baile nacional mexicano, ejecutado en pareja con sombrero, es reconocido internacionalmente como danza folclórica típica?", opciones: ["Jarabe Tapatío", "Tango", "Flamenco", "Salsa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué muralista mexicano pintó \"El hombre controlador del universo\" en el Palacio de Bellas Artes?", opciones: ["Diego Rivera", "David Alfaro Siqueiros", "José Clemente Orozco", "Rufino Tamayo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escritor mexicano es autor de \"La región más transparente\" y \"La muerte de Artemio Cruz\"?", opciones: ["Carlos Fuentes", "Juan Rulfo", "Octavio Paz", "Mariano Azuela"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué ensayo de Octavio Paz, publicado en 1950, analiza la identidad mexicana?", opciones: ["El laberinto de la soledad", "Pedro Páramo", "La región más transparente", "Los de abajo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué periodista y escritora mexicana ganó el Premio Cervantes en 2013?", opciones: ["Elena Poniatowska", "Rosario Castellanos", "Ángeles Mastretta", "Laura Esquivel"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué escritora mexicana es autora de \"Como agua para chocolate\"?", opciones: ["Laura Esquivel", "Elena Poniatowska", "Rosario Castellanos", "Ángeles Mastretta"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué muralista mexicano pintó \"El hombre en llamas\" en el Hospicio Cabañas de Guadalajara?", opciones: ["José Clemente Orozco", "Diego Rivera", "David Alfaro Siqueiros", "Rufino Tamayo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué corriente artística mexicana del siglo XX se caracterizó por murales de temática social y política en edificios públicos?", opciones: ["Muralismo mexicano", "Cubismo", "Impresionismo", "Surrealismo europeo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué pintora mexicana, cercana a Frida Kahlo, exploró el surrealismo con obras como \"La creación de las aves\"?", opciones: ["Remedios Varo", "María Izquierdo", "Leonora Carrington", "Frida Kahlo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento de cuerda pequeño, típico del mariachi, tiene un sonido agudo?", opciones: ["Vihuela", "Violín", "Guitarrón", "Arpa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento grande de cuerda, con sonido grave, es la base rítmica del mariachi?", opciones: ["Guitarrón", "Vihuela", "Contrabajo", "Bajo eléctrico"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Qué plato mexicano de tortilla rellena, doblada o enrollada, existe en decenas de variantes?", opciones: ["Taco", "Sushi", "Hamburguesa", "Pizza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué salsa mexicana, hecha de aguacate, es mundialmente popular?", opciones: ["Guacamole", "Ketchup", "Mostaza", "Mayonesa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida alcohólica mexicana, similar al tequila pero de otro agave, es originaria de Oaxaca?", opciones: ["Mezcal", "Ron", "Vodka", "Ginebra"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato mexicano de maíz relleno, envuelto en hoja y cocido al vapor, es típico de festividades?", opciones: ["Tamal", "Empanada", "Arepa", "Pupusa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué chile relleno y bañado en salsa de nogada es un platillo festivo típico de septiembre?", opciones: ["Chiles en nogada", "Mole poblano", "Pozole", "Enchiladas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Qué salsa mexicana oscura, con chocolate y chiles, es típica de Puebla y Oaxaca?", opciones: ["Mole", "Guacamole", "Pico de gallo", "Adobo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué sopa mexicana de maíz cacahuazintle y carne de cerdo se sirve en festividades?", opciones: ["Pozole", "Menudo", "Caldo de res", "Consomé"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida no alcohólica mexicana, de maíz y cacao, tiene raíces prehispánicas?", opciones: ["Atole (o champurrado)", "Horchata", "Chicha", "Pulque"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida fermentada mexicana, de origen prehispánico, se extrae del agave?", opciones: ["Pulque", "Tequila", "Mezcal", "Vino"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato mexicano de tortilla frita, cubierta de salsa, queso y crema, se llama?", opciones: ["Enchilada", "Quesadilla", "Taco", "Burrito"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué antojito mexicano de tortilla doblada con queso derretido y otros rellenos se llama?", opciones: ["Quesadilla", "Enchilada", "Tostada", "Sope"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué cítrico pequeño y ácido, muy usado para marinar y en bebidas mexicanas, se usa constantemente en la cocina?", opciones: ["Limón", "Naranja", "Toronja", "Mandarina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Cuántos tipos de mole se reconocen tradicionalmente en la gastronomía de Oaxaca (los \"siete moles\")?", opciones: ["7", "3", "12", "5"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué platillo mexicano se sirve con nogada, granada y perejil, imitando los colores de la bandera?", opciones: ["Chiles en nogada", "Mole poblano", "Pozole", "Cochinita pibil"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué técnica de cocción yucateca envuelve la carne de cerdo en hoja de plátano y la cuece bajo tierra o en horno?", opciones: ["Cochinita pibil", "Barbacoa", "Birria", "Carnitas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué guiso mexicano de carne de res o chivo, cocido en pozo o vapor, es típico de Jalisco e Hidalgo?", opciones: ["Barbacoa", "Birria", "Cochinita pibil", "Carnitas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué platillo de Jalisco, un guiso picante de carne en caldo rojo, se ha popularizado internacionalmente como \"tacos de birria\"?", opciones: ["Birria", "Barbacoa", "Pozole", "Menudo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué insecto comestible, considerado manjar en la gastronomía mexicana (especialmente Oaxaca), se sirve frito con sal y limón?", opciones: ["Chapulines", "Escamoles únicamente", "Gusanos de maguey únicamente", "Ninguno se come en México"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué platillo mexicano de carne de cerdo cocida lentamente en su propia grasa se llama?", opciones: ["Carnitas", "Cochinita pibil", "Birria", "Barbacoa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué chile ahumado y seco mexicano, derivado del jalapeño, se usa en salsas y adobos?", opciones: ["Chipotle", "Habanero", "Serrano", "Poblano"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué queso mexicano, blanco y fresco, se desmorona sobre platillos como enchiladas y tostadas?", opciones: ["Queso fresco (o cotija)", "Queso manchego", "Mozzarella", "Queso gouda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida caliente mexicana de maíz, dulce y espesa, se toma tradicionalmente con tamales?", opciones: ["Atole", "Café", "Chocolate suizo", "Té"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Qué mariposa migratoria, famosa por viajar miles de km hasta México cada invierno, se refugia en Michoacán?", opciones: ["Mariposa monarca", "Mariposa azul", "Mariposa cola de golondrina", "Polilla luna"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave rapaz, devorando una serpiente sobre un nopal, aparece en el escudo nacional de México?", opciones: ["Águila real", "Cóndor", "Halcón", "Búho"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué desierto mexicano alberga gran diversidad de cactus y fauna adaptada a la aridez?", opciones: ["Desierto de Sonora", "Selva Amazónica", "Bosque nuboso", "Tundra"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran felino manchado, el más grande de América, habita selvas del sureste mexicano?", opciones: ["Jaguar", "León", "Tigre", "Leopardo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero marino gigante visita las costas del Pacífico mexicano (Baja California) para reproducirse?", opciones: ["Ballena gris", "Foca", "Morsa", "Delfín"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿En qué estado mexicano se ubican los santuarios de la mariposa monarca?", opciones: ["Michoacán", "Oaxaca", "Chiapas", "Yucatán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué laguna de Baja California Sur es famosa por el avistamiento de ballenas grises?", opciones: ["Laguna San Ignacio", "Laguna de Términos", "Laguna de Bacalar", "Laguna del Carmen"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué reserva de la biosfera mexicana, en Chiapas, protege selva lacandona?", opciones: ["Montes Azules", "Sian Ka'an", "El Pinacate", "Calakmul"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué reserva de la biosfera en Quintana Roo, Patrimonio de la Humanidad, protege manglares y arrecifes?", opciones: ["Sian Ka'an", "Montes Azules", "Calakmul", "El Vizcaíno"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave nacional de México, cazadora, aparece en el escudo devorando una serpiente?", opciones: ["Águila real", "Quetzal", "Zopilote", "Colibrí"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué pez de acuario, hoy en peligro crítico, es endémico de los canales de Xochimilco en Ciudad de México?", opciones: ["Ajolote", "Pez payaso", "Pez ángel", "Guppy"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué gran arrecife de coral, compartido con Belice, Guatemala y Honduras, bordea el Caribe mexicano?", opciones: ["Sistema Arrecifal Mesoamericano", "Gran Barrera de Coral", "Jardines de la Reina", "Arrecife de Fiyi"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Qué anfibio mexicano, capaz de regenerar extremidades, es un ícono de la biología por su neotenia?", opciones: ["Ajolote", "Salamandra de fuego", "Rana toro", "Tritón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿En qué lago/canales de Ciudad de México habita naturalmente el ajolote?", opciones: ["Xochimilco", "Lago de Chapala", "Lago de Pátzcuaro", "Lago de Texcoco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué reserva de la biosfera mexicana, la más grande de Latinoamérica, protege el desierto de Baja California?", opciones: ["El Vizcaíno", "El Pinacate", "Sian Ka'an", "Montes Azules"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Cuántas especies de cactus aproximadamente alberga México, uno de los países con mayor diversidad del mundo?", opciones: ["Más de 900", "Menos de 10", "Exactamente 50", "Más de 5.000"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué zona natural protegida mexicana, en el Golfo de California, es conocida como \"el acuario del mundo\" según Jacques Cousteau?", opciones: ["Islas del Golfo de California", "Sian Ka'an", "Montes Azules", "El Pinacate"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué ballena, la más grande del mundo, ha sido avistada en aguas del Golfo de California?", opciones: ["Ballena azul", "Ballena jorobada", "Ballena gris", "Cachalote"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero marino pequeño, en grave peligro de extinción, es endémico del Golfo de California?", opciones: ["Vaquita marina", "Delfín rosado", "Foca monje", "Nutria marina"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué volcán mexicano, el más joven del hemisferio norte, nació de la nada en un campo de maíz en 1943?", opciones: ["Paricutín", "Popocatépetl", "Iztaccíhuatl", "Nevado de Toluca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué zona semidesértica mexicana, en Sonora, es Patrimonio de la Humanidad por sus paisajes volcánicos y biodiversidad?", opciones: ["El Pinacate y Gran Desierto de Altar", "El Vizcaíno", "Sian Ka'an", "Montes Azules"], correctaIndex: 0, fuente: "UNESCO", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué serpiente venenosa de cascabel es endémica y común en varias regiones de México?", opciones: ["Serpiente de cascabel", "Cobra real", "Mamba negra", "Víbora de Gabón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte más popular en México?", opciones: ["Fútbol", "Béisbol", "Baloncesto", "Rugby"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué evento deportivo mundial ha organizado México en dos ocasiones (1970 y 1986)?", opciones: ["Copa Mundial de la FIFA", "Juegos Olímpicos", "Super Bowl", "Champions League"], correctaIndex: 0, fuente: "FIFA", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿En qué ciudad mexicana se celebraron los Juegos Olímpicos de 1968?", opciones: ["Ciudad de México", "Guadalajara", "Monterrey", "Acapulco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué deporte de lucha libre mexicana, con máscaras coloridas, es un espectáculo popular?", opciones: ["Lucha libre", "Boxeo", "Judo", "Karate"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué club de fútbol mexicano es uno de los más populares y ganadores del país?", opciones: ["Club América", "Real Madrid", "Boca Juniors", "River Plate"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Qué boxeador mexicano, con récord histórico de más de 100 combates, es considerado el mejor boxeador mexicano de todos los tiempos (activo en los 80-90)?", opciones: ["Julio César Chávez", "Canelo Álvarez", "Marco Antonio Barrera", "Erik Morales"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué luchador mexicano enmascarado, ícono de la lucha libre, es reconocido como \"El Santo\"?", opciones: ["El Santo", "Blue Demon", "Mil Máscaras", "Rey Mysterio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué portero mexicano ha participado en múltiples Copas Mundiales, siendo uno de los referentes de la selección?", opciones: ["Guillermo Ochoa", "Jorge Campos", "Hugo Sánchez", "Rafael Márquez"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué futbolista mexicano fue máximo goleador histórico de la liga española jugando para el Real Madrid en los 80?", opciones: ["Hugo Sánchez", "Rafael Márquez", "Cuauhtémoc Blanco", "Javier Hernández"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué defensor mexicano fue el primer futbolista de su país en jugar 5 Copas Mundiales?", opciones: ["Rafael Márquez", "Hugo Sánchez", "Guillermo Ochoa", "Andrés Guardado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué delantero mexicano, apodado \"Chicharito\", jugó en el Manchester United?", opciones: ["Javier Hernández", "Hugo Sánchez", "Rafael Márquez", "Carlos Vela"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué ciudad mexicana alberga el Estadio Azteca, uno de los más icónicos del fútbol mundial?", opciones: ["Ciudad de México", "Guadalajara", "Monterrey", "Puebla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿En qué Mundial de fútbol, celebrado en México, Diego Maradona anotó el famoso gol \"La Mano de Dios\" contra Inglaterra?", opciones: ["1986", "1970", "1994", "1978"], correctaIndex: 0, fuente: "FIFA", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué corredor mexicano de Fórmula 1 compitió en los años 2010-2020 para Force India y Racing Point?", opciones: ["Sergio Pérez", "Pedro Rodríguez", "Ricardo Rodríguez", "Héctor Rebaque"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué piloto mexicano de los años 60, fallecido en un accidente en 1962, da nombre a una curva del Autódromo Hermanos Rodríguez?", opciones: ["Ricardo Rodríguez", "Sergio Pérez", "Pedro Rodríguez", "Héctor Rebaque"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué autódromo de Ciudad de México alberga el Gran Premio de México de F1?", opciones: ["Autódromo Hermanos Rodríguez", "Autódromo de Interlagos", "Circuito de las Américas", "Monza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué clavadista mexicana ganó múltiples medallas olímpicas en clavados, siendo referente del deporte?", opciones: ["Paola Espinosa", "Ana Guevara", "Soraya Jiménez", "María del Rosario Espinoza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué taekwondista mexicana ganó la primera medalla de oro olímpica individual femenina de México, en Sídney 2000?", opciones: ["Soraya Jiménez", "Paola Espinosa", "Ana Guevara", "María del Rosario Espinoza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué velocista mexicana fue campeona mundial de 400m en 2001 y 2003?", opciones: ["Ana Gabriela Guevara", "Soraya Jiménez", "Paola Espinosa", "Bárbara Mair"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué Juegos Olímpicos la taekwondista mexicana María del Rosario Espinoza ganó la medalla de oro?", opciones: ["Beijing 2008", "Londres 2012", "Río 2016", "Tokio 2020"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué exjugador mexicano de la NBA, ala-pívot, jugó para Dallas, Golden State y otros equipos en los 2000-2010?", opciones: ["Eduardo Nájera", "Horacio Llamas", "Gustavo Ayón", "Jorge Gutiérrez"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Cuántas veces ha sido México anfitrión de una Copa Mundial de fútbol masculina (hasta 2022)?", opciones: ["2 (1970 y 1986)", "1", "3", "0"], correctaIndex: 0, fuente: "FIFA", dificultad: "dificil" },
    ],
  },
};
