import type { Categoria, PreguntaTrivia } from "./onboarding-data";
import type { RondaId } from "./trivia-bank-types";

type BancoPorRonda = Record<RondaId, PreguntaTrivia[]>;

// Banco real de Costa Rica (Ruta 2 — Ritmo y Trópico). Mismo estándar que Colombia/Perú/Chile/Brasil/Cuba.
export const BANCO_COSTA_RICA: Record<Categoria, BancoPorRonda> = {
  Geografía: {
    Explorador: [
      { categoria: "Geografía", pregunta: "¿Cuál es la capital de Costa Rica?", opciones: ["San José", "Alajuela", "Cartago", "Heredia"], correctaIndex: 0, fuente: "REST Countries API", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué océano bordea a Costa Rica por el oeste?", opciones: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Qué mar bordea a Costa Rica por el este?", opciones: ["Mar Caribe", "Mar Rojo", "Mar Negro", "Mar Mediterráneo"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿Cuál es el idioma oficial de Costa Rica?", opciones: ["Español", "Inglés", "Portugués", "Francés"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Geografía", pregunta: "¿En qué región está ubicada Costa Rica?", opciones: ["América Central", "América del Sur", "El Caribe", "Europa"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Geografía", pregunta: "¿Con cuántos países limita Costa Rica?", opciones: ["2", "3", "1", "4"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la segunda provincia más poblada de Costa Rica?", opciones: ["Alajuela", "Cartago", "Heredia", "Puntarenas"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué cordillera volcánica atraviesa Costa Rica de noroeste a sureste?", opciones: ["Cordillera Volcánica Central", "Cordillera de los Andes", "Sierra Madre", "Montañas Rocosas"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué volcán, uno de los más famosos de Costa Rica, se ubica cerca de La Fortuna?", opciones: ["Volcán Arenal", "Volcán Poás", "Volcán Irazú", "Volcán Turrialba"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuál es la moneda oficial de Costa Rica?", opciones: ["Colón costarricense", "Peso", "Dólar", "Quetzal"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué país limita a Costa Rica por el norte?", opciones: ["Nicaragua", "Panamá", "Honduras", "El Salvador"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Qué país limita a Costa Rica por el sureste?", opciones: ["Panamá", "Nicaragua", "Colombia", "Honduras"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Geografía", pregunta: "¿Cuál es el punto más alto de Costa Rica?", opciones: ["Cerro Chirripó", "Volcán Arenal", "Volcán Poás", "Volcán Irazú"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué parque nacional protege el Cerro Chirripó, el punto más alto del país?", opciones: ["Parque Nacional Chirripó", "Parque Nacional Corcovado", "Parque Nacional Tortuguero", "Parque Nacional Manuel Antonio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué península costarricense, en el Pacífico sur, alberga el Parque Nacional Corcovado?", opciones: ["Península de Osa", "Península de Nicoya", "Península de Azuero", "Yucatán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué península costarricense, en el Pacífico norte, es famosa por sus playas turísticas?", opciones: ["Península de Nicoya", "Península de Osa", "Baja California", "Yucatán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿En qué provincia se ubica la capital San José?", opciones: ["San José", "Alajuela", "Cartago", "Heredia"], correctaIndex: 0, fuente: "Wikidata", dificultad: "medio" },
      { categoria: "Geografía", pregunta: "¿Cuántas provincias tiene Costa Rica?", opciones: ["7", "5", "9", "10"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
      { categoria: "Geografía", pregunta: "¿Qué volcán, activo cerca de la capital, cubrió de cenizas San José entre 1963 y 1965?", opciones: ["Irazú", "Arenal", "Poás", "Turrialba"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué lago artificial, el más grande de Costa Rica, se formó por una represa hidroeléctrica?", opciones: ["Lago Arenal", "Lago de Nicaragua", "Lago Titicaca", "Lago Atitlán"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Qué antigua capital colonial de Costa Rica fue destruida varias veces por erupciones del volcán Irazú?", opciones: ["Cartago", "Heredia", "Alajuela", "Liberia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Geografía", pregunta: "¿Cuál de las dos costas costarricenses tiene más extensión de litoral?", opciones: ["Pacífico", "Caribe", "Igual extensión", "Ninguna"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
    ],
  },
  Historia: {
    Explorador: [
      { categoria: "Historia", pregunta: "¿Qué país europeo colonizó Costa Rica?", opciones: ["España", "Portugal", "Inglaterra", "Francia"], correctaIndex: 0, fuente: "Wikipedia — Historia de Costa Rica", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año Costa Rica se independizó de España?", opciones: ["1821", "1810", "1900", "1848"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿A qué federación centroamericana perteneció brevemente Costa Rica tras su independencia?", opciones: ["Provincias Unidas de Centroamérica", "Imperio Español", "Imperio Portugués", "Gran Colombia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿En qué año Costa Rica abolió su ejército de forma permanente?", opciones: ["1948", "1900", "1821", "2000"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Historia", pregunta: "¿Quién es el expresidente costarricense que abolió el ejército tras la guerra civil de 1948?", opciones: ["José Figueres Ferrer", "Óscar Arias", "Juan Mora Fernández", "Rafael Ángel Calderón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Historia", pregunta: "¿En qué año ocurrió la Guerra Civil de Costa Rica que llevó a la abolición del ejército?", opciones: ["1948", "1821", "1900", "1856"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Quién fue el primer jefe de estado de Costa Rica tras la independencia?", opciones: ["Juan Mora Fernández", "José Figueres", "Braulio Carrillo", "Tomás Guardia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué expresidente costarricense ganó el Premio Nobel de la Paz en 1987?", opciones: ["Óscar Arias", "José Figueres", "Laura Chinchilla", "Carlos Alvarado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué filibustero estadounidense intentó apoderarse de Centroamérica y fue derrotado en 1856?", opciones: ["William Walker", "Theodore Roosevelt", "Cecil Rhodes", "Sam Houston"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿En qué batalla de 1856 los costarricenses derrotaron a las tropas de William Walker?", opciones: ["Batalla de Santa Rosa", "Batalla de Ayacucho", "Batalla de Boyacá", "Batalla de Carabobo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué presidente costarricense impulsó la construcción del ferrocarril al Caribe en el siglo XIX?", opciones: ["Tomás Guardia", "Juan Mora Fernández", "Braulio Carrillo", "José Figueres"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Historia", pregunta: "¿Qué producto agrícola impulsó la economía costarricense desde el siglo XIX, ligado al ferrocarril?", opciones: ["Café", "Petróleo", "Oro", "Algodón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Historia", pregunta: "¿Qué héroe nacional costarricense murió luchando contra William Walker en 1856?", opciones: ["Juan Santamaría", "José Figueres", "Braulio Carrillo", "Tomás Guardia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué ciudad costarricense es honrada con el feriado de Juan Santamaría, el 11 de abril?", opciones: ["Alajuela", "San José", "Cartago", "Heredia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿En qué año se promulgó la Constitución Política de Costa Rica actualmente vigente?", opciones: ["1949", "1821", "1900", "1948"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué junta de gobierno lideró José Figueres tras la guerra civil de 1948?", opciones: ["Junta Fundadora de la Segunda República", "Junta Militar", "Consejo de Estado", "Directorio Revolucionario"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿En qué año se trasladó la capital de Costa Rica de Cartago a San José?", opciones: ["1823", "1821", "1848", "1900"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué conflicto entre Cartago y San José en 1823 definió el traslado de la capital?", opciones: ["Batalla de Ochomogo", "Batalla de Santa Rosa", "Batalla de Rivas", "Batalla de Ayacucho"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué presidenta fue la primera mujer en gobernar Costa Rica, electa en 2010?", opciones: ["Laura Chinchilla", "Margarita Penón", "Sonia Picado", "Epsy Campbell"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué antigua provincia colonial española integraba Costa Rica junto con Guatemala, Honduras, El Salvador y Nicaragua?", opciones: ["Capitanía General de Guatemala", "Virreinato de Nueva España", "Virreinato del Perú", "Virreinato de Nueva Granada"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Historia", pregunta: "¿Qué guerra centroamericana de 1856-57 enfrentó a Costa Rica contra el filibustero William Walker?", opciones: ["Guerra Nacional (Campaña Nacional)", "Guerra de los Mil Días", "Guerra del Pacífico", "Guerra de la Triple Alianza"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Historia", pregunta: "¿Qué expresidente costarricense fundó el Partido Liberación Nacional en 1951?", opciones: ["José Figueres", "Óscar Arias", "Rafael Ángel Calderón", "Juan Mora Fernández"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Cultura: {
    Explorador: [
      { categoria: "Cultura", pregunta: "¿Cómo se conoce popularmente a los costarricenses?", opciones: ["Ticos", "Chapines", "Catrachos", "Nicas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué expresión costarricense, símbolo de su cultura pacífica, se usa para saludar o despedirse?", opciones: ["Pura vida", "Buena onda", "Qué chévere", "Órale"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué carreta de madera pintada de colores es un símbolo artesanal nacional de Costa Rica?", opciones: ["Carreta típica", "Alebrije", "Molas", "Sombrero vueltiao"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué religión es mayoritaria en Costa Rica?", opciones: ["Catolicismo", "Islam", "Budismo", "Hinduismo"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Cultura", pregunta: "¿Qué deporte es el más popular en Costa Rica?", opciones: ["Fútbol", "Béisbol", "Rugby", "Críquet"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Cultura", pregunta: "¿En qué ciudad se originó la tradición de las carretas pintadas costarricenses, Patrimonio de la Humanidad?", opciones: ["Sarchí", "San José", "Cartago", "Liberia"], correctaIndex: 0, fuente: "UNESCO", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué instrumento musical, típico de Guanacaste, se hace con calabazo y teclas de madera?", opciones: ["Marimba", "Arpa", "Bandoneón", "Charango"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué provincia costarricense es cuna de la cultura de fuerte tradición vaquera?", opciones: ["Guanacaste", "Limón", "Cartago", "Heredia"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué provincia costarricense caribeña tiene fuerte influencia cultural afrocaribeña?", opciones: ["Limón", "Guanacaste", "Alajuela", "Puntarenas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué baile folclórico, con influencia española, es representativo de Guanacaste?", opciones: ["Punto guanacasteco", "Tango", "Flamenco", "Salsa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué escritor costarricense es autor de \"Mamita Yunai\", novela sobre las bananeras?", opciones: ["Carlos Luis Fallas", "Yolanda Oreamuno", "Carmen Naranjo", "Fabián Dobles"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Cultura", pregunta: "¿Qué sombrero es parte del traje típico masculino costarricense?", opciones: ["Sombrero de pintón (traje típico)", "Sombrero vueltiao", "Sombrero charro", "Panamá"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Cultura", pregunta: "¿Qué escritora costarricense es autora de \"La ruta de su evasión\"?", opciones: ["Yolanda Oreamuno", "Carmen Naranjo", "Carlos Luis Fallas", "Eunice Odio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué poeta costarricense, voz lírica destacada del país, escribió \"Los elementos terrestres\"?", opciones: ["Eunice Odio", "Yolanda Oreamuno", "Carmen Naranjo", "Ana Istarú"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué grupo indígena costarricense, ubicado en Talamanca, mantiene vivas tradiciones ancestrales?", opciones: ["Bribri", "Maya", "Náhuatl", "Quechua"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué otro grupo indígena, vecino de los Bribri en Talamanca, es reconocido en Costa Rica?", opciones: ["Cabécar", "Wayúu", "Aimara", "Mapuche"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué festival religioso, con romería masiva a Cartago cada 2 de agosto, honra a la Virgen de los Ángeles?", opciones: ["Romería a la Basílica de los Ángeles", "Carnaval", "Semana Santa", "Día de los Muertos"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué esferas precolombinas de piedra, Patrimonio de la Humanidad, se hallan en el sur de Costa Rica?", opciones: ["Esferas de piedra del Diquís", "Moáis", "Estelas mayas", "Nazca"], correctaIndex: 0, fuente: "UNESCO", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué cultura precolombina talló las esferas de piedra de la región del Diquís?", opciones: ["Cultura Diquís", "Cultura Maya", "Cultura Azteca", "Cultura Inca"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿En qué zona costarricense se celebra la tradicional \"Fiesta de los Diablitos\" de fin de año?", opciones: ["Zona Boruca (Puntarenas)", "Limón", "Heredia", "Cartago"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Cultura", pregunta: "¿Qué grupo indígena celebra la tradicional \"Fiesta de los Diablitos\" a fin de año?", opciones: ["Boruca", "Bribri", "Cabécar", "Huetar"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Cultura", pregunta: "¿Qué museo en San José exhibe orfebrería precolombina de oro?", opciones: ["Museo del Oro Precolombino", "Museo del Prado", "Museo del Louvre", "Museo Británico"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
    ],
  },
  Gastronomía: {
    Explorador: [
      { categoria: "Gastronomía", pregunta: "¿Cuál es el desayuno tradicional costarricense de arroz y frijoles revueltos?", opciones: ["Gallo pinto", "Moros y cristianos", "Casamiento", "Ropa vieja"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida de arroz o avena, endulzada y con canela, es típica en Costa Rica?", opciones: ["Horchata (resbaladera)", "Chicha", "Atole", "Champola"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta tropical es uno de los principales productos de exportación de Costa Rica?", opciones: ["Piña", "Manzana", "Uva", "Pera"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué grano es históricamente uno de los productos agrícolas más importantes de Costa Rica?", opciones: ["Café", "Trigo", "Arroz", "Cebada"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Gastronomía", pregunta: "¿Qué plato costarricense de carne, arroz, frijoles, plátano y ensalada se sirve en un solo plato?", opciones: ["Casado", "Feijoada", "Ajiaco", "Pabellón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Gastronomía", pregunta: "¿Qué sopa costarricense de mariscos y leche de coco es típica de la costa caribeña?", opciones: ["Rondón", "Ajiaco", "Sancocho", "Mondongo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué tamal costarricense envuelto en hoja de plátano se prepara tradicionalmente en Navidad?", opciones: ["Tamal costarricense", "Hallaca venezolana", "Humita", "Pupusa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida fermentada de maíz es tradicional en algunas zonas rurales de Costa Rica?", opciones: ["Chicha", "Pulque", "Sake", "Hidromiel"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué plátano frito y dulce acompaña muchos platos costarricenses?", opciones: ["Plátano maduro frito", "Tostones", "Yuca frita", "Papa frita"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué queso fresco, típico de zonas rurales costarricenses, se usa en muchos platos?", opciones: ["Queso Turrialba", "Queso manchego", "Queso gouda", "Queso brie"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué picadillo de vegetales, acompañamiento típico costarricense, se hace de chayote o papa?", opciones: ["Picadillo", "Ceviche", "Guacamole", "Escabeche"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Gastronomía", pregunta: "¿Qué ceviche costarricense, marinado en limón, suele llevar pescado o corvina?", opciones: ["Ceviche costarricense", "Sushi", "Tartar", "Carpaccio"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Gastronomía", pregunta: "¿Qué olla de carne con múltiples vegetales (yuca, camote, plátano, elote) es un plato tradicional dominical en Costa Rica?", opciones: ["Olla de carne", "Ajiaco", "Sancocho colombiano", "Cocido madrileño"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida tradicional costarricense se prepara con la semilla de \"chan\" remojada en agua con limón?", opciones: ["Fresco de chan", "Chicha morada", "Atole", "Horchata mexicana"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué tubérculo o vegetal, base del picadillo costarricense, es una calabaza espinosa?", opciones: ["Chayote", "Papa", "Ñame", "Malanga"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué dulce costarricense, hecho con leche cocida lentamente hasta espesar, es típico en Navidad?", opciones: ["Leche quemada (cajeta)", "Flan", "Arroz con leche", "Natilla"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué región costarricense es la mayor productora de café del país, con microclimas reconocidos internacionalmente?", opciones: ["Valle Central", "Guanacaste", "Limón", "Puntarenas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta ácida y pequeña, muy usada en refrescos costarricenses, se llama \"cas\"?", opciones: ["Cas", "Guayaba", "Maracuyá", "Tamarindo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué salsa costarricense, agridulce y a base de vegetales, acompaña el gallo pinto y otros platos?", opciones: ["Salsa Lizano", "Salsa inglesa", "Salsa de soya", "Kétchup"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué bebida de maíz fermentado se prepara para festividades como las Fiestas de los Diablitos?", opciones: ["Chicha de maíz", "Pulque", "Tepache", "Sake"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Gastronomía", pregunta: "¿Qué variedad de café, cultivada en las alturas del Valle Central, es reconocida internacionalmente por su calidad?", opciones: ["Café de altura (Arábica)", "Café Robusta", "Café instantáneo", "Café descafeinado"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Gastronomía", pregunta: "¿Qué fruta tropical, además de la piña, es un importante producto de exportación agrícola costarricense?", opciones: ["Banano", "Manzana", "Durazno", "Cereza"], correctaIndex: 0, fuente: "Wikidata", dificultad: "dificil" },
    ],
  },
  Naturaleza: {
    Explorador: [
      { categoria: "Naturaleza", pregunta: "¿Qué ave colorida y grande, símbolo de la selva tropical, se puede ver en Costa Rica?", opciones: ["Tucán", "Pingüino", "Avestruz", "Emú"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué mamífero lento y arbóreo, de movimientos pausados, es un ícono de Costa Rica?", opciones: ["Perezoso", "Canguro", "Koala", "Oso panda"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué reptil marino llega a desovar en playas costarricenses como Tortuguero?", opciones: ["Tortuga marina", "Cocodrilo", "Iguana", "Lagarto"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué porcentaje aproximado del territorio de Costa Rica está cubierto por áreas protegidas?", opciones: ["Más de la cuarta parte", "Menos del 1%", "La mitad exacta", "Ninguno"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Naturaleza", pregunta: "¿Qué tipo de bosque, siempre verde y con alta humedad, cubre gran parte de Costa Rica?", opciones: ["Bosque tropical lluvioso", "Desierto", "Tundra", "Estepa"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional costarricense, en el Caribe, es famoso por el desove de tortugas verdes?", opciones: ["Tortuguero", "Corcovado", "Manuel Antonio", "Poás"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué parque nacional del Pacífico sur ha sido descrito como uno de los lugares más biodiversos del planeta?", opciones: ["Corcovado", "Tortuguero", "Cahuita", "Arenal"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué felino, el más grande de América, habita algunas reservas de Costa Rica?", opciones: ["Jaguar", "León", "Tigre", "Leopardo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué primate pequeño y de cara blanca es común observar en los parques costarricenses?", opciones: ["Mono capuchino de cara blanca", "Gorila", "Chimpancé", "Orangután"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué reserva biológica costarricense, famosa por su bosque nuboso, protege gran diversidad de orquídeas y aves?", opciones: ["Monteverde", "Corcovado", "Tortuguero", "Cahuita"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué ave, símbolo de los bosques nubosos centroamericanos, es codiciada por observadores de aves en Monteverde?", opciones: ["Quetzal", "Águila calva", "Cóndor", "Flamenco"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Naturaleza", pregunta: "¿Qué anfibio, hoy posiblemente extinto, era endémico de Monteverde y de color dorado brillante?", opciones: ["Sapo dorado", "Rana venenosa", "Rana toro", "Sapo común"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Naturaleza", pregunta: "¿Qué porcentaje de la biodiversidad mundial se estima que alberga Costa Rica, pese a su reducido tamaño?", opciones: ["Cerca del 5%", "Cerca del 50%", "Menos del 0,1%", "Cerca del 20%"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué rana venenosa, de cuerpo rojo y patas azules, es un ícono fotografiado de Costa Rica?", opciones: ["Rana flecha roja y azul", "Rana de ojos rojos", "Sapo dorado", "Rana toro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué famosa rana verde de ojos rojos, símbolo fotográfico de la selva tropical, habita Costa Rica?", opciones: ["Rana de ojos rojos (Agalychnis callidryas)", "Rana flecha", "Sapo dorado", "Rana toro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de perezoso, junto con el de tres dedos, habita Costa Rica?", opciones: ["Perezoso de dos dedos", "Perezoso gigante extinto", "Oso hormiguero", "Armadillo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué volcán activo alberga en su base el Parque Nacional Volcán Arenal, con bosques y biodiversidad?", opciones: ["Arenal", "Poás", "Irazú", "Turrialba"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué golfo del Pacífico costarricense es refugio de ballenas jorobadas en su migración?", opciones: ["Golfo Dulce", "Golfo de Nicoya", "Golfo de México", "Golfo Pérsico"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué isla costarricense, remota en el Pacífico, fue Patrimonio de la Humanidad e inspiró \"Jurassic Park\"?", opciones: ["Isla del Coco", "Isla de Chira", "Isla Tortuga", "Isla Damas"], correctaIndex: 0, fuente: "UNESCO", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Qué especie de tiburón se congrega en gran número cerca de la Isla del Coco, atractivo para el buceo científico?", opciones: ["Tiburón martillo", "Tiburón blanco", "Tiburón ballena", "Tiburón tigre"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Naturaleza", pregunta: "¿Qué mono, el más grande y ruidoso de Costa Rica, se escucha rugir por las mañanas en la selva?", opciones: ["Mono aullador", "Mono araña", "Mono capuchino", "Tití"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Naturaleza", pregunta: "¿Cuántas especies de colibríes aproximadamente se han registrado en Costa Rica?", opciones: ["Más de 50", "Menos de 5", "Exactamente 10", "Más de 500"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
    ],
  },
  Deportes: {
    Explorador: [
      { categoria: "Deportes", pregunta: "¿Cuál es el deporte más popular en Costa Rica?", opciones: ["Fútbol", "Béisbol", "Rugby", "Hockey"], correctaIndex: 0, fuente: "Wikidata", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cuántas veces se ha clasificado la selección de fútbol de Costa Rica a Copas del Mundo (hasta 2022)?", opciones: ["6", "2", "10", "1"], correctaIndex: 0, fuente: "FIFA", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿En qué Mundial de fútbol la selección de Costa Rica llegó sorpresivamente a cuartos de final?", opciones: ["2014", "1990", "2002", "2018"], correctaIndex: 0, fuente: "FIFA", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Qué color de camiseta identifica tradicionalmente a la selección de fútbol de Costa Rica?", opciones: ["Rojo", "Azul", "Verde", "Amarillo"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
      { categoria: "Deportes", pregunta: "¿Cómo se le apoda popularmente a la selección de fútbol de Costa Rica?", opciones: ["La Sele", "Los Cafeteros", "La Tricolor", "Los Charrúas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "facil" },
    ],
    Descubridor: [
      { categoria: "Deportes", pregunta: "¿Qué portero costarricense fue figura clave en el histórico Mundial de 2014?", opciones: ["Keylor Navas", "Bryan Ruiz", "Joel Campbell", "Celso Borges"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿En qué club europeo Keylor Navas ganó múltiples Champions League como portero titular?", opciones: ["Real Madrid", "Barcelona", "Bayern Múnich", "Manchester United"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué delantero costarricense jugó en clubes como el Fulham y el PSV, siendo referente ofensivo de \"La Sele\"?", opciones: ["Joel Campbell", "Keylor Navas", "Bryan Ruiz", "Paulo Wanchope"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué delantero costarricense de los años 90-2000 destacó en la Premier League (Derby County, Manchester City)?", opciones: ["Paulo Wanchope", "Joel Campbell", "Bryan Ruiz", "Keylor Navas"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué capitán costarricense lideró al equipo en el histórico Mundial de Brasil 2014?", opciones: ["Bryan Ruiz", "Keylor Navas", "Joel Campbell", "Celso Borges"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Contra qué selecciones europeas Costa Rica logró histórica victoria y empate en la fase de grupos del Mundial 2014?", opciones: ["Uruguay e Italia", "Alemania y España", "Francia y Portugal", "Bélgica y Croacia"], correctaIndex: 0, fuente: "FIFA", dificultad: "medio" },
      { categoria: "Deportes", pregunta: "¿Qué torneo regional de selecciones de la CONCACAF ha ganado Costa Rica en varias ocasiones?", opciones: ["Copa Oro de la CONCACAF", "Copa América", "Eurocopa", "Copa Africana de Naciones"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "medio" },
    ],
    Experto: [
      { categoria: "Deportes", pregunta: "¿En qué año debutó Costa Rica en una Copa Mundial de fútbol por primera vez?", opciones: ["1990", "1970", "2002", "1950"], correctaIndex: 0, fuente: "FIFA", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué entrenador colombiano dirigió a Costa Rica en su histórica campaña del Mundial 2014?", opciones: ["Jorge Luis Pinto", "José Pékerman", "Carlos Queiroz", "Gustavo Alfaro"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Contra qué selección perdió Costa Rica en penales en los cuartos de final del Mundial 2014?", opciones: ["Países Bajos", "Alemania", "Argentina", "Brasil"], correctaIndex: 0, fuente: "FIFA", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Qué arquero costarricense fue elegido en el equipo ideal del Mundial 2014 por la FIFA?", opciones: ["Keylor Navas", "Bryan Ruiz", "Fabio Marín", "Patrick Pemberton"], correctaIndex: 0, fuente: "FIFA", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Cuántas Champions League ganó Keylor Navas como portero titular del Real Madrid (2014-2019)?", opciones: ["3", "1", "5", "0"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué jugador costarricense de los años 90 fue durante mucho tiempo el máximo goleador histórico de la selección?", opciones: ["Rolando Fonseca", "Bryan Ruiz", "Joel Campbell", "Paulo Wanchope"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿Qué capitán y goleador costarricense más reciente superó el récord histórico de goles de la selección?", opciones: ["Bryan Ruiz", "Rolando Fonseca", "Keylor Navas", "Celso Borges"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "experto" },
      { categoria: "Deportes", pregunta: "¿En qué ciudad costarricense se encuentra el Estadio Nacional, principal escenario deportivo del país?", opciones: ["San José", "Alajuela", "Cartago", "Limón"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿En qué disciplina, además del fútbol, ha destacado tradicionalmente la provincia caribeña de Limón?", opciones: ["Atletismo (velocidad)", "Curling", "Esquí", "Rugby"], correctaIndex: 0, fuente: "Wikipedia", dificultad: "dificil" },
      { categoria: "Deportes", pregunta: "¿Cuántas veces se clasificó Costa Rica consecutivamente a Mundiales entre 2014 y 2022?", opciones: ["3 veces (2014, 2018, 2022)", "1 vez", "5 veces", "Nunca"], correctaIndex: 0, fuente: "FIFA", dificultad: "dificil" },
    ],
  },
};
